CONTRIBUTING.md, README.md
To ensure pull requests meet the standards for commit messages, a new
`CONTRIBUTING.md` document has been added that highlights the best
practice in creating a pull request.
The `README.md` has been updated to show this new change.
=> chore(CONTRIBUTING): add guidelines for contribution

Assets/SteamVR_Unity_Toolkit/Scripts/SteamVR_HeadsetCollisionFade.cs
=> fix(Headset): show warning if fade script is not present

Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_TouchpadWalking.cs, README.md
Adds a property that allows you to toggle whether or not the left or
right controller will allow walking.
=> feat(Controller): disable walking per controller

Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BasicTeleport.cs, Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_HeightAdjustTeleport.cs
Adds 'Teleporting' and 'Teleported' events which pass along
DestinationMarkerEventArgs to any interested parties.
=> feat(Teleport): add events to teleport

Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
Add offset to playAreaCursor relative to hmd position, per discussion in issue #173
=> feat(Pointer): offset playAreaCursor to hint at relative player position

Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BezierPointer.cs, Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_SimplePointer.cs, README.md
Added checks to ignore specified layers when raycasting.
=> feat(Pointer): add raycast ignore layer checks

Assets/SteamVR_Unity_Toolkit/Examples/025_Controls_Overview.unity, Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Drawer.cs, README.md
So far the drawer worked only with x and z axis. It now also detects
the y axis. In addition it supports handle-less drawers and the script
can be put onto the mesh directly without the need to specify the body.
Also a snapping mode has been added to compensate for minor physics
effects.
=> feat(Interaction): enhanced drawer control

Assets/SteamVR_Unity_Toolkit/Examples/025_Controls_Overview.unity, Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Button.cs, ProjectSettings/ProjectSettings.asset
The button control so far used constrained rigidbodies and a manual
check for distance. This turned out to be quite error prone when buttons
are rotated.
A better way to setup the button is with a limited configurable joint.
This way we don't need to do any manual checks and all constraint
calculations are done by the physics engine. This now also allows
rotated and more complex buttons.
=> feat(Interaction): enhance button control

Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
Previously, if the system dashboard was activated by pressing the
system menu button, then the `OnDisable` script would be called on
the Interactable Object, casuing the object to be dropped, which is
not the desired effect. When the dashboard is activated, the
controllers are disabled in Unity so now the force drop on disable
checks to see if the controllers are active before stopping the
interaction.
Also, when the object was a child of the controller, it would not
correctly unparent itself from the controller when it was disabled.
This has also been fixed.
=> fix(Interaction): ensure dropping objects on disable works

Assets/SteamVR_Unity_Toolkit/Prefabs/ConsoleViewerCanvas.prefab, Assets/SteamVR_Unity_Toolkit/Prefabs/ConsoleViewerCanvas.prefab.meta, Assets/SteamVR_Unity_Toolkit/Scripts/Helper/ConsoleViewer.cs, Assets/SteamVR_Unity_Toolkit/Scripts/Helper/ConsoleViewer.cs.meta, README.md
A new prefab has been added that can be dropped into a scene that
will display the console log messages within the game world which
is useful for debugging within VR.
=> feat(utility): add prefab to display console logs

Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Drawer.cs
One needed to pull too strong to open the drawer so far.
=> fix(Interaction): make force of drawer more reasonable

Assets/SteamVR_Unity_Toolkit/Examples/034_Controls_InteractingWithUnityUI.unity, Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_EventSystemVRInput.cs, Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_UIPointer.cs, DOCUMENTATION.md
The UI Pointer can now also be toggled on and off with a button press
in the same way the World Pointer can. This means it works better
with a World Pointer that has the `Hold Button To Activate` parameter
unchecked as the world pointer will stay active until another button
press and now so will the UI pointer.
=> feat(UIPointer): add hold button to activate option

Assets/SteamVR_Unity_Toolkit/Examples/034_Controls_InteractingWithUnityUI.unity, Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_EventSystemVRInput.cs, Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_UIPointer.cs
A UI ScrollView can now be scrolled by using the touchpad axis on the
controller. It also shows the scroll wheel on the controller when
an active and valid scroll is happening.
=> feat(UIPointer): add ability to scroll views with touchpad axis - resolves #375

Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
Previously, it was possible to get the force stop interactions into an
infinite loop by calling `ForceStopTouching` or `ForceStopInteracting`
from within an event listener from the Stop Using event which would
in turn could emit the Stop Using event again and therefore getting
stuck in an infinite loop.
The fix now ensures that any interactable object force stop events
are done at the end of the frame giving the controller scripts time
to correctly clean up.
=> fix(Interaction): make force stop interactions wait for end of frame

Assets/VRTK/Scripts/VRTK_InteractableObject.cs
When an object was force dropped because either the object or the
grabbing controller was disabled, the object would not correctly call
the release code because it was in a co-routine that would not activate
because the object was disabled. This meant the state was not being set
correctly for when the object was re-enabled and would break
`Child_Of_Controller` grab mechanics because the parent wouldn't be
reset after the force release had taken place.
This fix ensures drop code is executed correctly even if the disabled
code is triggered.
=> fix(Interaction): ensure object is released on disable

Assets/VRTK/Scripts/Abstractions/VRTK_WorldPointer.cs
Previously, the Pointer Activate Use Action setting would always
activate the use function on an interactable object even if the Valid
Use Hand was set to ignore the hand the pointer was coming from.
This fix ensures the Pointer Use Action honours the Valid Use Hand
setting and if the pointer hand is not valid then teleport function
will also default to working.
=> fix(Interaction): ensure pointer use activation honours valid hand - resolves #449

Assets/VRTK/Scripts/Helper/UnityEvents.meta, Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractableObject_UnityEvents.cs, Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractableObject_UnityEvents.cs.meta, DOCUMENTATION.md
This adds a helper script to use on Interactable Objects. It will connect all delegates to UnityEvents to use inside the inspector, but is not integrated directly into the Interactable Object script for performance and clutter reasons.
=> feat(Interaction): add helper for interaction unity events

Assets/VRTK/Scripts/Controls/3D/VRTK_Door.cs
Improves visualizing the opening direction of doors a lot. There were
quite some situations so far where gizmos would point into the wrong
direction. These should be much fewer now.
In addition when a hinge joint is added manually this is now taken as
the input for the gizmos and the direction is also derived from it
resulting in a much better editor experience.
=> fix(Interaction): improve door gizmos

Assets/VRTK/Examples/025_Controls_Overview.unity, Assets/VRTK/Scripts/Controls/3D/VRTK_Chest.cs
The handle on the chest is now optional. If not specified the whole
lid is interactable.
=> feat(Interaction): support chests without handle

Assets/VRTK/Scripts/VRTK_Simulator.cs
=> fix(Interaction): improve simulator

README.md
Use a markdown table for listing all the games built with VRTK.
=> chore(README): change game list to table

Assets/VRTK/Examples/038_CameraRig_DashTeleport.unity, Assets/VRTK/Examples/038_CameraRig_DashTeleport.unity.meta, Assets/VRTK/Examples/Resources/Scripts/RendererOffOnDash.cs, Assets/VRTK/Examples/Resources/Scripts/RendererOffOnDash.cs.meta, Assets/VRTK/Scripts/VRTK_DashTeleport.cs, Assets/VRTK/Scripts/VRTK_DashTeleport.cs.meta, DOCUMENTATION.md
Dashing Teleport inspired by the implementation of realities.io.
When dashing through objects their renderers can be turned off.
An example scene has been added to show it in action.
=> feat(Teleport): add dash teleport

Assets/VRTK/Examples/Resources/Scripts/VRTK_ControllerEvents_ListenerExample.cs, Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_ControllerEvents_UnityEvents.cs, Assets/VRTK/Scripts/VRTK_ControllerEvents.cs, DOCUMENTATION.md
The Controller Events script will now throw an event when the
controller is enabled and when the controller is disabled.
=> feat(Controller): add event for controller enable and disable state

Assets/VRTK/Materials/Resources/WorldPointer.mat, Assets/VRTK/Scripts/Shaders/TransparentFresnelBehind.shader, Assets/VRTK/Scripts/Shaders/TransparentFresnelBehind.shader.meta
Default WorldPointer material uses a custom shader with a fresnel rim and transparency.
=> feat(Pointer): update default pointer material

Assets/VRTK/Scripts/VRTK_InteractTouch.cs
fix(Controller): ensure controller colliders scale
The colliders added automatically by the script
are now scaled properly according to the parent scale
=> fix(Controller): ensure controller colliders scale

Assets/VRTK/Editor/VRTK_AdaptiveQualityEditor.cs, Assets/VRTK/Editor/VRTK_AdaptiveQualityEditor.cs.meta, Assets/VRTK/Examples/039_CameraRig_AdaptiveQuality.unity, Assets/VRTK/Examples/039_CameraRig_AdaptiveQuality.unity.meta, Assets/VRTK/Examples/Resources/Materials/GlowingGreen.mat, Assets/VRTK/Examples/Resources/Materials/GlowingGreen.mat.meta, Assets/VRTK/Materials/Resources/AdaptiveQualityDebugVisualization.mat, Assets/VRTK/Materials/Resources/AdaptiveQualityDebugVisualization.mat.meta, Assets/VRTK/SDK/SteamVR/VRTK_SDK_Bridge.cs, Assets/VRTK/Scripts/Shaders/AdaptiveQualityDebugVisualization.shader, Assets/VRTK/Scripts/Shaders/AdaptiveQualityDebugVisualization.shader.meta, Assets/VRTK/Scripts/VRTK_AdaptiveQuality.cs, Assets/VRTK/Scripts/VRTK_AdaptiveQuality.cs.meta, ProjectSettings/EditorBuildSettings.asset, ProjectSettings/QualitySettings.asset, THIRD_PARTY_NOTICES
Adaptive Quality dynamically changes rendering settings to maintain VR
framerate while maximizing GPU utilization.
It includes a debug visualization and supports both command line
arguments and keyboard shortcuts. A new example scene uses way too many
lights to bring down the GPU to show the framerate getting stabilized
by the script.
Because this is based on The Lab Renderer from Valve their license is
included and mentioned in the files that are derived from it.
=> feat(AdaptiveQuality): add Adaptive Quality

Assets/VRTK/Scripts/Controls/3D/VRTK_Lever.cs, Assets/VRTK/Scripts/Controls/3D/VRTK_Spring_Lever.cs, Assets/VRTK/Scripts/Controls/3D/VRTK_Spring_Lever.cs.meta
A new lever 3D control that adds spring loading to
the functionality of VRTK_Lever
=> feat(Controls): add spring lever

Assets/VRTK/Examples/003_Controller_SimplePointer.unity, Assets/VRTK/Examples/Resources/Scripts/ModelVillage_TeleportLocation.cs, Assets/VRTK/Examples/Resources/Scripts/VRTK_ControllerPointerEvents_ListenerExample.cs, Assets/VRTK/Scripts/Abstractions/VRTK_DestinationMarker.cs, Assets/VRTK/Scripts/Abstractions/VRTK_WorldPointer.cs, Assets/VRTK/Scripts/VRTK_BezierPointer.cs, Assets/VRTK/Scripts/VRTK_SimplePointer.cs, DOCUMENTATION.md, ProjectSettings/ProjectSettings.asset
The RaycastHit struct is now passed in the Destination Marker payload
and the RaycastHit.collider is also used to check if a new object is
being collided with as using RaycastHit.transform only checks the top
level rigidbody for changes and not the sub colliders.
=> feat(Pointer): pass RaycastHit struct on destination marker events

Assets/VRTK/Examples/Resources/Materials/Simple_Solid_Colors/Cyan.mat, Assets/VRTK/Examples/Resources/Prefabs/BezierCursor.prefab
The custom bezier cursor prefab has been updated with a new custom
material.
=> fix(Pointer): update custom cursor prefab

Assets/VRTK/Scripts/VRTK_SimplePointer.cs
Add to VRTK_SimplePointer an option to rotate the pointer cursor to
match the normal of the target surface (pointerCursorMatchTargetNormal).
Add to VRTK_SimplePointer an option to scale the pointer cursor
proportionally to the distance from this game object if this is true
(pointerCursorRescaledAlongDistance).
Both these options are useful when using the simple pointer as a gaze
pointer with a custom pointer without a spherical symmetry.
=> feat(Pointer): options to reorient and rescale the pointer cursor

Assets/VRTK/Scripts/VRTK_PlayerPresence.cs
Fixes bug with climb where ungrab sends you in the wrong direction
=> fix(Presence): adjust physics fall to correct for local rotation

Assets/VRTK/Examples/025_Controls_Overview.unity, Assets/VRTK/Scripts/Controls/3D/VRTK_Knob.cs
Knobs have been converted to use configurable joints. This enables
specifying connected rigidbodies like in many other 3d controls already.
Scene 25 contains a new knob on the small door now showcasing this.
While at it also the axis has been switch from world to local so
existing knobs will have to be adapted.
Also the value calculation was fixed which was working more by accident
than by intention. It now uses a heuristics to determine the correct
axis.
=> feat(Interaction): support moving knobs

Assets/VRTK/Scripts/Controls/3D/VRTK_Door.cs, Assets/VRTK/Scripts/Controls/3D/VRTK_Drawer.cs
Fixes issue of force affecting objects after rotation
=> fix(Interaction): use relative instead of world force when snapping - resolves #518

Assets/VRTK/Examples/042_CameraRig_MoveInPlace.unity, Assets/VRTK/Examples/042_CameraRig_MoveInPlace.unity.meta, Assets/VRTK/Scripts/VRTK_MoveInPlace.cs, Assets/VRTK/Scripts/VRTK_MoveInPlace.cs.meta
This PR is to add in the Immersive Movement system to the VRTK.  Immersive Movement has been renamed Real Movement to fall more in line with the VRTK brand and to feel more generic and self-explanitory.
=> feat(Locomotion): add locomotion based on arm swing / head movement - resolves #602

Assets/VRTK/Scripts/VRTK_MoveInPlace.cs
Add an additional method to direct locomotion for Motion In Place.
Controller Direction will average the rotation/direction of the two controllers and use that value for movement.  If only one controller is present, only that one value will be
used.
This is my first PR to VRTK, so please let me know if I need to change anything stylistically.
=> feat(MoveInPlace): add controller rotation control method

Assets/VRTK/Editor/VRTK_AdaptiveQualityEditor.cs, Assets/VRTK/Editor/VRTK_EditorUtilities.cs, Assets/VRTK/Examples/039_CameraRig_AdaptiveQuality.unity, Assets/VRTK/Scripts/Shaders/AdaptiveQualityDebugVisualization.shader, Assets/VRTK/Scripts/VRTK_AdaptiveQuality.cs
This cleans up the code and docs a bit, improves the performance a smaller bit and introduces dynamic adjusting of the render target resolution.
=> Adaptive Quality - Service Pack 1

Assets/VRTK/Scripts/SecondaryControllerGrabActions/VRTK_AxisScaleGrabAction.cs
Add Uniform Scaling option to `VRTK_AxisScaleGrabAction`.
Refactor methods to reuse some code.
Change some `var` to the corresponding type to make the code more
readable (see MSDN and several discussion on the Web about this topic).
=> feat(Interaction): uniform scaling for secondary grab action

Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ObjectTooltip.cs, Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs, Assets/VRTK/Scripts/Pointers/VRTK_BasePointer.cs, Assets/VRTK/Scripts/Utilities/VRTK_AdaptiveQuality.cs
Unity 5.5 provides a number of new ways of dealing with core Unity
features. This commit ensures that if Unity 5.5 is being used that
these new ways are adhered to.
=> feat(Structure): support Unity 5.5 - resolves #764

Assets/VRTK/Editor/VRTK_SDKManagerEditor.cs, Assets/VRTK/Prefabs/Resources/ControllerColliders/Simulator.prefab, Assets/VRTK/Prefabs/Resources/ControllerColliders/Simulator.prefab.meta, Assets/VRTK/Prefabs/VRTK_SimPlayer.prefab, Assets/VRTK/Prefabs/VRTK_SimPlayer.prefab.meta, Assets/VRTK/SDK/Simulator.meta, Assets/VRTK/SDK/Simulator/SDK_ControllerSim.cs, Assets/VRTK/SDK/Simulator/SDK_ControllerSim.cs.meta, Assets/VRTK/SDK/Simulator/SDK_InputSimulator.cs, Assets/VRTK/SDK/Simulator/SDK_InputSimulator.cs.meta, Assets/VRTK/SDK/Simulator/SDK_SimBoundaries.cs, Assets/VRTK/SDK/Simulator/SDK_SimBoundaries.cs.meta, Assets/VRTK/SDK/Simulator/SDK_SimController.cs, Assets/VRTK/SDK/Simulator/SDK_SimController.cs.meta, Assets/VRTK/SDK/Simulator/SDK_SimHeadset.cs, Assets/VRTK/SDK/Simulator/SDK_SimHeadset.cs.meta, Assets/VRTK/SDK/Simulator/SDK_SimSystem.cs, Assets/VRTK/SDK/Simulator/SDK_SimSystem.cs.meta, Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs, README.md
Add new Simulator SDK for using mouse instead of controllers.
Take 2!
=> feat(SDK): add simulator

Assets/VRTK/Prefabs/VRSimulatorCameraRig.prefab, README.md
Style fixes for simulator part in readme
Set MainCamera tag on camera instead of root prefab
=> fix(simulator): fix readme and rig

Assets/VRTK/Scripts/Interactions/SecondaryControllerGrabActions/VRTK_AxisScaleGrabAction.cs
The uniform scale option within the Axis Scale Grab Action now uses
the magnitude between the controllers rather than the distance
calculation as it provides a smoother scale and allows scaling below
the initial grabbed object as well.
This work is based on a pull request by @smygarn
=> fix(Interaction): use magnitude instead of distance for uniform scale

Assets/VRTK/Scripts/Interactions/SecondaryControllerGrabActions/VRTK_ControlDirectionGrabAction.cs
Previously the 2 hand control direction would z lock the rotation by
saving the existing z rotation and then re-applying it after the look
rotation had been done. However, this caused gimbal lock issues putting
the rotation into unexpected positions.
This fix now deals with z lock rotations using a different algorithm
that attempts to compensate and adjust for unwanted rotations.
Thanks to cynicat for the solution.
=> fix(Interaction): improve z locked rotations for 2 hand direction

Assets/VRTK/Editor/VRTK_ObjectSetup.cs, Assets/VRTK/Editor/VRTK_ObjectSetup.cs.meta
Add a new menu item to help with setting up a new Intractable Object.
=> feat(menu): add setup helper

Assets/VRTK/Scripts/UI/VRTK_UIPointer.cs
fix(UIPointer): UI not responding after application loses focus
In Unity 5.5 and above the default `EventSystem` pauses its processing
whenever `OnApplicationFocus(false)` is called on it. The solution is
to subclass the default `EventSystem` and *not* call the base
implementation in `OnApplicationFocus`. The rest of this code works
around some problems when changing the `EventSystem` at runtime while
another one is active and referenced by other objects. See the code
comments for more info on this.
=> fix(UIPointer): UI not responding after application loses focus

Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
The SteamVR Plugin has been updated to version 1.2.0 which removed the
method `SteamVR_Util.Event.Listen`. Since it has not been deprecated it
now causes errors to be thrown in VRTK as this method was used within
the SteamVR Controller SDK.
This fix updates the code to use the new API when found, otherwise it
will fall back to the previous API.
=> fix(SDK): support SteamVR Plugin version 1.2.0

FAQ.md, README.md
The new frequently asked questions document contains a collection
of commonly asked questions and answers to make it easier for users
to find solutions to common issues.
=> docs(FAQ): add frequently asked questions document

Assets/VRTK/Editor/VRTK_SDKManagerEditor.cs
Adds buttons to quickly select the desired SDK in the SDK manager inspector.
=> feat(Editor): add quick select sdk option

Assets/VRTK/Scripts/Locomotion/VRTK_TouchpadMovement.cs, Assets/VRTK/Scripts/Locomotion/VRTK_TouchpadMovement.cs.meta
Adds a new touchpad locomotion script that supports multiple configurable movement options for horizontal and vertical axis.
=> feat(Locomotion): add improved touchpad movement script

Assets/VRTK/SDK/Daydream.meta, Assets/VRTK/SDK/Daydream/DAYDREAM_README.md, Assets/VRTK/SDK/Daydream/DAYDREAM_README.md.meta, Assets/VRTK/SDK/Daydream/DaydreamControllerLog.cs, Assets/VRTK/SDK/Daydream/DaydreamControllerLog.cs.meta, Assets/VRTK/SDK/Daydream/DaydreamReach.cs, Assets/VRTK/SDK/Daydream/DaydreamReach.cs.meta, Assets/VRTK/SDK/Daydream/SDK_DaydreamBoundaries.cs, Assets/VRTK/SDK/Daydream/SDK_DaydreamBoundaries.cs.meta, Assets/VRTK/SDK/Daydream/SDK_DaydreamController.cs, Assets/VRTK/SDK/Daydream/SDK_DaydreamController.cs.meta, Assets/VRTK/SDK/Daydream/SDK_DaydreamHeadset.cs, Assets/VRTK/SDK/Daydream/SDK_DaydreamHeadset.cs.meta, Assets/VRTK/SDK/Daydream/SDK_DaydreamSystem.cs, Assets/VRTK/SDK/Daydream/SDK_DaydreamSystem.cs.meta, Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs
The pull request implements the Daydream SDK for VRTK, which integrates the Google VR Daydream platform with VRTK. See the readme VRTK/Assets/VRTK/SDK/Daydream/DAYDREAM_README.md for usage documentation and details.
=> feat(SDK): implements the Daydream SDK for VRTK

Assets/VRTK/Scripts/Internal/VRTK_EventSystem.cs
There's an issue where a "Screen Space - Overlay" camera doesn't
register any mouse input. The problem is that
`VRTK_EventSystem.OnEnable` returns too early and therefore never
changes the event system reference.
This is fixed by this change. Additionally the `VRTK_EventSystem` is
simplified to the needed minimum.
=> fix(EventSystem): screen space overlay desktop camera

Assets/VRTK/Scripts/Internal/VRTK_EventSystem.cs
There's an issue where a "Screen Space - Overlay" camera doesn't
register any mouse input. The problem (this time) is that
`VRTK_EventSystem.SetEventSystemOfBaseInputModulesTo` is called too
early and therefore never changes the event system reference for some of
the existing input modules.
The fix is to run `VRTK_EventSystem.SetEventSystemOfBaseInputModulesTo`
after a frame has passed by making it a coroutine.
=> fix(EventSystem): screen space overlay desktop camera (again)

Assets/VRTK/Prefabs/VRSimulatorCameraRig.prefab, Assets/VRTK/SDK/Simulator/SDK_InputSimulator.cs
* Add key bindings for WASD so movement bindings can be changed for other keyboard layouts.
* Add context sensitive control hints.
* Add an alternative scene view like mouse movement input mode where a button press is required and the mouse cursor can be locked to the game window.
=> feat(Simulator): Simulator enhancements

Assets/VRTK/Editor/VRTK_UpdatePrompt.cs
The update prompt was checking for new updates to VRTK every time Unity
was started or recompiled the project. This change makes sure to only
check every 6 hours.
=> perf(UpdatePrompt): only check for updates every 6 hours

Assets/VRTK/SDK/Simulator/SDK_InputSimulator.cs
There was a typo in the Simulator's Input Simulator which has been fixed.
=> fix(Simulator): typo

Assets/VRTK/Editor/VRTK_EditorUtilities.cs, Assets/VRTK/Scripts/Internal/VRTK_ObjectCache.cs, Assets/VRTK/Scripts/Utilities/VRTK_DeviceFinder.cs, Assets/VRTK/Scripts/Utilities/VRTK_SharedMethods.cs
All VRTK classes that only have static methods are now static classes
and no longer inherit from anything.
=> chore(Structure): ensure static classes

Assets/VRTK/SDK/Base/SDK_BaseController.cs, Assets/VRTK/SDK/Base/SDK_BaseHeadset.cs, Assets/VRTK/SDK/Daydream/SDK_DaydreamController.cs, Assets/VRTK/SDK/Daydream/SDK_DaydreamHeadset.cs, Assets/VRTK/SDK/Fallback/SDK_FallbackController.cs, Assets/VRTK/SDK/Fallback/SDK_FallbackHeadset.cs, Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs, Assets/VRTK/SDK/OculusVR/SDK_OculusVRHeadset.cs, Assets/VRTK/SDK/Simulator/SDK_SimController.cs, Assets/VRTK/SDK/Simulator/SDK_SimHeadset.cs, Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs, Assets/VRTK/SDK/SteamVR/SDK_SteamVRHeadset.cs, Assets/VRTK/SDK/VRTK_SDK_Bridge.cs, Assets/VRTK/SDK/Ximmerse/SDK_XimmerseVRController.cs, Assets/VRTK/SDK/Ximmerse/SDK_XimmerseVRHeadset.cs, Assets/VRTK/Scripts/Internal/VRTK_TrackedController.cs, Assets/VRTK/Scripts/Internal/VRTK_TrackedHeadset.cs, DOCUMENTATION.md
The controller and headset SDK can now execute items within a
FixedUpdate routine if required.
=> feat(SDK): add FixedUpdate routine for controller and headset

Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs
Add a null reference check also for actualRightController in
VRTK_SDKManager::SetupControllers().
=> fix(sdk): add null reference check

Assets/VRTK/Scripts/Pointers/VRTK_PlayAreaCursor.cs, DOCUMENTATION.md
The PlayArea Cursor can now have a custom prefab given to it to use as
the visual indicator of the play area cursor.
=> feat(Pointer): add customisable play area cursor game object

Assets/VRTK/SDK/Simulator/SDK_SimHeadset.cs
The Simulator SDK was changed to support headset fading using the Screen
Fade script.
=> fix(Simulator): support headset fading

Assets/VRTK/Scripts/Internal/VRTK_CurveGenerator.cs
The bezier pointer renderer can now utilise a line renderer by
attaching a line renderer to a game object that is provided as the
custom tracer object on the bezier pointer renderer.
If only a line renderer is provided, then only a line renderer will
be used to display the curve of the bezier pointer. If the game object
also contains a mesh the both the mesh and the line renderer is used
in the curve display.
=> feat(Pointer): allow bezier pointer to utilise line renderer

Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_TransformFollow.cs, DOCUMENTATION.md
The Transform Follow script now has the option to follow On Pre Cull.
=> feat(Utilities): add OnPreCull option for tranform follow

Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs
Previously, the Pointer script would attempt to set up the controller
for the pointer in the OnEnable and then the Start method, however
this caused issues when wanting to use the `activate on enable` setting
along with the `interact with objects` setting as the pointer was
enabled before the controller interactions were created meaning it
would not work.
This fix now ensures the pointer controller set up is done at the first
possible moment in the update routine after all enable and start
methods have been run. This will also mean that the disabling and
enabling of a pointer will still work and set up correctly.
=> fix(Pointer): defer controller setup to Update method

Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs
The Controller Tooltips would attempt to initialise the tips every
frame in an Update loop until they were correctly initialised.
This would cause an issue if the controller elements were not available
as the Initialise method would run every Update.
The fix now only initialises the tips when the controller enabled event
is thrown which is a more appropriate time to set the tooltips up.
Another fix was added that prevented the tooltips from being visible
if the `Hide when not in view` option was unticked.
=> fix(Tooltips): initialise tips when controller is enabled - fixes #1158

Assets/VRTK/Editor/VRTK_ObjectSetup.cs
Increase window height so everything fits inside.
=> fix(setupWindow): increase window height

Assets/VRTK/Scripts/Controls/3D/VRTK_Button.cs, Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_Button_UnityEvents.cs
Add `Released` event to VRTK_Button.cs
Add `OnReleased` Button3DEvent to VRTK_Button_UnityEvents.cs
=> feat(Controls): add `Released` event

Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs, Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BezierPointerRenderer.cs, Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs, Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs, Assets/VRTK/Scripts/Presence/VRTK_HeadsetCollision.cs, DOCUMENTATION.md
A number of the VRTK script auto generate objects containing things
that are used within the scene.
Providing a simple method to get these objects makes them more useful
if they need to be amended or referenced at runtime.
=> feat(Structure): provide getter methods for auto gen objects

Assets/VRTK/Editor/VRTK_SupportInfoWindow.cs
The Support Info window has been updated to include info on the used
VR settings found in the player settings.
=> feat(SupportInfo): add VR settings

Assets/VRTK/Editor/VRTK_ObjectSetup.cs
Support selecting several objects at once when
using the setup window.
=> feat(setupWindow): support multi selection

Assets/VRTK/Examples/ExampleResources/Prefabs/SDKSetups.prefab, Assets/VRTK/SDK/Simulator/SDK_InputSimulator.cs
Fixed a bug with y rotation when rig was parented that was
caused by mixing of rotation and localRotation. Also add
a simple neck model to the simulator.
=> fix(Simulator): sdd simple neck model.

Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs
Fix discussed with @bddckr on Slack.
=> fix(SDKManager): SDK Setup unloading - fixes #1272

Assets/VRTK/SDK/Base/SDK_BaseController.cs, Assets/VRTK/SDK/Oculus/SDK_OculusController.cs, DOCUMENTATION.md
The GearVR HMD input and controller input are now supported.
Along with basic support for the Oculus remote.
=> feat(SDK): support GearVR input

Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs, Assets/VRTK/Scripts/Locomotion/VRTK_DashTeleport.cs
Fix for incorrect final position during dash teleport with rotation
=> fix(Locomotion): ensure correct rotation with dash teleport

Assets/VRTK/Examples/037_CameraRig_ClimbingFalling.unity, Assets/VRTK/Scripts/Locomotion/VRTK_PlayerClimb.cs, Assets/VRTK/Scripts/Locomotion/VRTK_SlingshotJump.cs, Assets/VRTK/Scripts/Locomotion/VRTK_SlingshotJump.cs.meta
Allows the player to precisely jump by pulling the trigger on
bother controllers, pulling back the desired amount, and releasing.
The system combines the vectors and directions of both controllers
to sling the player in the defined direction.
=> feat(Locomotion): jumping mechanic using controller slingshot

Assets/VRTK/Scripts/Interactions/VRTK_InteractObjectAppearance.cs
The Interact Object Appearance script was incorrectly hiding controller
visibility when both controllers would touch the object.
This was because the cached object state was only for the last object
that interacted, however an existing interacting controller could
be overridden by a new interacting controller which would then prevent
the previous controller from regaining the correct visibility state.
The fix is to ensure the object state is cached accordingly.
=> fix(Interaction): ensure controllers preserve the correct visibility

Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ConsoleViewer.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerRigidbodyActivator.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DesktopCamera.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DestinationPoint.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_FramesPerSecondViewer.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_IndependentRadialMenuController.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ObjectTooltip.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_PanelMenuController.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_PanelMenuItemController.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_PointerDirectionIndicator.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_RadialMenu.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_RadialMenuController.cs, Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs, DOCUMENTATION.md
The prefab documentation has been updated to be more consistent and
cleaner with steps on how to add the prefab to the scene.
=> docs(prefabs): update prefab documentation

Assets/VRTK/Documentation/API.md, Assets/VRTK/Examples/028_CameraRig_RoomExtender.unity, Assets/VRTK/Examples/ExampleResources/Scripts/VRTK_RoomExtender_ControllerExample.cs, Assets/VRTK/Source/Scripts/Internal/VRTK_RoomExtender_PlayAreaGizmo.cs, Assets/VRTK/Source/Scripts/Internal/VRTK_RoomExtender_PlayAreaGizmo.cs.meta, Assets/VRTK/Source/Scripts/Locomotion/VRTK_StepMultiplier.cs, Assets/VRTK/Source/Scripts/Locomotion/VRTK_StepMultiplier.cs.meta
The Step Multiplier is a modified version of the Room Extender where it
has the button mappings on the script itself and is placed on the
controller script.
This also means the Room Extended and subsequent classes have also been
deprecated.
=> feat(Locomotion): add step multiplier locomotion method

Assets/VRTK/Source/SDK/Simulator/SDK_InputSimulator.cs
This adds a hotkey to toggle the mouse cursor lock state in
both editor and builds.
=> feat(Simulator): add toggle hotkey for mouse lock

Assets/VRTK/Documentation/API.md, Assets/VRTK/Source/Scripts/Interactions/Interactables/GrabAttachMechanics/VRTK_ControlAnimationGrabAttach.cs
The Control Animation Grab Mechanic now supports legacy animations as
well as mechanim Animators.
=> feat(Interaction): support legacy animation in animation grab mechanic

Assets/VRTK/Documentation/API.md, Assets/VRTK/Source/Editor/DataTypes.meta, Assets/VRTK/Source/Editor/DataTypes/Vector3StateDrawer.cs, Assets/VRTK/Source/Editor/DataTypes/Vector3StateDrawer.cs.meta, Assets/VRTK/Source/Scripts/Internal/DataTypes.meta, Assets/VRTK/Source/Scripts/Internal/DataTypes/Vector3State.cs, Assets/VRTK/Source/Scripts/Internal/DataTypes/Vector3State.cs.meta, Assets/VRTK/Source/Scripts/Locomotion/VRTK_DragWorld.cs, Assets/VRTK/Source/Scripts/Locomotion/VRTK_DragWorld.cs.meta
The Drag World script mimics the movement mechanic popularised in
Sports Bar VR (Hulk Mode) or in Tilt Brush and Google Blocks, where the
PlayArea can be moved, rotated and scaled based on dragging and
grabbing the world with the controllers and moving them in a certain
way to determine the appropriate mechanism to be performed.
A new custom data type has been created that allows the state of a
Vector3 to contain boolean information, this is used in this case for
knowing which axis on the Vector3 to lock, but could also be used
for other boolean information relating to a Vector3.
=> feat(Locomotion): ability to move, rotate, scale play area by dragging

Assets/VRTK/Documentation/API.md, Assets/VRTK/Source/Scripts/Interactions/Interactors/VRTK_ObjectAutoGrab.cs, Assets/VRTK/Source/Scripts/Utilities/VRTK_DeviceFinder.cs
The Object Auto Grab script has been updated to also attempt to
secondary grab the object if required.
=> feat(Interactions): option to automatically secondary grab object - fixes #1608

Assets/VRTK/Source/Scripts/Locomotion/VRTK_DragWorld.cs
Changed vector math to allow for continuous rotation.
=> fix(Locomotion): continuous rotation in DragWorld

Assets/VRTK/Examples/ExampleResources/SharedResources/Scripts/VRTKExample_AdditiveSceneLoader.cs
Previously, the constructor scene was removed from being injected into
the example scenes as it wasn't working in a build, instead the
constructor scene was required to be the last scene in the build
settings and was loaded in by index.
This only worked if using the project settings from the VRTK repo but
would not work if VRTK was imported into another project.
To remedy this, the scene injection is now being used again and the
last scene index is being used as a fallback. If no scene is in the
build settings then the script will attempt to add it as the last
scene automatically.
=> fix(Examples): ensure constructor scene is available in build settings

Assets/VRTK/Prefabs/SnapDropZone/VRTK_SnapDropZone.cs
Null check added to suppress NRE
fixes: #1771
=> fix(SnapDropZone): Empty Higherlighter Null Check

Assets/VRTK/Source/Scripts/Utilities/VRTK_SDKTransformModify.cs
Removed the reliance on the model being active
fixes: #1790
=> fix(TransformModify): SteamVR Dashboard reset

Assets/VRTK/Prefabs/SnapDropZone/VRTK_SnapDropZone.cs, Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractableObject.cs
Cloning/Duplicating SDZ possible through SDZ.Clone();
fixes: #1695
=> feat(SnapDropZone): cloning snap drop zones

README.md
The v4 beta text has been added to the title in the Readme just to
make it clear that the new branch is the v4 beta.
=> docs(README.md): add v4 beta text to readme for clarity

Prefabs/Interactions/InteractableSnapZone/SharedResources/Scripts/ActivationValidator.cs
It was possible for an Interactable collision list to be populated with
a SnapZone due to the way the SnapZone forcibly populates the
Interactable Collision list when checking if it can activate. On most
occasions this is handled by the collision exit code, however on rare
occasion it may forego this operation and mean the Interactable thinks
it is still colliding with a SnapZone that it no longer is. This fix
checks to see if the collision is valid and if it's not then it
forcibly removes it to ensure the state is correct.
=> fix(Interactions): remove invalid SnapZone collisions from interactable

Prefabs/Locomotion/Movement/SpatialManipulation.meta, Prefabs/Locomotion/Movement/SpatialManipulation/Drag.Rotate.Scale.PlayArea.prefab, Prefabs/Locomotion/Movement/SpatialManipulation/Drag.Rotate.Scale.PlayArea.prefab.meta, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources.meta, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources/Scripts.meta, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources/Scripts/PositionManipulator.cs, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources/Scripts/PositionManipulator.cs.meta, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources/Scripts/RotationManipulator.cs, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources/Scripts/RotationManipulator.cs.meta, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources/Scripts/ScaleManipulator.cs, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources/Scripts/ScaleManipulator.cs.meta, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources/Scripts/SpatialManipulator.cs, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources/Scripts/SpatialManipulator.cs.meta, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources/Scripts/SpatialManipulatorFacade.cs, Prefabs/Locomotion/Movement/SpatialManipulation/SharedResources/Scripts/SpatialManipulatorFacade.cs.meta, Samples/Farm/Prefabs/OptionsMenu/OptionsMenu.prefab, Samples/Farm/Scenes/ExampleScene.unity
The "Hulk Mode" locomotion where the playarea can be dragged through
the world with the controllers and rotated/scaled has been added
as a simple prefab that combines 3 smaller components that can be
used independently for further customisation if required.
=> feat(Locomotion): ability to drag, rotate and scale playarea

Assets/Samples/Farm/Scenes/ExampleScene.unity
A disclaimer has been added to the farm example scene explaining the
scene is a showcase of how VRTK v4 can be used and not necessarily
best practice of how things should be achieved. This disclaimer is
displayed in the Game view via a screen space UI so it will not be
visible in VR and it also disappears after a short amount of time.
=> feat(examples): add farm example scene disclaimer

README.md
The bowling tutorial link has been added to help people
get started with the Tilia repos.
=> feat(README.md): add link to Tilia bowling tutorial
