- Assets/SteamVR_Unity_Toolkit/Scripts/SteamVR_HeightAdjustTeleport.cs
It is now possible to move up and down mesh colliders by walking in
the play area and the mesh below will affect the Y of the play area.
It has an adverse effect of not doing the blink on fast movements
such as falling from a mesh because it's not an actual teleport but
a walk within game space.
> feat(Movement): add ability to change play area Y on mesh colliders

- Assets/SteamVR_Unity_Toolkit/Scripts/SteamVR_InteractGrab.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/SteamVR_InteractTouch.cs
- README.md
There is now an option on the `InteractGrab` script that enables a
rigidbody on the controller object if the grab button is pressed when
the controller is not touching any Interactable Objects. This means
that the controller can be used to interact with other rigidbodies
to push them around or press them (e.g. a button).
> feat(Interaction): add rigidbody to controller option

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
- README.md
The new `Handle Snap` grab mechanic allows you to specify a transform as
a child of the VRTK_InteractableObject to which the grab will snap. Any
rotation applied to the handle will rotate the object around the handle.
> feat(Interaction): add handle snap grab mechanic

- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/VRTK_ControllerEvents_ListenerExample.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerEvents.cs
ControllerClickedEventArgs now contains touchpadAngle which is the
angle in degrees of the touch on the touchpad around it's center,
with 0 being up, 90 being right, 180 being down and 270 being left.
> feat(Controller): add angle of touch on touchpad

- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/DeviceFinder.cs
Here's that commit for the compile warning separated out as requested.
> fix(DeviceFinder): fix for compile waring in Unity 5.4+

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
The Interactable Object's previous parent and kinematic state is now
saved when the object is grabbed and reset back to it's original state
when it is no longed grabbed. Supports swapping hands without needing
to drop the item first.
> fix(Interaction): save previous object state on grab

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerEvents.cs
Solves an issue where `TouchpadAxisChanged` occurred before `TouchpadTouchStart` and `TriggerAxisChanged` occurred before `TriggerPressed`. Now, these can only occur in the following frame if the value continues to change, so now you can be assured that a 'Start' event will occur before a 'Changed' event for initialization purposes. (I needed this to get the first change delta and start tracking changes at the right moment.)
This also keeps the 'Changed' events from happening on the 'End' event frame, which would often cause a value jump. (At least they would with my tests on `TouchpadAxisChanged`.)
> fix(ControllerEvents): fix order of controller events

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
Since `InteractGrab` and `InteractTouch` don't work unless certain
components are a part of the controller, the `RequireComponent`
attributes will make sure those components are there or automatically
add them. They also keep required components from being removed in
the Unity editor.
> feat(Interaction): add RequireComponents to grab and touch

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
If no rigid body is found when `InteractableObject` starts up, it will
add one, but make sure the rigid body is set to 'kinematic' so it
doesn't start unexpectedly rolling around, popping up, or falling.
> feat(InteractableObject): add a rigid body if missing

- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/Archery/BowAim.cs
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/Sword.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerActions.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractUse.cs
Changes the TriggerHapticPulse method to call a coroutine rather than
performing the haptic feedback event in the update method. This allows
feedback events specified in time intervals, rather than number of
frames. There are now two TriggerHapticPulse methods.
TriggerHapticPulse(ushort strength) does not call a coroutine, and
simply triggers a single pulse of specified strength.
TriggerHapticPulse(ushort strength, float duration, float pulseInterval)
allows specification of strength, total pulse duration, and the interval
that the controller should pulse at for that duration.
> feat(Interaction): add haptic feedback coroutine

- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/Breakable_Cube.cs
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/Sword.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerEvents.cs
The Controller Events now has a method for getting the current velocity
and angular velocity of the controller.
The sword example has been updated to utilise this new velocity to
determine how fast the sword is being swung to determine the collision
force.
> feat(Controller): add ability to get controller velocity

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
Using the Precision Snap grab mode with a Spring Joint was producing unintuitive effects, as the Spring Joint was always anchored at the grabbed object's center point. This will set the anchor point for a temporary Spring Joint when Precision Snap is in use.
> Fix(interaction) precise spring anchor

- Assets/SteamVR_Unity_Toolkit/Examples/028_CameraRig_RoomExtender.unity
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/VRTK_RoomExtender_ControllerExample.cs
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/VRTK_RoomExtender_ControllerExample.cs.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_RoomExtender_PlayAreaGizmo.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_RoomExtender_PlayAreaGizmo.cs.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_RoomExtender.cs
- README.md
I have added the ability to toggle the script, control it
with the controllers and extended the example scene
to showcase the new usage.
See VRTK_RoomExtender_ControllerExample.cs
I also added a Gizmo to show the extended playArea,
see example (028)
See #189 for more information.
> feat(RoomExtender): adds toggle, gizmo and controller example #189

- Assets/SteamVR_Unity_Toolkit/Examples/025_Controls_Overview.unity
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/VRTK_Slider.cs
So far one could only select to auto-detect axis and min/max together.
If axis detection does not work one could set it manually but then
would also have to define the bounds for min and max. Now it is
possible to specify the axis manually but let the min/max be
auto-detected.
In addition the auto-detection can now also detect setups where the
slider is not necessarily inside a frame but instead on an object.
> feat(Interaction): add additional slider auto-detect modes

- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/DeviceFinder.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractUse.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
- README.md
It is now possible to limit the interaction on an object to a specific
controller. The new parameters available on the Interactable Object:
* Allowed Touch Controllers
* Allowed Grab Controllers
* Allowed Use Controllers
Each option can be selected as:
* Both
* Left_Only
* Right_Only
If the option isn't `Both` then only the selected controller will
perform the relevant interaction.
> feat(Interaction): add option to prevent certain controller interaction

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
- README.md
It is now possible set the `Is Swappable` parameter on an Interactable
Object and if it is set to false then the object cannot be swapped
between hands and must be dropped before the other controller can
grab it.
> feat(Interaction): prevent object swapping between controllers

- Assets/SteamVR_Unity_Toolkit/Examples/029_Controller_Tooltips.unity
- Assets/SteamVR_Unity_Toolkit/Examples/029_Controller_Tooltips.unity.meta
- Assets/SteamVR_Unity_Toolkit/Prefabs/ControllerTooltips.prefab
- Assets/SteamVR_Unity_Toolkit/Prefabs/ControllerTooltips.prefab.meta
- Assets/SteamVR_Unity_Toolkit/Prefabs/ObjectTooltip.prefab
- Assets/SteamVR_Unity_Toolkit/Prefabs/ObjectTooltip.prefab.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/Shaders/UIOverlay.shader
- Assets/SteamVR_Unity_Toolkit/Scripts/Shaders/UIOverlay.shader.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerTooltips.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerTooltips.cs.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ObjectTooltip.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ObjectTooltip.cs.meta
- README.md
Two new prefabs have been added `ObjectTooltip` and
`ControllerTooltips` that provide UI driven tooltips on to game objects
or onto the controllers to provide easy visual descriptions of what
objects are for or for what controller buttons do.
A custom UI shader has been added to deal with the text so the back
face culls preventing reversed text when looking from behind.
> feat(Tooltips): add UI object tooltips and on controllers

- Assets/SteamVR_Unity_Toolkit/Examples/031_CameraRig_HeadsetGazePointer.unity
- Assets/SteamVR_Unity_Toolkit/Examples/031_CameraRig_HeadsetGazePointer.unity.meta
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/Remote_Beam.cs
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/Remote_Beam.cs.meta
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/Remote_Beam_Controller.cs
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/Remote_Beam_Controller.cs.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BasicTeleport.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BezierPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_SimplePointer.cs
- README.md
The World Pointer scripts can now be placed on any object instead of
just a controller. This enables things like gaze pointers (projecting
a beam from the headset) and works by linking the controller to
the script so there is a way of initiating the destination set event.
The controller linking is done via a new parameter called `controller`
that will auto populate if the script is added to an existing
controller object, but will need populating with a controller object
if the script is attached to another object.
The parameter `beamAlwaysOn` has been replaced with `pointerVisibility`
as this now has three states of:
* `On_When_Active` only render the pointer beam when the controller
button is pressed.
* `Always_On` always render the pointer beam
* `Always_Off` never render the pointer …
> feat(Pointer): allow pointers to be placed on any object

- Assets/SteamVR_Unity_Toolkit/Examples/005_Controller_BasicObjectGrabbing.unity
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
Previously, if an object was touched then it would create a touch lock
on that object even if another object was touched (whilst still
touching the original object). This fix means that whatever the latest
object touched is will get the touch focus.
> fix(Interaction): fix issue with overlapping colliders on touch

- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BasicTeleport.cs
The pointer script would still throw the relevant events even if the
script component had been disabled at run time because the events had
already been set up. The fix is to check if the script is enabled and
only emit the events if it is.
The Basic Teleport has also been updated to find all Destination
Markers on an object and not just the first one so it's possible to
include multiple pointers on the same object and toggle them at
runtime.
> fix(Pointer): prevent pointer events when script is disabled

- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BezierPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_SimplePointer.cs
The pointers create game objects and register listeners and now when
a pointer script is destroyed it cleans up these created artifacts
by removing them.
> fix(Pointer): clean up pointer artifacts on destroy

- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/Utilities.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_PlayerObject.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_PlayerObject.cs.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BasicTeleport.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BezierPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_HeadsetCollisionFade.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_PlayerPresence.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_SimplePointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_TouchpadWalking.cs
Previously, player objects were identified by the name of the game
object. This was done by certain scripts would rename the game object
and add the string `PlayerObject` which would then be looked up by
other scripts.
This was not an ideal solution as it meant renaming game objects which
could create confusion and mess in the editor at runtime. It's cleaner
and more extensible to add a custom script to these objects and they
are identified by the existence of the script.
The `VRTK_PlayerObject` script also allows to hint at what type of
object it is from the following types:
* CameraRig
* Headset
* Controller
* Pointer
> refactor(identification): determine player objects with script

- Assets/SteamVR_Unity_Toolkit/Examples/034_Controls_InteractingWithUnityUI.unity
- Assets/SteamVR_Unity_Toolkit/Examples/034_Controls_InteractingWithUnityUI.unity.meta
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/UI_Interactions.cs
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/UI_Interactions.cs.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_EventSystemVRInput.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_EventSystemVRInput.cs.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_UIGraphicRaycaster.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_UIGraphicRaycaster.cs.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/Shaders/Unlit_TransparentColor.shader
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BasicTeleport.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_UIPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_UIPointer.cs.meta
- README.md
Unity provides a collection of UI elements that are traditionally for
use with a mouse or a touch screen. It is now possible to use these
elements within VR utilising the new `VRTK_UIPointer` script that can
be attached to any object such as the controllers or headset and it
casts a ray out to the UI elements for interaction.
The `Pointer` alias button on the associated controller determines if
the ray is being cast or not. The `Use` alias button on the
associated controller determines if the UI element has been clicked.
It works well in conjucntion with the Simple Pointer to provide visual
feedback to where the ray is hitting.
The UIPointer works by replacing the `Standalone Input Module` on the
`EventSystem` with a custom Input Module. It also finds all canvases
that are set to `World …
> feat(UI): add ability to interact with unity ui

- Assets/SteamVR_Unity_Toolkit/Materials.meta
- Assets/SteamVR_Unity_Toolkit/Materials/Resources.meta
- Assets/SteamVR_Unity_Toolkit/Materials/Resources/TooltipLine.mat
- Assets/SteamVR_Unity_Toolkit/Materials/Resources/TooltipLine.mat.meta
- Assets/SteamVR_Unity_Toolkit/Materials/Resources/UIText.mat
- Assets/SteamVR_Unity_Toolkit/Materials/Resources/UIText.mat.meta
- Assets/SteamVR_Unity_Toolkit/Materials/Resources/WorldPointer.mat
- Assets/SteamVR_Unity_Toolkit/Materials/Resources/WorldPointer.mat.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ObjectTooltip.cs
- ProjectSettings/GraphicsSettings.asset
- README.md
The World Pointer material can now be set as a parameter on any
pointer via the `Pointer Material` option in the inspector. If no
material is provided then a default material is loaded from the new
`Materials` directory.
This new `Materials` directory also provides the ability to load
required materials at runtime rather than trying to create them via
code using non-standard shaders. The approach of `Shader.Find` causes
build issues if the shader is not included in the
`Project Settings->Graphics->Shaders` option, but if there is a
material in the project that is using that shader then the build
process will automatically include the shader so there is no need to
manually update the settings.
> feat(Pointer): add option for custom pointer material

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
The touch rumble can get stuck in a loop if objects are touched in
quick succession. It's better to only allow for one rumble at a time
and let that rumble finish before triggering another rumble otherwise
the controller could be overloaded with rumble requests.
> fix(Interaction): prevent continuous rumble on touch

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
If an interactable object is touched and grabbed by one controller
but then another controller touches the object whilst it's grabbed
and then the object is disabled, the touch is not reset on the
original controller because it's not considered the touching obejct.
This fix ensures that the grabbing object and using object also
force the touch to be reset as well.
> fix(Interaction): ensure touch state is reset on disable

- Assets/SteamVR_Unity_Toolkit/Examples/025_Controls_Overview.unity
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Drawer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Drawer.cs.meta
- README.md
This will transform game objects into drawers for use e.g. inside
cabinets. Most things are auto-detected like the direction and the
extent it can be pulled out.
The value range will be 0 (closed) to 100 (fully open). Optionally
interactable objects inside the drawer can become managed so that they
are not grabbable when the drawer is closed.
> feat(Interaction): add drawer control

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BasicTeleport.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_HeightAdjustTeleport.cs
There are occasions when the pointer tip position would report being
above the target teleport location, or other times where the target
location wasn't being considered valid so the `[CameraRig]` y position
wasn't being updated leaving the player hanging in mid air.
This is because the logic to determine the destination y relied on
the target object having a defined center and height, which could
produce flakey results.
This has now been replaced and a ray is cast from the pointer tip
(with a slight height offset to ensure it avoids clipping with the
target surface). The ray is cast downwards and looks for the top of
the object the user should be standing on. This produces more
consistent results for both the bezier pointer and simple pointer
across many different surface types.
The …
> fix(Teleport): ensure teleporting sets y position correctly

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
Previously, if a tracked object was being grabbed and the player
teleported, the tracked object would not have it's position updated
after the teleport event, meaning the tracked object would whizz to
the player's current location and detach from their hand.
This fix, listens out for any teleport events and updates the
tracked object's position based on the controller that is holding it.
> fix(Interaction): ensure tracked object stays grabbed on teleport

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_SimplePointer.cs
- README.md
It's now possible to provide a custom pointer cursor game obejct for
the Simple Pointer. This gameobject will be used for the pointer tip
rather than the default sphere. If no game object is provided then the
default sphere is still used.
> feat(Pointer): add custom cursor option for the simple pointer

- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BezierPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerEvents.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_SimplePointer.cs
- README.md
It is now possible to have separate buttons for activating/deactivating
the pointer beam and setting the pointer destination marker.
This is useful if a pointer beam is required but teleport is wanted on
a different button press.
> feat(Pointer): add seperate button for destination set

- Assets/SteamVR_Unity_Toolkit/Examples/021_Controller_GrabbingObjectsWithJoints.unity
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
- README.md
The `Rotator_Track` grab attach mechanic allows the Interactable Object
to rotate around a joint (usually hinge) to simulate grabbing and
spinning an item (such as a wheel on an axel).
This is heavily influenced by how NewtonVR handle rotation items.
> feat(Interaction): add rotator track grab attach mechanic

- Assets/SteamVR_Unity_Toolkit/Examples/034_Controls_InteractingWithUnityUI.unity
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/UI_Keyboard.cs
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/UI_Keyboard.cs.meta
A keyboard built out of UI elements has been added to the example
scene `034_Controls_InteractingWithUnityUI` to demonstrate the UI
interactions and to provide a useful prefab for text entry.
> feat(Interaction): add ui keyboard to example scene

- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
Previously, the activation delay on a pointer would happen when the
pointer was disabled, but this gave the impression that the pointer
was not working because it was being delayed.
It's better that if no destination is set then the pointer can work
again immediately, but after a destination set has occured then the
pointer activation should be delayed.
> fix(Pointer): ensure activate delay only happens on destination set

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
The touched object collider may be a child of the object that is in
fact the interactable object so the collider's ancestors also need
checking for the presence of an interactable object.
> fix(Interaction): ensure touched objects check ancestors in triggers

- Assets/SteamVR_Unity_Toolkit/Examples/025_Controls_Overview.unity
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
So far disabling an interactable_object at runtime did not have any
effect as it could still be touched and grabed. This patch checks the
enablement state explicitly.
A fix in the sample scene was needed to remove a boxcollider which
made it nearly impossible to showcase the feature that disables the
drawer contents.
> fix(Interaction): react to enablement state of interactable_object

- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/ButtonReactor.cs
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/ControlReactor.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Button.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/VRTK_Control.cs
Controls now expose UnityEvents which are neatly exposing their own
inspector UI so that it becomes very easy to wire controls together
through configuration instead of using code. Programmatic access is
still possible.
The events are wrapped in event container classed to fold them per
default in the inspector.
> feat (Interaction): make 3D controls expose UnityEvents

- Assets/SteamVR_Unity_Toolkit/Examples/025_Controls_Overview.unity
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Chest.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Door.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Door.cs.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Drawer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Slider.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/VRTK_Control.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/Utilities.cs
- ProjectSettings/DynamicsManager.asset
- README.md
This change adds the door control. A door consists of a door, handles
and an optional frame. Auto-detection works very reliably. Advanced
gizmos are included. Multiple options can be set already. More to come
in the near future.
While testing the door this use-case became apparent so 3D controls now
also support enablement and disablement at start and at run-time.
Utilities contain a much better bounds calculation now and a new
convenience method for collider creation.
> feat(Interaction): add door 3D control

- .editorconfig
- SteamVR_Unity_Toolkit.sln.DotSettings
These two files help me keep my code formatting straight between different projects and their varying style requirements. I thought perhaps they might help other collaborators keep to this projects specific styles too.
1. **`.editorconfig`** - Allows Visual Studio to change its tabs, spaces, and indent settings from project to project when used with the [EditorConfig plugin](https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328). See [EditorConfig.org](http://editorconfig.org/) for more info.
2. **`SteamVR_Unity_Toolkit.sln.DotSettings`** - Saves [per-project settings](https://www.jetbrains.com/help/resharper/2016.1/Sharing_Configuration_Options.html) for [ReSharper](https://www.jetbrains.com/resharper/) so they can be shared with all collaborators.
> chore(Configs): add editor configs for VS and ReSharper

- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
If pointerActivatesUseAction is true in VRTK_InteractableObject, after
pointing at the object with the pointer, the object continues to be used
also when the pointer is switched off.
Add a check in VRTK_WordPointer.TogglePointer() to switch off the
object usage if the pointer is switched off (add also a reference to the
object as private class member to keep track of the pointed object).
> fix(Pointer): switch off usage on pointer off

- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/2D/RadialMenu/RadialMenu.cs
- DOCUMENTATION.md
This allows events to be triggered when the button enters/exits the hovered state.
An example use case is showing/hiding of an attached laser pointer component depending on which button is being hovered over.
> feat(RadialMenu): add OnHoverEnter / OnHoverExit events to RadialMenu buttons

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_Simulator.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_Simulator.cs.meta
- DOCUMENTATION.md
For many trivial tests one still has to put on the headset in order to
move to the right spot. This increases turn-around times. This script
can be put onto the camera rig and will then allow movement through
the scene using keys. Once at the desired location the controllers can
be used to interact while looking at the monitor.
Supported so far are move, strafe, rotate and up/down. Being an early
version this is only tested in one context so far and especially after
rotating the move directions are inverted currently. These are all
things to look at in future versions. Help always welcome.
> feat(Testing): add movement simulator resolves #262

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractUse.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
- DOCUMENTATION.md
Previously, when using an object and swapping controllers (either
grab or touch state) the use state on the object would not be reset
correctly and therefore the previous using controller would still
be considered the active use controller.
This fix ensures that when a controller stops touching or grabbing
an object, that the use state on the controller is also reset to
no longer using the object.
> fix(Interaction): prevent controller swap breaking use functionality - resolves #343

- Assets/SteamVR_Unity_Toolkit/Examples/030_Controls_RadialTouchpadMenu.unity
- Assets/SteamVR_Unity_Toolkit/Prefabs/RadialMenu.prefab
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/2D/RadialMenu/RadialMenu.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/2D/RadialMenu/VRTK_IndependentRadialMenuController.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/2D/RadialMenu/VRTK_IndependentRadialMenuController.cs.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/2D/RadialMenuController.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/Utilities.cs
- DOCUMENTATION.md
Pretty much summarized in commit b483d782c8717c1b9db3c4cdb81cf7440d236b30. Lets the RadialMenu be used on objects separate from the controllers, with all expected features (facing the player, using controller position instead of touchpad axis, etc.).
> feat(RadialMenu): allow anchoring to interactable GameObjects

- Assets/SteamVR_Unity_Toolkit/Examples/036_Controller_CustomCompoundPointer.unity
- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractUse.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
- DOCUMENTATION.md
Add to Interactable Object a "Hide on touch/grab/use" option which
overrides the controller option (see issue #79 and #346).
Add to Interactable Object a "Use Only If Grabbed" option which can
prevent an object to be used if not grabbed (see issue #346).
Set "Hide Controller On Use" to "Override Hide" and checked
"Use Only If Grabbed" in the object "Usable Grabbable Sphere"
(script "Use Rotate") in the example scene
036_Controller_CustomCompoundPointer. The sphere can be used only if
grabbed and when it is used the grabbing controller disappears.
> feat(Interaction): override controller hide + use only if grabbed

- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerEvents.cs
There is an issue that controller events such as button presses can
become stuck in the on state if the controller is disabled whilst a
button is being held down. For example, bringing up the SteamVR
keyboard overlay will disable the Unity controller models but then
when the overlay is closed the initial state of the controller's
pressed buttons is not updated so buttons are reported as being
pressed even though they are no longer being pressed.
This fix is to ensure that upon the controller being disabled that
all buttons that are active will have their released state emitted.
This will put them back in a fresh state when the controller is
re-enabled. However, if a button is being held down it will need
to be released and re-held down again for the event to register.
> fix(ControllerEvents): ensure all events are released when disabled

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
Previously, the touch highlighting would only change the first material
on the Interactable Object. This fix ensures that all the materials on
an object get updated by the hightlight colour.
> fix(Interaction): allow touch highlight to affect all object materials resolves #310

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
Minor fix for tracked objects, the grab state was not being reset when
"Hold Button To Grab" was disabled after dropping an item. When grabbing it for a second time you have to hold the button despite it being disabled. Moving the state
reset into InitUngrabbedObject() fixes the issue as it is called no
matter which path is used to drop an item.
> fix(Interaction): ensure grab state is reset for tracked objects

- Assets/SteamVR_Unity_Toolkit/Examples/034_Controls_InteractingWithUnityUI.unity
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/UI_Interactions.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_EventSystemVRInput.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_UIPointer.cs
- DOCUMENTATION.md
A new inspector parameter has been added that provides the ability
to ignore certain world canvases that match a given tag or contain
a specific named class.
The `Ignore Canvas With Tag Or Class` parameter accepts a string and
any canvas that is tagged with the same string or contains a script
that is named the same as the string will not be interactable with
the UI Pointers.
The UI example scene has been updated to demonstrate this exclusion.
> feat(UI): add ability to ignore certain world canvases - resolves #309

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_UIPointer.cs
Previously, the UIPointer would attempt to assign the pointer id
based on the provision that a Tracked Object script was present on
the same component as the UIPointer script. This meant it could
only be applied to the controllers or the headset by default.
The pointer id is now determined by the index of the controller
passed to the UI Pointer and therefore the UI pointer can be
attached to any game object that can also emit a world pointer.
> fix(UIPointer): get pointer id from specified controller

- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
- DOCUMENTATION.md
With the new `Hold Button To Activate` inspector parameter, it's
possible to activate the pointer beam with one press of the pointer
alias and the pointer then stays active until the pointer alias button
is pressed again.
> feat(Pointer): allow for pointer toggle with button presses resolves #213

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
Previously, tracked objects did not pause collisions on grab due
to the code that calls the pause being inaccessible. This code has
now been moved so it is accessible for all grab mechanics.
> fix(Interaction): allow pause collisions on tracked objects

- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/VRTK_ControllerInteract_ListenerExample.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Helper/VRTK_EventSystemVRInput.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BasicTeleport.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BezierPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerActions.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_HeadsetCollisionFade.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_HeightAdjustTeleport.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractUse.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_PlayerClimb.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_PlayerPresence.cs
The event listeners are now managed in `OnEnable` and they are removed
in `OnDisable` to ensure they are no longer registered when the object
is no longer active.
> chore(events): ensure events are managed on enable and disable - resolves #350

- Assets/SteamVR_Unity_Toolkit/Examples/033_CameraRig_TeleportingInNavMesh.unity
- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_DestinationMarker.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BasicTeleport.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BezierPointer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_HeightAdjustTeleport.cs
- DOCUMENTATION.md
Previously, the nav mesh check would use the origin position of the
target to see if it was within the nav mesh boundaries. This would
cause false positives to be reported. The solution is to check the
actual destination position vector.
> fix(Teleport): ensure nav mesh check uses destination position - resolves #277

- Assets/SteamVR_Unity_Toolkit/Examples/025_Controls_Overview.unity
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Animations/ButtonAnimation.anim
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Animations/ButtonAnimation.anim.meta
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Animations/ButtonAnimation2.anim
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Animations/ButtonAnimation2.anim.meta
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Animations/ButtonWall 1.controller
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Animations/ButtonWall 1.controller.meta
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Animations/ButtonWall.controller
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Animations/ButtonWall.controller.meta
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Animations/MovingPanel2.controller
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Animations/MovingPanel2.controller.meta
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/ControlReactor.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Button.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Chest.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Control.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Door.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Drawer.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Knob.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Lever.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Slider.cs
- DOCUMENTATION.md
This patch is the result of adapting the controls further to a real game
scene.
The lever has been reworked, coding aligned with the other controls and
the detection is improved.
Auto-detection of door anchor points has been greatly improved by a new
calculation method. The nested door in 025 does not need the manual
hingejoint anymore.
All controls now support returning normalized values that range between
0-100%.
In progress but stuck due to one last Unity issue: Buttons now support
being moved at run-time (gizmos and activation point already fixed,
only configurable joint left which does not seem updatable at run-time).
To try out the issue simply activate the animation on "ButtonWall".
Scene 025 has been cleaned up a bit and the texts now also show the
normalized value.
> feat(Interaction): service pack for 3D controls

- Assets/SteamVR_Unity_Toolkit/Examples/027_CameraRig_TeleportByModelVillage.unity
- Assets/SteamVR_Unity_Toolkit/Examples/032_Controller_CustomControllerModel.unity
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/Archery/ArrowSpawner.cs
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/Controller_Hand.cs
- Assets/SteamVR_Unity_Toolkit/Examples/Resources/Scripts/ModelVillage_TeleportLocation.cs
- Assets/SteamVR_Unity_Toolkit/Prefabs/Resources.meta
- Assets/SteamVR_Unity_Toolkit/Prefabs/Resources/ControllerColliders.meta
- Assets/SteamVR_Unity_Toolkit/Prefabs/Resources/ControllerColliders/HTCVive.prefab
- Assets/SteamVR_Unity_Toolkit/Prefabs/Resources/ControllerColliders/HTCVive.prefab.meta
- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/2D/RadialMenu/VRTK_IndependentRadialMenuController.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
- DOCUMENTATION.md
It is now possible to provide a custom collection of colliders as a
child object to the Controller. Which means the touch collider is
no longer a simple sphere but can be a complex collection of colliders
to provide a higher level of fidelity.
The `Custom Rigidbody Object` on the Interact Touch script can take
a custom game object that deals with the collider collection for touch
collisions but will also form the collection of colliders for when
the controller rigidbody is not kinematic. If no custom rigidbody is
provided then the default `HTCVive` collider collection will be used.
The example scene `032_Controller_CustomControllerModel` has been
updated to demonstrate how a custom controller can be set up with this
new method.
> feat(Interaction): add custom controller colliders for touch - resolves #334

- Assets/SteamVR_Unity_Toolkit/Examples/037_CameraRig_ClimbingFalling.unity
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_PlayerClimb.cs
- DOCUMENTATION.md
Fix for rope section of climbing example.
Adds a new option for an additional offset when teleporting out of
walls (safeZoneTeleportOffset).
Fix for climbing wall collision sometimes not working.
Updated documentation.
> feat(Climbing): add new headset safe zone offset

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
When no constraints are set on the controller rigidbody it will start
to move a and spin coming out of sync with the model and causing
erratic behaviour.
> fix(Interaction): make controller rigidbody unmovable

- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Door.cs
Fixes a small bug with handleless doors that were referencing the wrong
object.
> fix(Interaction): correct wrong door references

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ObjectAutoGrab.cs
AutoGrab would fail if the controllers initially already touched
something. This is now fixed.
Also stronger typing has been introduced and the script flow fixed so
that now error messages also appear in the console.
> fix(Controller): enhance AutoGrab script

- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs
- Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs
- DOCUMENTATION.md
The `Create Rigid Body When Not Touching` flag on the Interact Grab
script would only create a rigidbody on the grab event, so when an
item was being held but then dropped automatically (e.g. by banging it
into a wall and breaking the joint) but the grab button was still being
held down, the rigidbody would not activate.
This fix moves the logic into the Update routine so it constantly
checks for the state of the grab button and toggles the rigidbody
accordingly.
> fix(Controller): ensure rigidbody on not touching works on auto drop - resolves #405

- Assets/SteamVR_Unity_Toolkit/Scripts/Controls/3D/VRTK_Button.cs
Unity would show two warnings currently for the button.
> fix(Interaction): remove unused code in 3D button

- Assets/VRTK/Examples/002_Controller_Events.unity
- Assets/VRTK/Scripts/VRTK_ControllerEvents.cs
- DOCUMENTATION.md
It's now possible to specify the click threshold that the trigger axis
must exceed for a click to be registered.
The reason for this is, the trigger click should happen when the axis
has reached it's maximum level of 1f but this is achieved by a
microswitch inside the controller trigger being pressed and when it is
pressed it changes the trigger axis to 1f. However, if the controller
microswitch is broken and not registering the click then the trigger
axis is never set to 1f and therefore the trigger click event is never
emitted. This setting gives the ability to reduce the threshold to a
level where a click even can still be recognised on faulty hardware.
> feat(Controller): add trigger click threshold parameter

- Assets/VRTK/Scripts/VRTK_PlayerPresence.cs
The controller can have a rigidbody activated on it and this would then
enable the player to push themselves around because the controller
would collide with the player presence collider.
This fix ensures the controller colliders are ignored.
> fix(Presence): ensure controller colliders do not affect user collider - resolves #299

- Assets/VRTK/Examples/021_Controller_GrabbingObjectsWithJoints.unity
- Assets/VRTK/Examples/028_CameraRig_RoomExtender.unity
- Assets/VRTK/Scripts/Controls/3D/VRTK_Chest.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Door.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Drawer.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Knob.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Lever.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Slider.cs
- Assets/VRTK/Scripts/VRTK_HeightAdjustTeleport.cs
- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
- DOCUMENTATION.md
The Height Adjust Teleporter was continually changing position to the
nearest floor even if the Y position of the floor hadn't changed.
There is now a check to only teleport if the Y of the floor hasn't
changed.
> fix(Teleporter): prevent constant teleporting to nearest floor - resolves #448

- Assets/VRTK/SDK/SteamVR/VRTK_SDK_Bridge.cs
A number of object references are made using `FindObjectOfType` which
can be an expensive call so there is no point in continually doing this
every time the same object is required. Instead, the object is now
cached and the cache version is returned if it has been set.
> chore(SDK): cache common object references

- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
- Assets/VRTK/Scripts/VRTK_ObjectAutoGrab.cs
- DOCUMENTATION.md
Previously, Autograb would only happen on Start which meant that after
a controller was disabled and re-enabled the Autograb would not take
place again. This has been rectified by moving the Autograb logic into
the `OnEnable` method.
> fix(Interaction): ensure autograb always happens on enable

- Assets/VRTK/Scripts/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
- DOCUMENTATION.md
Tracked objects were not being thrown in the same way as other object
grab types like joints or child of controller meaning that they would
be thrown with a lot more force which made them feel unnatural. This
has been resolved to ensure they feel the same as other objects when
thrown.
> fix(Interaction): make tracked objects throw the same as other objects

- Assets/VRTK/Scripts/VRTK_BasicTeleport.cs
- Assets/VRTK/Scripts/VRTK_HeadsetCollision.cs
- Assets/VRTK/Scripts/VRTK_HeadsetCollision.cs.meta
- Assets/VRTK/Scripts/VRTK_HeadsetCollisionFade.cs
- Assets/VRTK/Scripts/VRTK_HeadsetFade.cs
- Assets/VRTK/Scripts/VRTK_HeadsetFade.cs.meta
- Assets/VRTK/Scripts/VRTK_PlayerClimb.cs
- Assets/VRTK/Scripts/VRTK_PlayerPresence.cs
- DOCUMENTATION.md
The Headset Collision Fade script is now just composed of two other
scripts that deal with headset collision and headset fading
independently. This decoupling of the headset collision and headset
fading actions means that more versatile solutions for headset
collision can be implemented.
The Headset Collision script deals with any collisions from the user's
headset and emits the relevant events, whilst the Headset Fade script
deals with fading and unfading the headset view and also emits relevant
events.
> feat(Headset): decouple collision and fade into separate scripts - resolves #436

- Assets/VRTK/Editor.meta
- Assets/VRTK/Editor/VRTK_InteractableObjectEditor.cs
- Assets/VRTK/Editor/VRTK_InteractableObjectEditor.cs.meta
- DOCUMENTATION.md
The Interactable Object now has a custom Unity inspector to arrange the
parameters in a more accessible way by grouping things in foldouts and
only showing certain foldouts and parameters if they are required.
> feat(Editor): add interactable object custom inspector

- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
Check detachment from grab point instead of transform so big objects don't release immediately if grabbed from a point far from the transform origin
> fix(Interaction): detachment check from grab point

- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_BasicTeleport_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_BasicTeleport_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_ControllerEvents_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_ControllerEvents_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_DestinationMarker_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_DestinationMarker_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_HeadsetCollision_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_HeadsetCollision_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_HeadsetFade_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_HeadsetFade_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractGrab_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractGrab_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractTouch_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractTouch_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractUse_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractUse_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractableObject_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_PlayerClimb_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_PlayerClimb_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_PlayerPresence_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_PlayerPresence_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_UIPointer_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_UIPointer_UnityEvents.cs.meta
- DOCUMENTATION.md
The toolkit uses C# delegates to raise events, however, Unity Events
provide a nice inspector interface (but come at a performance cost) so
Unity Event helper scripts have been added that can be used to extend
the relevant script that is using a C# delegate to provide the benefit
of Unity Events but optionally to remove the requirement of the
performance overhead.
> feat(Events): add unity events helper scripts for delegate events

- Assets/VRTK/SDK/SteamVR/VRTK_SDK_Bridge.cs
- Assets/VRTK/Scripts/Abstractions/VRTK_DestinationMarker.cs
- Assets/VRTK/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/VRTK/Scripts/Helper/VRTK_ObjectCache.cs
- Assets/VRTK/Scripts/Helper/VRTK_ObjectCache.cs.meta
- Assets/VRTK/Scripts/VRTK_BasicTeleport.cs
- Assets/VRTK/Scripts/VRTK_ControllerActions.cs
- Assets/VRTK/Scripts/VRTK_HeadsetCollision.cs
- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
Rather than use `Find` `FindChild` and `FindObjectOfType` when looking
up required objects, the system now has a new Cache static object that
has scripts register with and then other scripts can use this cache
rather than making expensive find calls.
> feat(Caching): add object cache to reduce expensive find calls - resolves #501

- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
VRTK_Interactable object grabs each material to change the color
if highlighting is used. This breaks batching support in Unity
and so it is now only set if highlighting is actually used.
> fix(Interaction): only instance materials if highlight is used

- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
Previously, the game object when highlighted would use the name of the
game object to store a reference to it's original colour. However, if
child game objects shared the same name then this would break and cause
a crash with the highlighting.
This fix ensures a unique reference to the game object is used, which
is the instance ID of the game object.
> fix(Interaction): use game object instance id as ref for highlighting - resolves #466

- Assets/VRTK/Scripts/VRTK_BasicTeleport.cs
- Assets/VRTK/Scripts/VRTK_TeleportDisableOnHeadsetCollision.cs
- Assets/VRTK/Scripts/VRTK_TeleportDisableOnHeadsetCollision.cs.meta
- DOCUMENTATION.md
The ability to disable the teleport on headset collision has now been
extracted into it's own script to decouple the feature and also to
make it optional in case it's valid for teleporting to happen on
headset collision.
> feat(Teleport): extract teleport disable on headset collision - resolves #514

- Assets/VRTK/Scripts/Helper/VRTK_UIGraphicRaycaster.cs
The `UI_CONTROL_OFFSET` const was previously removed as it was thought
it was no longer required. However, the offset does provide a mechanism
for preventing a discrepancy in hit distance that will cause a UI
element if centrally placed in the canvas to constantly hover enter and
immediately hover exit repeatidly. This causes the button flicker as
the button is constantly being hovered over and then out.
The fix is to put the `UI_CONTROL_OFFSET` back in but just set the
offset at a very low value so it stops the ui raycast at a blocking
object but will not trigger the discrepancy with the button flickering.
> fix(UIPointer): prevent central button flickering on hover - resolves #527

- Assets/VRTK/Scripts/VRTK_HeightAdjustTeleport.cs
- DOCUMENTATION.md
The `Floor Height Tolerance` parameter is used to determine how much
of a change between the current floor `y` and the previous floor `y`
has happened before considering it valid to drop to the nearest floor.
This setting can be used to prevent unnecessary teleport events when
the floor below the user is uneven but should not be considered
different enough to force the user to drop to a new location on such
a small variation change in their `y` position.
> fix(Teleport): add floor height tolerance parameter - resolves #489

- Assets/VRTK/Scripts/VRTK_PlayerPresence.cs
- Assets/VRTK/Scripts/VRTK_TouchpadWalking.cs
- DOCUMENTATION.md
The Touchpad Walking script no longer requries the Player Presence
script to work as it can get the headset transform from the
Device Finder script. This also means the `GetHeadset()` method
in the Player Presence script can be removed as it's now obsolete.
> feat(Locomotion): decouple touchpad walking from player presence - resolves #530

- Assets/VRTK/Scripts/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
If the Interactable Object is set as `isDroppable = false` then it
should not be able to drop the object by the joint breaking or
the object/controller distance being too far. It should also not
drop if the controller is disabled but it will drop if the
Interactable Object is disabled.
The way the prevent drop works on controller disable is by storing
a reference to the grabbed object then auto grabbing it again
when the controller is re-enabled.
> fix(Interaction): ensure undroppable objects cannot be dropped - resolves #535

- Assets/VRTK/Examples/017_CameraRig_TouchpadWalking.unity
- Assets/VRTK/Scripts/VRTK_PlayerPresence.cs
- DOCUMENTATION.md
The original Box Collider on the Player Presence script has now
been replaced with a Capsule Collider which is a better option as it
resolves collisions in a more natural way, for instance a small bump
in the floor or a step will stop a box collider from moving, but
because of the shape of a capsule collider, the collision resolution
will move the capsule collider up the steps which gives for a more
natural feel.
> feat(Presence): replace collider with capsule collider - resolves #523

- Assets/VRTK/Scripts/VRTK_HeightAdjustTeleport.cs
- DOCUMENTATION.md
The play space falling mechanism on the Height Adjust Teleport has
been updated now to allow for a restriction to prevent play space
falling if one/either/both of the controllers are still hovering
over the existing standing floor.
Previously, if the headset looked over a ledge and the raycast
detected a new lower floor, it would immediately teleport the
user down to the new floor. However, now with this new setting
it's possible to lean over the ledge and look down as long as
one of the controllers (or both) is still hovering over the
existing standing floor.
> feat(Teleport): add play space falling restrictions on height adjust

- Assets/VRTK/SDK/SteamVR/VRTK_SDK_Bridge.cs
- Assets/VRTK/Scripts/Helper/VRTK_ObjectCache.cs
- Assets/VRTK/Scripts/VRTK_ControllerEvents.cs
- Assets/VRTK/Scripts/VRTK_DeviceFinder.cs
- DOCUMENTATION.md
The Controller Events script will now attempt to cache the tracked
object associated with the controller and the SDK Bridge will
attempt to get a tracked object by index from the cache before
attempting to do an expensive `FindObjectOfType` call.
> perf(Controller): cache tracked objects for controllers

- Assets/VRTK/SDK/SteamVR/VRTK_SDK_Bridge.cs
- Assets/VRTK/Scripts/VRTK_ControllerActions.cs
- Assets/VRTK/Scripts/VRTK_InteractGrab.cs
The string paths to the model parts are now within the SDK Bridge
script as they will most likely differ for different SDK libraries.
> chore(Controller): decouple model paths into sdk bridge

- Assets/VRTK/Scripts/Abstractions/VRTK_DestinationMarker.cs
- Assets/VRTK/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/VRTK/Scripts/Helper/Utilities.cs
- Assets/VRTK/Scripts/Helper/VRTK_EventSystemVRInput.cs
- Assets/VRTK/Scripts/VRTK_BasicTeleport.cs
- Assets/VRTK/Scripts/VRTK_HeadsetCollision.cs
- Assets/VRTK/Scripts/VRTK_HeadsetCollisionFade.cs
- Assets/VRTK/Scripts/VRTK_TagOrScriptPolicyList.cs
- Assets/VRTK/Scripts/VRTK_TagOrScriptPolicyList.cs.meta
- Assets/VRTK/Scripts/VRTK_UIPointer.cs
- DOCUMENTATION.md
Previously, many of the classes utilised a single string to determine
whether something should be ignored by a tag or a script on the
component.
For example, the Teleport scripts could have a single tag or class name
provided to ignore any game objects containing that tag or named
component and treat it as an invalid teleport location.
This was very limiting as it only allowed for a single tag or class to
be specified and was always based on the items had to be in the ignore
list to be limited.
The new Tag Or Script Policy List script can now be added to a
component and have multiple tags or script name elements checked
against and can also have the operation set to `Ignore` to provide
the current behaviour, or be set to `Include` to only allow operations
on identifier matches.
This means …
> feat(PolicyList): add ability to have multiple tag/script ignore checks

- Assets/VRTK/Examples/Resources/Scripts/VRTK_ControllerUIPointerEvents_ListenerExample.cs
- Assets/VRTK/Scripts/VRTK_UIPointer.cs
- DOCUMENTATION.md
A new option on the UI Pointer script is now available that when
enabled will automatically attempt a click event on the last hovered
UI element before the UI Pointer was deactivated.
This provides the ability to just enable the UI Pointer and point at
an object then release the pointer to perform a click, rather than
having to press a separate button to perform the click action.
> feat(UIPointer): add option to do click when pointer is deactivated

- Assets/VRTK/Editor/VRTK_InteractableObjectEditor.cs
The Rumble parameters on the Interactable Object could potentially
switch around so strength would become duration and vice versa due
to how the editor logic was working.
This fix ensures they should always be the same way round.
> fix(Editor): prevent interactable object rumble values from switching

- Assets/VRTK/Scripts/Abstractions/VRTK_WorldPointer.cs
If the `holdButtonToActivate` variable was set to false so there
was a constant pointer beam and if the pointer toggle and pointer set
alias buttons were different then the destination set event would be
emitted at the wrong time.
It would not emit the destination set event whilst the pointer beam
was still active, but would then allow the destination set event
after the pointer beam had been turned off.
This has been resolved with some additional checking in the pointer
set logic.
> fix(Pointer): set destination correctly for constant beam - resolves #566

- Assets/VRTK/Scripts/VRTK_InteractTouch.cs
- Assets/VRTK/Scripts/VRTK_PlayerPresence.cs
The custom rigid body collider object needs to be scaled to match
the parent object's scale.
The PlayerPresence body collider now scales properly.
> fix(Colliders): ensure colliders scale properly

- Assets/VRTK/Scripts/Highlighters.meta
- Assets/VRTK/Scripts/Highlighters/VRTK_BaseHighlighter.cs
- Assets/VRTK/Scripts/Highlighters/VRTK_BaseHighlighter.cs.meta
- Assets/VRTK/Scripts/Highlighters/VRTK_MaterialColorSwapHighlighter.cs
- Assets/VRTK/Scripts/Highlighters/VRTK_MaterialColorSwapHighlighter.cs.meta
- Assets/VRTK/Scripts/VRTK_ControllerActions.cs
- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
- DOCUMENTATION.md
A new Highlighter composition concept has been added that allows a
separate component to deal with highlighting of objects.
Previously, the Interactable Object and the Controller highlighting
were done with the same logic in two different scripts and it also
meant that there was only one way to highlight these elements.
The new highlighter scripts mean the logic for highlighting is in
one script but other highlighters can be created and added to an
object to provide alternative highlighting methods.
> feat(Highlighters): add highlighter composition scripts - resolves #493

- Assets/VRTK/Scripts/Helper/CurveGenerator.cs
- Assets/VRTK/Scripts/Helper/Utilities.cs
- Assets/VRTK/Scripts/VRTK_BezierPointer.cs
- Assets/VRTK/Scripts/VRTK_InteractTouch.cs
- Assets/VRTK/Scripts/VRTK_PlayerPresence.cs
- Assets/VRTK/Scripts/VRTK_SimplePointer.cs
The `GetComponentsInChildren` method will also return any types
found on the current object as well so it's not required to do a
`GetComponents` to affect the current object and then followed by
`GetComponentsInChildren` to affect the child objects.
`GetComponentsInChildren` is enough to deal with all current object
types and all child types as well. It's inefficient to make the
call twice and update the same object in both calls.
There are still occasions where a check to see if the item exists
on the current object using `GetComponent` is valid, because it
it a cheaper call to execute and if the object contains the
component then doing the more expensive `GetComponentInChildren`
is not required to be made.
> fix(Components): simplify getting components and child components

- Assets/VRTK/Scripts/VRTK_InteractTouch.cs
- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
The Interactable Object would only track the last controller to touch
it, which caused issues when both controllers touched the object at the
same time because if one controller was removed then the Interactable
Object's touched status would be set to null even though another
controller was still touching it.
The fix is to keep a `List<>` of all objects that are touching the
Interactable Object rather than just a reference to the last object
that touched it.
> fix(Interaction): track every touching object instead of last one

- Assets/VRTK/Examples/005_Controller_BasicObjectGrabbing.unity
- Assets/VRTK/Examples/035_Controller_OpacityAndHighlighting.unity
- Assets/VRTK/Examples/Resources/Scripts/VRTK_ControllerAppearance_Example.cs
- Assets/VRTK/Materials/Resources/OutlineBasic.mat
- Assets/VRTK/Materials/Resources/OutlineBasic.mat.meta
- Assets/VRTK/Scripts/Helper/Utilities.cs
- Assets/VRTK/Scripts/Highlighters/VRTK_BaseHighlighter.cs
- Assets/VRTK/Scripts/Highlighters/VRTK_MaterialColorSwapHighlighter.cs
- Assets/VRTK/Scripts/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
- Assets/VRTK/Scripts/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs.meta
- Assets/VRTK/Scripts/Shaders/VRTK_OutlineBasic.shader
- Assets/VRTK/Scripts/Shaders/VRTK_OutlineBasic.shader.meta
- Assets/VRTK/Scripts/VRTK_ControllerActions.cs
- Assets/VRTK/Scripts/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/VRTK_InteractTouch.cs
- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
- DOCUMENTATION.md
A new highlighter has been added that puts an outline around the
object that it is applied to. It achieves this by making a copy of
the object (or a provided mesh) and puts an outline shader on the
object, which is toggled on when the highlight occurs.
The highlighters have also been updated to have an `active`
parameter on them which is used by scripted components to know which
highlighter is the one to use when found on the component (as it may
be required to put multiple highlighter components onto an object
to toggle on and off).
The Controller Actions script has also been updated to allow the
sub elements of the controller to have a custom highlighter provided
for each so it can override the main highlighter if needed.
> feat(Highlighters): add outline copy highlighter

- Assets/VRTK/Scripts/Controls/3D/VRTK_Lever.cs
The lever now uses the Rotator_Track as the Track_Object grab mechanic doesn't work as well for moving the lever.
> fix(Controls): replace lever to use rotator track - resolves #582

- Assets/VRTK/Editor/VRTK_AdaptiveQualityEditor.cs
- Assets/VRTK/Editor/VRTK_InteractableObjectEditor.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Spring_Lever.cs
- Assets/VRTK/Scripts/Helper/Utilities.cs
- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
- DOCUMENTATION.md
The custom inspector editor for the Interactable Object now displays
the tooltips from the Interactable Object script via a shared Utility
method for getting the class tooltip. The Adapative Quality Editor
now also uses this shared Utility method.
> chore(Editor): ensure tooltips display in custom inspector editor

- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_BasicTeleport_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_ControllerActions_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_ControllerEvents_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_DashTeleport_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_DestinationMarker_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_HeadsetCollision_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_HeadsetFade_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractGrab_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractTouch_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractUse_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_InteractableObject_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_PlayerClimb_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_PlayerPresence_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_UIPointer_UnityEvents.cs
All Unity Event helpers now send the sender object in the Unity Event
payload as well to match the delegate events correctly.
> feat(UnityEvents): add sender object to unity event payload

- Assets/VRTK/Editor/VRTK_AdaptiveQualityEditor.cs
- Assets/VRTK/Scripts/VRTK_AdaptiveQuality.cs
- DOCUMENTATION.md
- EXAMPLES.md
Unity 5.3 and below do not support many of the Unity.VR features
used by the Adaptive Quality script so the entire code block has been
wrapped to only allow it to execute in Unity 5.4 and above.
> fix(AdaptiveQuality): only allow for Unity 5.4 and above

- Assets/VRTK/Scripts/VRTK_Hip_Tracking.cs
- Assets/VRTK/Scripts/VRTK_Hip_Tracking.cs.meta
Adds a VRTK_Hips script that allows for head-rotation-independent body tracking for things like gun holsters. The hips will rotate with the players Y rotation, but ignore X and Z rotation which is non-trivial when the HMD is looking directly up/down.
> feat(Tracking): add head-rotation independent hips

- Assets/VRTK/Scripts/VRTK_InteractTouch.cs
Previously, there was an issue with controller interaction touches
that meant if an object had multiple child colliders, it would register
a valid touch on one of the colliders and set the interactable
object associated with that collider as the `touchedObject`. However,
when another collider in the interactable object's collider set
was touched, it would register an trigger exit on the controller
touch and execute the `StopTouching` method only for 1 frame as the
next collider would then register a valid touch again keeping the
interactable object as the touched object.
This would cause a problem as as soon as `StopTouching` was called
it would also call `StopUsing` meaning if an object was being used
and the controller was being moved in a way that could cause the
collider trigger issue …
> fix(Interaction): ensure multi-collider objects register touch properly

- Assets/VRTK/Scripts/VRTK_InteractGrab.cs
The throw velocity now takes the scale of the player into
consideration. This allows the user to dynamically scale the
player up and down without having to worry about manually
adjusting the throw multiplier to regain expected results.
> fix(InteractGrab): scaled player throw velocity matches world size

- Assets/VRTK/Examples/012_Controller_PointerWithAreaCollision.unity
- Assets/VRTK/Examples/031_CameraRig_HeadsetGazePointer.unity
- Assets/VRTK/Examples/Resources/Scripts/Setup_Scene_031.cs
- Assets/VRTK/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/VRTK/Scripts/VRTK_BezierPointer.cs
- Assets/VRTK/Scripts/VRTK_PlayAreaCursor.cs
- Assets/VRTK/Scripts/VRTK_PlayAreaCursor.cs.meta
- Assets/VRTK/Scripts/VRTK_SimplePointer.cs
- DOCUMENTATION.md
This commit brings some breaking changes to the World Pointer script.
The Play Area Cursor used to be part of the World Pointer script but
this meant the play area cursor was coupled to the pointer script and
meant that adding custon play area cursors would mean changing core
code.
A new `VRTK_PlayAreaCursor` script has now been added that can be
applied to the same game object that a World Poiinter component is
applied to. If the Play Area Cursor is applied then it works the same
way as previously, with the same options just moved into the new
script.
> feat(Pointer): separate play area cursor into own script

- Assets/VRTK/Scripts/VRTK_Simulator.cs
Fixed inconsistency in vector addition caused by adding a vector in
world space (the camera forward)to a vector in local space (the camera
rig's basis vectors).  Doing the math in the same space gives the
intended result.
> fix(Simulator): inconsistent vector addition

- Assets/VRTK/Scripts/Controls/2D/RadialMenuController.cs
SteamVR seems to sent a TouchpadAxisChanged event when the touchpad
is released. This is causing an OnOverEnter event to fire out of the
RadialMenu after the OnHoverExit event is fired. Because of this,
you'll always get an OnHoverEnter event at the end of picking your
finger up off of the touchpad.
Keep track of if the touchpad is currently being touched or not. Only
trigger the axis change if it is during an active touch.
> fix(RadialMenu): only change the axis if the touchpad is being touched

- Assets/VRTK/Scripts/Controls/3D/VRTK_Lever.cs
Lever attaches to game object so that it is moveable with connected game
object. Previously, lever is unable to attach to game object and cannot
move without breaking.
> feat(Interaction): lever attach to game object - resolves #611

- Assets/VRTK/Scripts/Highlighters/VRTK_MaterialColorSwapHighlighter.cs
Add true parameter to GetComponentsInChildren to store/restore materials
also for inactive object (in VRTK_MaterialColorSwapHighlighter).
If a script sets some inactive objects as active after highlighting an
object, when that object is unhighlighted the colors of the previously
inactive objects are not restored. This PR fixes this issue.
> fix(Interaction): scan also inactive objects in color highlighter

- Assets/VRTK/Scripts/VRTK_PlayAreaCursor.cs
- DOCUMENTATION.md
A new setting on the Play Area Cursor script has been added that
determines if the headset is outside the bounds of the defined
cursor play space and if it is outside then it treats this as a
play area collision.
This is useful if preventing teleporting if the user isn't standing
within the defined play space is required.
> feat(Pointer): check headset out of bounds on play area cursor

- Assets/VRTK/Examples/040_Controls_Panel_Menu.unity
- Assets/VRTK/Examples/040_Controls_Panel_Menu.unity.meta
- Assets/VRTK/Examples/Resources/Scripts/PanelMenu.meta
- Assets/VRTK/Examples/Resources/Scripts/PanelMenu/PanelMenuDemoFlyingSaucer.cs
- Assets/VRTK/Examples/Resources/Scripts/PanelMenu/PanelMenuDemoFlyingSaucer.cs.meta
- Assets/VRTK/Examples/Resources/Scripts/PanelMenu/PanelMenuDemoSphere.cs
- Assets/VRTK/Examples/Resources/Scripts/PanelMenu/PanelMenuDemoSphere.cs.meta
- Assets/VRTK/Examples/Resources/Scripts/PanelMenu/PanelMenuUIGrid.cs
- Assets/VRTK/Examples/Resources/Scripts/PanelMenu/PanelMenuUIGrid.cs.meta
- Assets/VRTK/Examples/Resources/Scripts/PanelMenu/PanelMenuUISlider.cs
- Assets/VRTK/Examples/Resources/Scripts/PanelMenu/PanelMenuUISlider.cs.meta
- Assets/VRTK/Prefabs/PanelMenu.prefab
- Assets/VRTK/Prefabs/PanelMenu.prefab.meta
- Assets/VRTK/Scripts/Controls/2D/PanelMenu.meta
- Assets/VRTK/Scripts/Controls/2D/PanelMenu/PanelMenuController.cs
- Assets/VRTK/Scripts/Controls/2D/PanelMenu/PanelMenuController.cs.meta
- Assets/VRTK/Scripts/Controls/2D/PanelMenu/PanelMenuItemController.cs
- Assets/VRTK/Scripts/Controls/2D/PanelMenu/PanelMenuItemController.cs.meta
Add Panel Menu control that can attach to VRTK_InteractableObject.
The control is comprised of a prefab and controller scripts. Together these enable the display of a 2D context menu panel, which is opened by pressing the assigned controller touchpad vector position (up/down/left/right). Once a panel is open the controllers pass on basic interaction events to the panel, these events can be subscribed to and used to carry out custom UI actions inside the panel.
See the demo scene for a basic working example [ 040_Controls_Panel_Menu ].
> feat(Controls): add new Panel Menu 2D control

- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
Add a check on objectHighlighter in
VRTK_InteractableObject.ToggleHighlight.
Set objectHighlighter to null after it is destroyed in OnDisable().
With a `NetworkManager` active and if a `NetworkIdentity` component is
added to the same game object holding `VRTK_InteractableObject`, then
`VRTK_InteractableObject.objectHighlighter` is destroyed before the
object is touched.
This is a workaround to ensure objectHighlighter is initialized anyway.
> fix(Interaction): objectHighlighter not initialized in ToggleHighlight

- Assets/VRTK/Scripts/Controls/3D/VRTK_Drawer.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Lever.cs
This patch adds the ability to connect a drawer to another gameobject
similar to buttons and levers.
It also fixes a bug in the lever that was recently introduced, checking
on a different gameobject for the rigidbody than the one it will be
created on.
> feat(Interaction): support moving drawers

- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_BasicTeleport_UnityEvents.cs
Changed `+=` to `-=` in `VRTK_BasicTeleport_UnityEvents.OnDisable()`.
Event handlers were added again instead of being removed #642 .
> fix(UnityEvents): resolves issue #642

- Assets/VRTK/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/VRTK/Scripts/VRTK_SimplePointer.cs
Rescale the pointer in `VRTK_SimplePointer.Update()`, when the option to
scale the pointer cursor is on (`pointerCursorRescaledAlongDistance
==true`), also without a collision of the pointer.
Fix 2 typos in VRTK_WorldPointer ("Ineractor" changed to "Interactor").
> fix(Pointer): rescale the pointer cursor also if no collision

- Assets/VRTK/Examples/029_Controller_Tooltips.unity
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_HeadsetControllerAware_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_HeadsetControllerAware_UnityEvents.cs.meta
- Assets/VRTK/Scripts/VRTK_HeadsetControllerAware.cs
- Assets/VRTK/Scripts/VRTK_HeadsetControllerAware.cs.meta
- DOCUMENTATION.md
The Headset Controller Aware script provides the ability to have the
headset aware of where the controllers are in relation to the headset.
Two key elements are provided:
* The headset can track if the controllers are being obscured from a
direct path between the headset and controller.
* The headset can know when it is looking at a controller.
If a controller is obscured from the headset then an event is emitted
as well as when the controller is no longer obscured.
Also, when the headset looks (glances) at a controller then an event
is emitted.
The Controller Tooltips prefab has been updated to only show the
controller tooltips when the controller is being looked at.
> feat(Controller): add headset controller awareness - resolves #241

- Assets/VRTK/SDK/SteamVR/SDK_SteamVR.cs
Adding mixed reality support (externalcamera.cfg in root directory) would throw an error since the SteamVR_ControllerManager assignment was grabbing the MR controller manager (mixed reality requires 2 ControllerManagers). Checking to make sure the left and right hand objects are assigned ensures the proper controller manager is selected.
> fix(Caching): get specific ControllerManager for left/right controller

- Assets/VRTK/Prefabs/ControllerRigidbodyActivator.prefab
- Assets/VRTK/Prefabs/ControllerRigidbodyActivator.prefab.meta
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerRigidbodyActivator.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerRigidbodyActivator.cs.meta
- Assets/VRTK/Scripts/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/VRTK_InteractTouch.cs
- DOCUMENTATION.md
A new Controller Rigidbody Activator prefab has been added that is an
empty game object with a sphere trigger collider and a script that
listens for the controller entering the collider and turns on the
controller rigidbody automatically instead of needing to press the
grab button on the controller to activate it.
> feat(Controller): add prefab to auto enable rigidbody on controller

- Assets/VRTK/Examples/025_Controls_Overview.unity
- Assets/VRTK/Scripts/Controls/3D/VRTK_Control.cs
Controls now provide a native option to be interactable without the
need to hold the grab button. This will automatically setup the
required trigger volume based on the bounding box of the control.
> feat(Interaction): add option to interact without grab

- Assets/VRTK/Examples/041_Controller_ObjectSnappingToDropZones.unity
- Assets/VRTK/Examples/041_Controller_ObjectSnappingToDropZones.unity.meta
- Assets/VRTK/Examples/Resources/Materials/ExampleMaterials.meta
- Assets/VRTK/Examples/Resources/Materials/ExampleMaterials/SnapDropZone_SaucerFixed.mat
- Assets/VRTK/Examples/Resources/Materials/ExampleMaterials/SnapDropZone_SaucerFixed.mat.meta
- Assets/VRTK/Examples/Resources/Materials/ExampleMaterials/SnapDropZone_SaucerHolster.mat
- Assets/VRTK/Examples/Resources/Materials/ExampleMaterials/SnapDropZone_SaucerHolster.mat.meta
- Assets/VRTK/Examples/Resources/Scripts/SnapDropZoneGroup_Switcher.cs
- Assets/VRTK/Examples/Resources/Scripts/SnapDropZoneGroup_Switcher.cs.meta
- Assets/VRTK/Materials/Resources/SnapDropZoneEditorObject.mat
- Assets/VRTK/Materials/Resources/SnapDropZoneEditorObject.mat.meta
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs.meta
- Assets/VRTK/Prefabs/SnapDropZone.prefab
- Assets/VRTK/Prefabs/SnapDropZone.prefab.meta
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_SnapDropZone_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_SnapDropZone_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Helper/Utilities.cs
- Assets/VRTK/Scripts/VRTK_InteractTouch.cs
- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
- DOCUMENTATION.md
- EXAMPLES.md
- ProjectSettings/EditorBuildSettings.asset
- ProjectSettings/TagManager.asset
The new Snap Drop Zone prefab allows an interactable object to be
placed in a specific areas. When the interactable object is held over
a snap drop zone, the destination for the dropped object is highlighted
and when the object is released it's position, scale and rotation are
matched to the highlighted object's settings.
An example scene has been added to show the prefab in use.
> feat(SnapDropZone): add prefab to allow for set drop zones for objects - resolves #32 - resolves #90

- Assets/VRTK/Scripts/VRTK_InteractGrab.cs
Replace PR #673
Currently when throwing grabbed object, the velocity is based on center
of steam controller. Change to increase velocity based on distance
object is attached to controller.
Example: Ball at end of stick will move at greater speed,
compared to where stick is being held.
Based on article at http://www.normalvr.com/blog/throwing-throw-down/
> feat(Interaction): alter velocity of thrown object based on distance

- Assets/VRTK/Examples/034_Controls_InteractingWithUnityUI.unity
- Assets/VRTK/Examples/Resources/Scripts/Setup_Scene_034.cs
- Assets/VRTK/Examples/Resources/Scripts/UI_Interactions.cs
- Assets/VRTK/Examples/Resources/Scripts/VRTK_ControllerUIPointerEvents_ListenerExample.cs
- Assets/VRTK/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/VRTK/Scripts/Helper/UnityEvents/VRTK_UIPointer_UnityEvents.cs
- Assets/VRTK/Scripts/Helper/VRTK_EventSystemVRInput.cs
- Assets/VRTK/Scripts/Helper/VRTK_PlayerObject.cs
- Assets/VRTK/Scripts/Helper/VRTK_UIGraphicRaycaster.cs
- Assets/VRTK/Scripts/VRTK_BezierPointer.cs
- Assets/VRTK/Scripts/VRTK_InteractTouch.cs
- Assets/VRTK/Scripts/VRTK_SimplePointer.cs
- Assets/VRTK/Scripts/VRTK_UICanvas.cs
- Assets/VRTK/Scripts/VRTK_UICanvas.cs.meta
- Assets/VRTK/Scripts/VRTK_UIDraggableItem.cs
- Assets/VRTK/Scripts/VRTK_UIDraggableItem.cs.meta
- Assets/VRTK/Scripts/VRTK_UIDropZone.cs
- Assets/VRTK/Scripts/VRTK_UIDropZone.cs.meta
- Assets/VRTK/Scripts/VRTK_UIPointer.cs
- DOCUMENTATION.md
The UI Pointer click action can now be chosen per UI Pointer script.
Previously, the UI Click action would fire when the UI Click alias
button was pressed and the released (on click up) however it is also
a good idea to provide an option to fire the click action when the
UI Click alias button is pressed down.
The On Click Up works like a mouse click, if a mouse button is pressed
then the action on a clicked button is only triggered when the mouse
button is released.
However, the On Click Down works like a keyboard, if a key is pressed
then the action to type is done as the key is pressed down not when
it is released.
> feat(UIPointer): add ability to choose click on button down or up - resolves #525 - resolves #639 - resolves #675

- Assets/VRTK/Examples/008_Controller_UsingAGrabbedObject.unity
- Assets/VRTK/Scripts/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/VRTK_InteractTouch.cs
- Assets/VRTK/Scripts/VRTK_InteractUse.cs
- Assets/VRTK/Scripts/VRTK_InteractableObject.cs
- DOCUMENTATION.md
The Using state of an Interactable Object would get out of sync due to
the previous method of stopping an object's use method utilising a
co-routine at the end of the frame.
This was implemented due to StopTouching always being called even when
an object is grabbed. The fix is to remove the Coroutine as it causes
too many issues and to fix the issue at StopTouching by preventing
a stop touch event in the LateUpdate if the object is actually being
grabbed by the touching object, if it's being grabbed then it hasn't
stopped being touched in that instance.
This means that the Using action can get override correctly and no
artifacts are introduced at the end of the frame when stop using was
being called again, creating corruption with the Using State.
The toggle controller visibility has also …
> fix(Interaction): ensure using state is set correctly after touch/grab - resolves #688

- Assets/VRTK/Scripts/Abstractions/VRTK_WorldPointer.cs
- Assets/VRTK/Scripts/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/VRTK_SimplePointer.cs
- DOCUMENTATION.md
A new parameter on the World Pointer can now be set that when a
pointer is set to `Interact With Objects = true` rather than on grab
snapping the object to the controller, it now uses the pointer tip
as the attach point.
The length of the pointer is locked at the point of grabbing so it's
not possible to bring the objects closer or move them further away
but a potential feature in the future could be custom public methods
on the pointer scripts that allow the manual entry of a pointer length
so it could be controller via an input of a controller.
> feat(Interaction): add grab to pointer tip - resolves #683

- Assets/VRTK/Scripts/Internal/VRTK_ControllerTracker.cs
The colliders added automatically by the script
are now scaled properly according to the parent scale
> fix(Controller): ensure controller colliders scale

- Assets/VRTK/Scripts/Utilities/VRTK_AdaptiveQuality.cs
Whenever the render scale is changed the old frame is visible for some
time, looking like flickering when `AdaptiveQuality` is enabled. The
fix is to change the render scale in `LateUpdate` on Unity 5.4.3, too.
> fix(AdaptiveQuality): prevent flickering on Unity 5.4.3

- Assets/VRTK/Scripts/Internal/VRTK_CurveGenerator.cs
- Assets/VRTK/Scripts/Pointers/VRTK_BezierPointer.cs
- DOCUMENTATION.md
The Bezier Pointer beam can occasionally clip through the floor due
to the way the curve is calculated based on 1 forward point and 1
downward point.
This fix casts additional rays along the curve to check for early
collisions and if a collision is found then the target location
is updated to prevent clipping.
> fix(Pointer): prevent bezier pointer clipping - fixes #617

- EXAMPLES.md
- MADEWITHVRTK.md
- README.md
The README has been reformatted to read in a better flow, and the list
of games made with VRTK has been split out into it's own file as it was
getting too long for the README file.
> chore(README): reformat readme and split out things made with vrtk list

- Assets/VRTK/Scripts/Pointers/VRTK_SimplePointer.cs
The simple pointer can flicker when it is activated in a new position
as the position didn't change untit after the renderers were enabled.
This fix disables the renderers on initial beam activation until the
position has been updated and then the renderers are then set to
their correct state.
> fix(SimplePointer): prevent flicker on activate in different position

- Assets/VRTK/Examples/034_Controls_InteractingWithUnityUI.unity
- Assets/VRTK/Scripts/UI/VRTK_UICanvas.cs
The scale of the colliders is now calculated based on the scale of the
canvas transform and the position of the colliders is calculated based
on the pivot of the canvas.
Thanks to @getwilde for the fixes for pivot position.
> fix(UICanvas): calculate collider depth based on scale and pivot

- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_BaseGrabAttach.cs
The snap handle rotation is inverted when using a tracked object grab
mechanic. However, it was using the rotation to invert which caused
issues if the object had been rotated in the scene. Rotating the
local rotation of the snap handle is enough to fix the inversion issue
and this does not affect the object if it's world rotation has been
changed.
> fix(Interaction): use local rotation when inverting tracked snap handle

- Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs
Previously, there was a check to see if a collider on the controller
had been disabled by checking in the `LateUpdate` method which worked
but only because SteamVR locked the physics time step meaning the
physics routine (running the OnTrigger stuff) was in sync with the
Update/LateUpdate routines.
However, if the physics time step was not locked (e.g. if using the
simulator) then it would be possible to get the LateUpdate routine
to run during the physics loop and cause objects to constantly be
touched and untouched.
As FixedUpdate is a physics routine, it's best to do some of the
checks in there then the different time steps won't cause any
issues.
> fix(Interaction): ensure collision checks are done in physics loop

- Assets/VRTK/Scripts/Controls/2D/RadialMenu/RadialMenu.cs
The radial menu offset rotation was inverted causing issues when
pressing the touchpad as the touch position was not in the same
location as the button position.
This fix inverts the touch coordinate to ensure it matches the
button position.
> fix(RadialMenu): apply correct rotation offset to menu

- Assets/VRTK/Scripts/Internal/VRTK_EventSystemVRInput.cs
- Assets/VRTK/Scripts/UI/VRTK_UIPointer.cs
Previously, whenever a UIPointer was initialised it would get added to
the Event Input pointers list, but it could end up being added multiple
times to the same list as no checking was done to see if it already
existed within the list and it was also not removed from the list when
the UIPointer was disabled.
This fix ensures the list is correctly managed and also caches the
event system and event system input to prevent them from being re-found
each time a pointer is enabled.
> fix(UIPointer): ensure event input pointers list is managed correctly

- Assets/VRTK/Examples/Resources/Scripts/FireExtinguisher_Sprayer.cs
The used properties of a `ParticleSystem` are now on its `MainModule`.
> fix(Examples): fix a warning on Unity 5.5 and above

- Assets/VRTK/Scripts/Interactions/VRTK_ControllerEvents.cs
Two `Vector2`s were compared by using a string based method which
creates garbage on every call which decreases performance. The solution
is to do it without using strings and only relying on stack allocated
structs.
Thanks to @reznovvr for this performance fix.
> perf(ControllerEvents): don't create garbage on vector comparison

- Assets/VRTK/Scripts/Pointers/VRTK_BasePointer.cs
- Assets/VRTK/Scripts/Pointers/VRTK_SimplePointer.cs
It doesn't make sense to first set the local space values of a
transform and immediately overriding them by setting the world space
values.
> fix(SimplePointer): set pointer transform correctly

- Assets/VRTK/Scripts/Pointers/VRTK_BezierPointer.cs
- Assets/VRTK/Scripts/Pointers/VRTK_PlayAreaCursor.cs
The `ToggleBeam` method was not turning off the bezier pointer as it
was only setting the bezier state to inactive but not actually changing
the visibility of the bezier pointer.
This fix ensures that the bezier pointer objects are turned off when
the beam is toggled off.
> fix(Pointer): ensure ToggleBeam() turns off bezier pointer - fixes #797

- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
The VRTK SteamVR SDK used `uint.MaxValue` to check if a controller
index is out of bounds. This change makes sure the OpenVR provided
constant for the first invalid tracked device index is used instead.
`uint.MaxValue` is still used for everything that is VRTK API since it
is used to signal an invalid or missing index.
> refactor(SDK): use OpenVR provided invalid index

- Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
The `Awake()` method is supported in the ScriptableObject so it's
more appropriate to use this and `[RuntimeInitializeOnLoadMethod]`
only works on static methods meaning the `Initialise()` method was
never being run.
The Oculus SDK doesn't need an Awake method as the controllers
are not ready to be cached at that time anyway and the cache setup
will be run the first time they are called, which is a more
appropriate time to set the cache up as the other dependencies will
be available.
> fix(SDK): run controller init code using Awake

- Assets/VRTK/Examples/Resources/Scripts/Sword.cs
- Assets/VRTK/SDK/Base/SDK_BaseHeadset.cs
- Assets/VRTK/SDK/Fallback/SDK_FallbackHeadset.cs
- Assets/VRTK/SDK/OculusVR/SDK_OculusVRHeadset.cs
- Assets/VRTK/SDK/Simulator/SDK_SimHeadset.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRHeadset.cs
- Assets/VRTK/SDK/VRTK_SDK_Bridge.cs
- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_BaseGrabAttach.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ControllerEvents.cs
- Assets/VRTK/Scripts/Internal/VRTK_TrackedController.cs
- Assets/VRTK/Scripts/Internal/VRTK_TrackedHeadset.cs
- Assets/VRTK/Scripts/Internal/VRTK_TrackedHeadset.cs.meta
- Assets/VRTK/Scripts/Locomotion/VRTK_PlayerClimb.cs
- Assets/VRTK/Scripts/Utilities/VRTK_DeviceFinder.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs
- DOCUMENTATION.md
The Velocity tracking on the controllers was originally done in
Controller Events, but this is not the best place for it as velocity
retrieval is not really an event. The Velocity and Angular Velocity
retrieval methods have now been moved to the Device Finder script.
The Controller SDK Update routine has also been moved out of
Controller Events and into the Tracked Controller script as this script
is always available in the scene.
An addition of a Tracked Headset script has also been added that runs
an Update routine for the headset within the SDK mimicking the
functionality of the Tracked Controller update.
The methods in the Controller Events script are still in place but have
been deprecated (and removed from the documentation) and now all they
do is pass through the call to the Device …
> chore(velocity_tracking): move velocity tracking to device finder

- Assets/VRTK/Scripts/Locomotion/VRTK_TouchpadWalking.cs
- DOCUMENTATION.md
The Touchpad Walking script now has an option to press an additional
button to activate a speed multiplier which if is set to a number
above 1f then it will speed up the movement, however if it is set
below 1f then it will slow movement down.
> feat(Locomotion): add speed multiplier button to touchpad walking

- Assets/VRTK/Scripts/Internal/VRTK_EventSystemVRInput.cs
- Assets/VRTK/Scripts/UI/VRTK_UIPointer.cs
- DOCUMENTATION.md
A new `Click After Hover Duration` inspector parameter has been added
that means when the pointer is hovering over a UI element and has been
hovering over the same elemenet for the duration given in the param
then the UI Click will be triggered allowing for auto clicking items
which is useful for head gaze UI solutions.
> feat(UIPointer): allow for auto click after pointer hover timer - resolves #819

- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
I don't know if there was a specific reason it was being done in the other order, but I just ran into this one - it loses the local scale of the model because Unity will re-calculate scales when you set the parent. So you need to set the parent first.
Case where it was uses: Gameobject with scale of 0.015 holding mesh of scale 1 which was the interactable. When touching it, spawned highlighted mesh was at scale 66x because it would recalculate its scale to match the previous scale of 1x the root, rather than 1x the new mesh.
> fix(Highlighters): ensure cloned object parent is set first

- Assets/VRTK/Scripts/Interactions/VRTK_InteractUse.cs
Brings it in line to the other AttemptHaptic functions (i.e on grab). Stops the object reference null error that can occur.
> fix(Interaction): ensure a valid using object is present before haptics

- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
The copy highlighter needs a scale of 1,1,1 to match the size of the parent, otherwise if the parent doesn't have a scale of 1,1,1 it'll be smaller/bigger than the parent.
> fix(Highlighters): Use local scale of 1,1,1 to match parent size

- Assets/VRTK/Examples/029_Controller_Tooltips.unity
- Assets/VRTK/Examples/Resources/Scripts/VRTK_ControllerAppearance_Example.cs
- Assets/VRTK/Examples/Resources/Scripts/VRTK_ControllerEvents_ListenerExample.cs
- Assets/VRTK/Prefabs/ControllerTooltips.prefab
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs
- Assets/VRTK/SDK/Base/SDK_BaseController.cs
- Assets/VRTK/SDK/Fallback/SDK_FallbackController.cs
- Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs
- Assets/VRTK/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/SDK/VRTK_SDK_Bridge.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ControllerActions.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ControllerEvents.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_MoveInPlace.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_ControllerEvents_UnityEvents.cs
- DOCUMENTATION.md
The Oculus SDK supports a start button as the left controller
menu button can be overriden to be used as a start button although
the right controller menu button is reserved for Oculus Home.
This adds the support for the start button to the Oculus SDK and to
any other VRTK classes or prefabs that deal with buttons.
> feat(SDK): add support for start button - resolves #816

- Assets/VRTK/SDK/Base/SDK_BaseHeadset.cs
- Assets/VRTK/SDK/Fallback/SDK_FallbackHeadset.cs
- Assets/VRTK/SDK/OculusVR/SDK_OculusVRHeadset.cs
- Assets/VRTK/SDK/Simulator/SDK_SimHeadset.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRHeadset.cs
- Assets/VRTK/SDK/VRTK_SDK_Bridge.cs
- Assets/VRTK/Scripts/Utilities/VRTK_DeviceFinder.cs
The DeviceFinder and SDK classes provide methods to receive the
velocity and angular velocity of controllers. This change adds methods
to retrieve those velocities of the headset. The controller velocity
methods of the VRTK SteamVR SDK have been updated to only return
velocities of controllers, not the headset, because SteamVR uses
indexes for all the tracked objects.
> feat(headset_velocity): add methods to get velocities for headset

- Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs
- Assets/VRTK/Scripts/Pointers/VRTK_BasePointer.cs
The pointer activates use action would cause the `StartUsing` method
on the interactable object to continually execute.
This fix only runs the StartUsing method if it's not already being
used.
> fix(Interaction): prevent pointer use constantly calling start using - resolves #833

- Assets/VRTK/Scripts/Utilities/VRTK_AdaptiveQuality.cs
The debug visualization was not correctly parented to the headset. This
change makes sure to only attach at the appropriate moment to fix the
problem.
> fix(AdaptiveQuality): ensure debug visualization moves with headset

- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
Change the parent of the OutlineObjectCopyHighlighter cloned object to
the same parent as the original object.
Change the parent setting to not re-compute world position.
Change the transform assignments from world to local (faster), because
now the parent is the same.
The OutlineObjectCopyHighlighter cloned object needs to have the
parent set to the same parent of the customOutlineModel to exactly
match its shape. Even the PR #828 still causes problems with a hierarchy
of game objects with different scaling (e.g customOutlineModel with its
own scaling as child of the game object with its own scaling, holding
the OutlineObjectCopyHighlighter component).
> fix(Interaction): parent of the outline highlighter cloned object

- Assets/VRTK/Scripts/Interactions/VRTK_InteractControllerAppearance.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractHaptics.cs
- DOCUMENTATION.md
The Interactable Object script has a couple of helper scripts such as
Interact Haptics and Controller Appearance that need to be on the same
GameObject as the Interactable Object.
This fix throws a Log Error if they are attached to anything other than
an Interactable Object.
> fix(Interaction): set error if helper script not on interactable object - fixes #848

- Assets/VRTK/Scripts/Pointers/VRTK_SimplePointer.cs
There was an issue where the pointer interaction collider would not be
set to the correct size if the pointer had been initialised too early
before the pointer tip size had been set.
This fix ensures the interaction collider is always resized every time
the pointer is toggled.
> fix(Pointer): ensure pointer interaction collider is sized correctly - fixes #836

- Assets/VRTK/Scripts/Controls/2D/PanelMenu/PanelMenuController.cs
Fxies an issue where the PanelMenuController would only work for the SteamVR platform.
Instead of searching for hardcoded objects, use the SDK Manager to find the correct gameobject.
> Fix Panel Orientation on all platforms

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
Upon force snapping to a snap drop zone, the interactable object state
needs to be set, because if it is snapped then the SaveCurrentState
method won't be run and the previous parent will not be saved causing
it to lose it's parent when it is unsnapped and dropped.
Calling SaveCurrentState before the force snap takes place means the
previous parent will be adhered to when it is dropped.
> fix(SnapDropZone): save interactable object state before force snap - Resolves #855

- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_MaterialColorSwapHighlighter.cs
- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_MaterialPropertyBlockColorSwapHighlighter.cs
- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_MaterialPropertyBlockColorSwapHighlighter.cs.meta
Materials are now cloned when backing them up so there is no way the ChangeToHighlightColor function can overwrite these settings.
Fixes https://github.com/thestonefox/VRTK/issues/844
> fix(Interaction): backup / restore of materials

- Assets/VRTK/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ControllerEvents.cs
When trying to develop without any VR-Hardware, the simulator comes in really handy. However, I noticed that some events on the simulator (e.g. touchdown, touchup, touched on any buttons) are never fired. While it makes sense to not fire those events from a technical perspective (since we cannot distinguish between press and touch on a keyboard) it makes developing a whole lot harder, since a developer potentially has to use different types of events during development (Simulator) and in production (HMD). 
Furthermore, the Simulator SDK right now does not allow for finding script alias controllers. Whenever the calls to get a controller (e.g. `GetControllerLeftHand` or `GetControllerByIndex`) are used, the boolean `actual` parameter is simply ignored and the actual controllers are always …
> fix(SDK): controller retrieval and touch events in simulator

- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_RotatorTrackGrabAttach.cs
- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_TrackObjectGrabAttach.cs
- DOCUMENTATION.md
The rotator track mechanic should not apply thrown velocity when the
interactable object is released otherwise it causes the joint to
bounce back.
The fix for this is to override the `StopGrab` method on the Track
Object and prevent it from doing the ReleaseObject method which
is what adds the velocity.
> fix(Interaction): prevent rotator track applying velocity on release

- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_BasicTeleport_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_BodyPhysics_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_ControllerActions_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_ControllerEvents_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_DashTeleport_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_DestinationMarker_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_HeadsetCollision_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_HeadsetControllerAware_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_HeadsetFade_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractGrab_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractTouch_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractUse_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractableObject_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_PlayerClimb_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_SnapDropZone_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_UIPointer_UnityEvents.cs
Previously, the Unity Event Helper scripts were not initialising the
event parameters meaning that if the events were used via script then
they would throw a null reference error. They would work in the editor
as Unity would provide a default state for them.
This fix ensures that all events set up a default event and are
no longer null.
> fix(UnityEvents): ensure all unity event helpers initialise event.

- Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs
The Teleporter script runs a co-routine at the end of the frame to
register any destination markers. However, if the script is disabled
within the first frame then the co-routine is still executed and
registers the listeners even if they're not required.
This fix only registers the listeners if the teleporter script is
enabled and the co-routine is also cancelled when the script is
disabled.
> fix(Teleporter): ensure listener coroutine is not run if disabled - fixes #884

- CODE_OF_CONDUCT.md
- ISSUE_TEMPLATE.md
New markdown files have been added to outline issue creation template
and to provide a concise code of conduct for the VRTK community to
aspire towards.
> docs(Templates): add new template for code of conduct and issues

- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
Change the way the transform of the OutlineObjectCopyHighlighter cloned
object is computed.
First set the same parent as the original object, copy the local
transform, then set the parent to `transform`, the owner of the
OutlineObjectCopyHighlighter component, as it was before this commit.
This resolves both PR #828 and PR #850.
The PR #828 still causes problems with a hierarchy of game objects with
different scaling (e.g customOutlineModel with its own scaling as child
of the game object with its own scaling, holding the
OutlineObjectCopyHighlighter component).
The PR #850 broke the Outline Highlighter setting it as the parent,
preventing the outline to follow the object around.
> fix(Interaction): scale of the outline highlighter cloned object - fixes #828, #850

- Assets/VRTK/Examples/017_CameraRig_TouchpadWalking.unity
- Assets/VRTK/Scripts/Locomotion/TouchpadControlActions.meta
- Assets/VRTK/Scripts/Locomotion/TouchpadControlActions/VRTK_BaseTouchpadControlAction.cs
- Assets/VRTK/Scripts/Locomotion/TouchpadControlActions/VRTK_BaseTouchpadControlAction.cs.meta
- Assets/VRTK/Scripts/Locomotion/TouchpadControlActions/VRTK_RotateTouchpadControlAction.cs
- Assets/VRTK/Scripts/Locomotion/TouchpadControlActions/VRTK_RotateTouchpadControlAction.cs.meta
- Assets/VRTK/Scripts/Locomotion/TouchpadControlActions/VRTK_SlideTouchpadControlAction.cs
- Assets/VRTK/Scripts/Locomotion/TouchpadControlActions/VRTK_SlideTouchpadControlAction.cs.meta
- Assets/VRTK/Scripts/Locomotion/TouchpadControlActions/VRTK_SnapRotateTouchpadControlAction.cs
- Assets/VRTK/Scripts/Locomotion/TouchpadControlActions/VRTK_SnapRotateTouchpadControlAction.cs.meta
- Assets/VRTK/Scripts/Locomotion/TouchpadControlActions/VRTK_WarpTouchpadControlAction.cs
- Assets/VRTK/Scripts/Locomotion/TouchpadControlActions/VRTK_WarpTouchpadControlAction.cs.meta
- Assets/VRTK/Scripts/Locomotion/VRTK_TouchpadControl.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_TouchpadControl.cs.meta
- Assets/VRTK/Scripts/Locomotion/VRTK_TouchpadMovement.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_TouchpadWalking.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_TouchpadControl_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_TouchpadControl_UnityEvents.cs.meta
- DOCUMENTATION.md
The new Touchpad Control script is a more generic implementation of the
existing Touchpad Walking script and it allows for custom touchpad
control actions to be written and used in place. This feature makes
the touchpad control aspect more composable and easier to create custom
features.
There is currently only one provided touchpad control action which is
the Slide action and it replicates the same functionality as the
existing Touchpad Walking script.
Because of this duplication in features, the Touchpad Walking script
has now been deprecated and a warning message is shown in the inspector
panel on the script.
The TouchpadWalking example scene has been updated to use the new
Touchpad Control script to provide a demonstration of how to use it.
> feat(Locomotion): add new generic touchpad control script

- Assets/VRTK/Scripts/Pointers/VRTK_BasePointer.cs
The interactor collider is updated to match the current pointer
position. Previously, it was done in the Update method but this meant
that the interactor collider would lag behind the pointer tip causing
issues.
Putting the update of the interactor collider in the FixedUpdate
method means it is updated more frequently and therefore it has a
higher level of fidelity removing any glitches that were previously
showing up.
> fix(Pointer): update interactor collider in FixedUpdate - fixes #911

- Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs
Previously, the `forceDropped` was set to true when stop touching and
stop using was called. This would cause issues when an object was
disabled and re-enabled as the previous state would be loaded even
though it hasn't currently been saved.
There is no reason to set `forceDropped` to true on stop touch or
stop use as it's only relevant when an object is being grabbed because
this is the only way it can be force dropped.
> fix(Interaction): only set force dropped when stop grabbing

- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
Previously was only highlighting the first submesh found, rather than
the whole mesh. Added as a bool option to avoid any unforeseen
consequences for current users
Not to be confused with multiple MeshRenderers/objects,
that's a different problem altogether.
> fix(Highlighters): Added option to merge submeshes on copy

- Assets/VRTK/Editor/VRTK_ObjectSetup.cs
Force button overrides to undefined since when upgrading they
will not be undefined anymore, which is very unexpected behaviour.
> fix(objectSetup): force button overrides to undefined

- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
When climbing, grabbing the same object with your other hand
would not put the PlayerClimb physics kinematic state in the
correct value. This came from the correct state not being stored
when the player velocity modifies the object. This would cause
heavy flickering of the Oculus touch controllers as physics was
fighting with the system to get the player area in the correct
spot.
> fix(Climbing): Jitter on second hand grab climb state

- Assets/VRTK/Examples/044_CameraRig_RestrictedTeleportZones.unity
- Assets/VRTK/Examples/044_CameraRig_RestrictedTeleportZones.unity.meta
- Assets/VRTK/Examples/Resources/Models/Materials/LightRing.mat
- Assets/VRTK/Examples/Resources/Models/Materials/LightRingGreen.mat
- Assets/VRTK/Examples/Resources/Models/Materials/LightRingGreen.mat.meta
- Assets/VRTK/Examples/Resources/Models/Materials/LightRingRed.mat
- Assets/VRTK/Examples/Resources/Models/Materials/LightRingRed.mat.meta
- Assets/VRTK/Prefabs/DestinationPoint.prefab
- Assets/VRTK/Prefabs/DestinationPoint.prefab.meta
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DestinationPoint.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DestinationPoint.cs.meta
- Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs
- DOCUMENTATION.md
- EXAMPLES.md
A new Destination Point prefab has been added that provides a way of
having pre-determined teleport locations.
The destination points can be a single point position in the scene
or provide a boundary that can only be teleported within.
> feat(Locomotion): add destination point prefab

- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BezierPointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs
- DOCUMENTATION.md
There was an issue where the cursor and tracer visibility could not
be toggled to always visible unless a toggle event was called.
There was another issue where if the tracer or cursor was active
that the interaction object would not be enabled until the pointer
activation button was pressed.
This has now been fixed by ensuring the correct state of the tracer
and cursor visibility is checked taking into account the visibility
state. Also, if the tracer or cursor is visible even when the
pointer activation button hasn't been pressed then the object
interactor will be activate.
> fix(Pointer): ensure visibility and interaction states are toggled

- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_TransformFollow.cs
Setting either the visibility flag of the tracer or cursor of any of the
pointer renderers resulted in not drawing anything or never updating the
rendered object. This fix makes sure to account for the visibility
flags.
> fix(Pointer): always on visibility

- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BezierPointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/VRTK_BasePointer.cs
- Assets/VRTK/Scripts/Pointers/VRTK_PlayAreaCursor.cs
- Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs
- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_RigidbodyFollow.cs
- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_TransformFollow.cs
- DOCUMENTATION.md
If the tracer or cursor was set to always on and the activation button
was pressed then the cursor would be set to disable renderers and
re-enable next frame which would cause the flickering.
This has now been resolved by only calling the disable if the pointer
isn't using always on.
Another issue has been fixed with the play area cursor not coming on
and staying on at the right times. It should always come on when the
cursor is active as it's an extension of the cursor.
The documentation has also been generated, which includes the docs
for the pointer smoothing work as well.
> fix(Pointer): prevent flickering when activating an always on pointer

- Assets/VRTK/Scripts/Presence/VRTK_PositionRewind.cs
If any play area velocity is being applied prior to the rewind then
it will be applied to the play area when the rewind happens.
This fix checks to see if the play area has a rigidbody and force
resets the velocity to zero on rewind.
> fix(PositionRewind): reset play area velocity on rewind.

- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
- DOCUMENTATION.md
The outline highlighter now supports multiple custom objects or paths
when creating the outline object.
The variable name has changed which will cause breaking changes for
existing uses of the previous variable names.
> feat(Highlighter): add multiple object support in outline highlighter

- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/VRTK_BasePointer.cs
- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_ObjectFollow.cs
- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_RigidbodyFollow.cs
- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_TransformFollow.cs
The object follow script is changed so the game object it is attached to
is used for `gameObjectToChange` if none is set. This simplifies usage
of the object follow scripts.
Additionally an issue with the Oculus Avatar SDK is fixed: The OculusVR
boundaries SDK wasn't correctly setting up the transform follow script
to change the game object the OVRAvatar is attached to. This resulted in
the avatar not moving at all.
> refactor(ObjectFollow): change attached game object by default

- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
The SteamVR plugin was updated to version 1.2.1. This fix makes sure to
adapt to the changes done to the `SteamVR_Events.System` method.
> fix(SteamSDK): support SteamVR plugin 1.2.1

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
There was an issue where if 2 snap drop zones were next to each other
and highlighting always on was selected that when an object was dropped
into one of the snap drop zones the highlighter would turn off on the
other snap drop zone.
> fix(SnapDropZone): prevent highlight turning off when set to always on

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DestinationPoint.cs
The Destination Point is a Destination Marker yet it only implemented
the Destination Set event. Now it also implements the Destination Enter
and Destination Exit event so it's possible to know when something
is hovering over the destination point.
> feat(DestinationPoint): emit on enter and exit destination marker event

- Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs
- DOCUMENTATION.md
A new parameter has been added to the Interactable Object script that
allows an array of colliders to be provided that will be ignored
when the controller touches the Interactable Object.
This is useful if an object has a collection of child colliders but
not all of those should react to the touch events.
Example: A sword will have a collider on the blade and hilt, but the
user will only want to be able to pick the sword up by the hilt so
the blade collider will be added to the ignore list.
If the Ignored Colliders parameter is changed at runtime then the
ResetIgnoredColliders() method also needs to be called as the
ignored controller objects get cached so the colliders are not
continually iterated through on every touch event.
> feat(Interaction): allow sub colliders to be ignored on interactables - fixes #870

- Assets/VRTK/Scripts/Locomotion/VRTK_PlayerClimb.cs
- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
When the play area is scaled, throwing yourself from a
hand hold resulted in a double scaled velocity. It was
being applied in VRTK_PlayerClimb as well as when transforming
the vector to world space in BodyPhysics. This fix removes the
scale from happening in BodyPhysics, thus keeping the input
parameter as a world space input, and changing the value
instead in PlayerClimb (to world space orientation) before
passing the velocity along.
> fix(Climbing): scaled throw from climb

- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs
`VRTK_StraightPointerRenderer` offers to scale the pointer cursor based
on the distance from the tracer origin via `cursorDistanceRescale`. This
change adds a new field that allows to specify the maximum allowed
cursor scale.
> feat(StraightPointerRenderer): add maximum cursor scale

- Assets/VRTK/Editor/VRTK_SDKManagerEditor.cs
The SDK Manager allows to automatically manage the scripting define
symbols. If it's set up to do so the button to trigger the managing is
disabled.
This change makes sure to explain why that button is disabled currently
and how to enable it again.
> chore(SDKManager): explain why manage now button is disabled

- Assets/VRTK/Editor/VRTK_SDKManagerEditor.cs
The inspector for the SDK Manager doesn't allow clicking the auto
populate button if the manager is set up to populate the object
references automatically. Since the auto-populating only occurs whenever
an SDK selection is changed this lead to a problem when changing any of
the objects to reference.
To allow populating the object references manually this fix makes sure
to enable the button at all times.
> fix(SDKManager): enable auto populate button at all times

- Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs
The SDK Manager's method `ManageScriptingDefineSymbols` should only be
available when in the editor but was mistakenly not surrounded by the
needed `#if` and `#endif`. This fix makes sure to add those preprocessor
directives so the method is only available in the editor.
> fix(SDKManager): move method to editor only

- Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs
The SDK Manager made sure to not trigger the managing of the scripting
define symbols and population of the object reference when a scene is
reloaded. This behavior is wrong when the following is done:
- Change which SDKs are used or which objects are referenced in the SDK
Manager.
- Wait for it to change the scripting define symbols (if needed).
- Reload the scene **without** saving the changes done to the SDK
Manager.
This results in a scene reload that neither reverts the scripting define
symbols, nor the object references according to the previous
configuration of the SDK Manager.
This fix makes sure to always manage the scripting define symbols and
populate the object references on a scene reload.
> fix(SDKManager): handle scene reload

- Assets/VRTK/Scripts/UI/VRTK_UICanvas.cs
The UI Canvas creates a child game object to enable drag and drop of UI
elements on the canvas. That child object is a UI object so it gets
added a `RectTransform`. A `RectTransform` is inheriting from
`Transform` which means Unity does some stuff to the child object to
switch to that new transform. In Unity 5.6 this switching changed
somehow so the current implementation results in the parent of the
canvas' game object getting disabled.
The fix is to add the `RectTransform` as early as possible and only
adjust the parent and position of the transform afterwards.
> fix(UICanvas): unusable in Unity 5.6

- Assets/VRTK/SDK/SteamVR/SDK_SteamVRDefines.cs
The SteamVR defines incorrectly used a SteamVR type directly which
resulted in compiler errors if the SteamVR plugin is not included in the
project. This fix makes sure to not use any SteamVR type directly and
resorts to use reflection instead.
> fix(SDK): SteamVR defines

- Assets/VRTK/Scripts/Internal/VRTK_RoomExtender_PlayAreaGizmo.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs
The play area gizmo of the RoomExtender looks up the play area in
`Awake` and later uses it when drawing the gizmo. The issue is that the
SDK Manager is not set up correctly at that point in time so the
returned play area is null, resulting in errors when trying to draw the
gizmo.
This fix makes sure `VRTK_SDKManager.instance` is always set up, no
matter when the getter is called. Additionally the play area gizmo
drawing method is changed to not throw any errors if the needed objects
weren't found in the `Awake` method. That method logs a warning already,
so the user is notified about the reason the gizmo isn't drawing.
This fix resolves #985.
> fix(RoomExtender_PlayAreaGizmo): null play area

- Assets/VRTK/Scripts/UI/VRTK_UICanvas.cs
The draggable helper game object the UI Canvas uses interferes with the
layout system and shows up as an empty "ghost" object when used in
conjunction with a layout group. The fix is to add a `LayoutElement` and
setting `ignoreLayout` to true so the layout system ignores that element
completely.
This fix resolves #925.
> fix(UICanvas): ghost in layout group

- Assets/VRTK/SDK/OculusVR/SDK_OculusVRBoundaries.cs
The Oculus Avatar SDK is supported by making sure the `OvrAvatar`
follows the movement of the play area game object. The script that
handles the following was added multiple times in some cases. This fix
makes sure to only add the script if needed.
> fix(OculusAvatar): only set up once

- Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs
The haptics clip used for a tick of vibration was never reset, and would
previously get longer and longer until reaching its maximum length.
Adding a reset clears the clip, without reallocating memory.
Two clips are now used instead (left / right) since clearing the clip
would otherwise prevent both controllers from vibrating simultaneously.
> fix(OculusSDK): prevent increasing haptics duration on Oculus Touch

- Assets/VRTK/Scripts/Internal/VRTK_ControllerTracker.cs
The simulator would throw a `NullReferenceException` in
`SDK_SimController.GetControllerRenderModel` because the alias
controller wasn't parented to the actual one yet. This fix makes sure to
parent the script alias controller to the actual object immediately.
> fix(Simulator): render model null

- Assets/VRTK/Editor/VRTK_UpdatePrompt.cs
- Assets/VRTK/Editor/VRTK_UpdatePrompt.cs.meta
A new prompt window has been added that checks to see if the local
version of VRTK matches the latest release on github. If it does
not match then a prompt window appears informing the user that an
update is available and shows the latest chunk of the changelog.
It also provides a button to open the asset store page for VRTK and
provides an option to hide the popup window if the update isn't wanted.
> chore(Structure): add update prompt editor window

- Assets/VRTK/Examples/ExampleResources/Scripts/UI_Interactions.cs
- Assets/VRTK/Scripts/UI/VRTK_UICanvas.cs
Unity changed the way additions of components derived from `Transform`
are handled:
- From the 5.5.2p2 changelog:
>Kernel: Prevent scripts from adding Transform-derived components during
their Awake methods.
- From the 5.6.0b11 changelog:
>UI: Adding UI elements via script will cause OnDisable and OnEnable to
be called on all scripts in the hierarchy if a RectTransform needs to be
added.
To fix the first problem the creation of any game object that uses
`RectTransform` is deferred to the next frame. The second problem is
fixed by specifying the `RectTransform` to add in the game object
constructor.
> fix(UICanvas): RectTransform in 5.5.2p2 and 5.6

- Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs
Populating the object references of the SDK Manager was broken: You had
to switch to the Fallback SDK first and then switch to your desired SDK
to actually allow populating the object references based on the desired
SDK. The fix is to make sure the various object references are set to
`null` before asking the selected SDKs for their objects.
> fix(SDKManager): populate object references

- Assets/VRTK/Editor/VRTK_SDKManagerEditor.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SDKInfo.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs
Undoing or redoing changes to the selected SDKs of the SDK Manager lead
to a broken state of populated object references. The fix is to copy the
selected SDK Info whenever it's changed. That will prevent undos and
redos from changing the SDK Infos the SDK Manager uses as the list of
available SDK Infos. Additionally both the SDK Manager and its Editor
were simplified where possible.
> fix(SDKManager): undo and redo

- Assets/VRTK/SDK/Simulator/SDK_SimHeadset.cs
The simulator's headset script sometimes threw a
`NullReferenceException` in the editor after changing the selected SDK
in the SDK Manager. The fix is to handle a `null` headset in the script.
> fix(Simulator): null headset in Editor

- Assets/VRTK/Editor/VRTK_UpdatePrompt.cs
The update prompt was looking for the version file in a fixed location.
This fix makes sure that it looks at the location relative to the
installation path of VRTK.
> fix(UpdatePrompt): allow to move VRTK installation

- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_ObjectFollow.cs
- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_RigidbodyFollow.cs
- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_TransformFollow.cs
The Object Follow scripts cache some needed components in their
`OnEnable` methods. This meant that using these scripts at runtime
needed a toggle of their enabled state. The fix is to cache the
components even if the needed setup isn't done as soon as `OnEnable` is
called.
> fix(ObjectFollow): runtime usage

- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_ObjectFollow.cs
- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_RigidbodyFollow.cs
- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_TransformFollow.cs
The Object Follow scripts were updated to allow easier usage at runtime
in #1014. But they still threw errors when not disabling the runtime
created script early. The fix is to cache more often in the subclasses
and bail out early in the `VRTK_ObjectFollow.Follow` method.
> fix(ObjectFollow): runtime usage (again)

- Assets/VRTK/Prefabs/VRSimulatorCameraRig.prefab
- Assets/VRTK/SDK/Simulator/SDK_InputSimulator.cs
The Simulator allows to lock the mouse when controlling the hands. Since
this is very useful in the Editor it is now enabled by default.
Additionally the Simulator Camera Rig prefab has been updated to make
sure the hints text is always in the top left corner of the screen and
has a background to make reading the text easier.
> feat(Simulator): lock mouse by default and hints background

- Assets/VRTK/Scripts/Interactions/SecondaryControllerGrabActions/VRTK_AxisScaleGrabAction.cs
- Assets/VRTK/Scripts/Interactions/SecondaryControllerGrabActions/VRTK_ControlDirectionGrabAction.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs
There was an issue where the secondary controller was not notified of
the object release if the secondary controller was grabbing whilst the
primary controller was released.
The action is that the object is dropped and the secondary controller
has no influence over the object any more, but the secondary
controller Interact Grab script was not notified of the drop so it
would not emit the event and would keep the state of a grabbed object
until the grab button on the secondary controller was released.
This has been fixed by calling `ForceRelease` on the secondary
controller if the primary controller is ungrabbed. As the secondary
controller grab actions are cleaned up before the primary controller
then a `ForceRelease` should simply clean up the state of the
secondary controller Interact …
> fix(Interaction): force secondary controller release on primary drop

- Assets/VRTK/Scripts/Locomotion/VRTK_HeightAdjustTeleport.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BezierPointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs
- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
- Assets/VRTK/Scripts/Utilities/VRTK_CustomRaycast.cs
- Assets/VRTK/Scripts/Utilities/VRTK_CustomRaycast.cs.meta
- DOCUMENTATION.md
Many of the VRTK scripts utilise raycasts but have the raycast options
hard coded in the script. This new Custom Raycast script allows any
VRTK script that uses a raycast to have the raycast customised by
injecting a Custom Raycast into it.
Previously, the VRTK scripts that utilised a raycast would have a
`Layers To Ignore` parameter which would be passed through to the
raycast. However, this has now been deprecated as all of these scripts
can achieve the same customisation by using a Custom Raycast instead.
> feat(Utilities): add custom raycast script for customising rays - resolves #1034

- Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs
- Assets/VRTK/SDK/OculusVR/SDK_OculusVRDefines.cs
- Assets/VRTK/SDK/OculusVR/SDK_OculusVRHeadset.cs
Oculus updated their Utilities SDK to version 1.12.0 and introduced some
breaking changes. This fix adds support for the new version while
maintaining support for the previous version.
> fix(OculusSDK): support Utilities SDK version 1.12.0

- Assets/VRTK/Examples/044_CameraRig_RestrictedTeleportZones.unity
- Assets/VRTK/Prefabs/PointerDirectionIndicator.prefab
- Assets/VRTK/Prefabs/PointerDirectionIndicator.prefab.meta
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DestinationPoint.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_PointerDirectionIndicator.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_PointerDirectionIndicator.cs.meta
- Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs
- Assets/VRTK/Scripts/Pointers/VRTK_DestinationMarker.cs
- Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs
- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
- DOCUMENTATION.md
A new prefab has been added that displays a direction indicator on a
Pointer script that is used to denote the desired rotation for the
Destination Marker event.
This can be used now to rotate the play area upon teleporting based
on the direction that the indicator is pointing in.
The Direction Indicator is controller with the touchpad touch angle.
To use the prefab:
* Add the `PointerDirectionIndicator` prefab to the scene.
* Select the GameObject with the VRTK_Pointer to add the direction
indicator to.
* Drag and drop the `PointerDirectionIndicator` GameObject to the
VRTK_Pointer `Direction Indicator` inspector parameter.
* When the scene is running, a direction indicator will follow the
pointer cursor and the direction the indicator is facing will be
the direction the play area is …
> feat(Pointer): add pointer direction indicator prefab - resolves #1039

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
- DOCUMENTATION.md
There is now an option on the Snap Drop Zone to specify a default
snapped object that will be snapped into the drop zone when the
drop zone is enabled.
The object must also adhere to the snap drop zone policy list for
it to snap.
> feat(SnapDropZone): add default snapped object option

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractableObject_UnityEvents.cs
Mirror the events from `SnapDropZone` to the `InteractableObject`
because at times its more useful to observe these actions from the point
of view of the object being manipulated.
An example might be an object that changes shape depending if it's
hovering over or snapped to a drop zone.
This is the implementation for #1055
> feat(InteractableObject): add snap zone events

- Assets/VRTK/Scripts/Presence/VRTK_HeadsetControllerAware.cs
- Assets/VRTK/Scripts/Utilities/VRTK_CustomRaycast.cs
- DOCUMENTATION.md
The Headset Controller Aware script can now accept a CustomRaycast
object to determine how the Linecast from the Headset to the controller
interacts with other world objects.
> feat(Presence): add custom raycast option to headset controller aware - resolves #1054

- Assets/VRTK/Scripts/Pointers/VRTK_PlayAreaCursor.cs
- DOCUMENTATION.md
The Play Area Cursor can now accept a valid and an invalid prefab
parameter to customise the look of the play area cursor when it is
not colliding and when it is colliding with a valid object.
It's also possible to disable the pointer colour inheritance if a
more customised cursor is required.
Also, the custom play area cursor now resizes to the actual play area
boundaries sizes unless a custom size is entered.
> feat(Pointer): allow custom valid/invalid play area cursor object

- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BezierPointerRenderer.cs
- DOCUMENTATION.md
The Bezier Pointer Renderer now can have the downward length of the
beam set as well as setting the forward length of the beam.
This is now done by making the `maximumLength` parameter a Vector2
instead of a float where the `x` value represents the forward beam
length and the `y` value represents the downward beam length.
> feat(Pointer): add variable downward length on bezier pointer

- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
- DOCUMENTATION.md
The Body Physics script now supports a step offset height to determine
if a collided object is small enough to be climbed upon even if the
object is too high for the capsule collider to naturally resolve the
collision to the new height.
This is achieved with a sub capsule collider that sits below the main
collider and acts as a foot collider to detect when any objects are
collided with and then a box is cast down to see if the main body
collider should be standing on a new surface.
If the box cast is valid then the play area is either teleported to
the new position if a teleporter is available or the play area is just
snapped to the new position if no teleporter is available.
> feat(Presence): add step height support to body physics

- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/Scripts/Internal/VRTK_ControllerTracker.cs
- Assets/VRTK/Scripts/Internal/VRTK_TrackedController.cs
The HTC Trackers are now supported in a basic way by allowing for
additional tracked controllers to be supported by the SteamVR SDK
Bridge. The tracker support still requires manual configuration of
the tracker objects and only works with SteamVR. But until more
tracking solutions come out, this will be ok as the HTC trackers
can only be used with SteamVR at the moment anyway.
To set a tracker up:
* Follow HTC Tracker instructions to set object up with SteamVR
* Add `VRTK_TrackedController` to tracker object
* Add `VRTK_ControllerTracker` to tracker object
* The tracker object is now usable by VRTK
* Attach any controller scripts directly to the tracker object
> feat(SDK): allow additional tracked controller usage

- Assets/VRTK/SDK/Simulator/SDK_SimController.cs
The Simulator Controller SDK used a private helper class for keeping
track of the controller objects. This change removes that class and
instead keeps track of the controller objects directly in the Controller
SDK.
> refactor(Simulator): remove unnecessary private helper class

- Assets/VRTK/SDK/Base/SDK_ScriptingDefineSymbolPredicateAttribute.cs
A private variable in the Scripting Define Symbol Predicate Attribute
has been moved down to adhere to the coding conventions. Additionally an
exception message has been updated to keep the same style that is used
for the other error cases.
> chore(SDK): move private variable

- Assets/VRTK/Editor/VRTK_UpdatePrompt.cs
When checking for an VRTK update the Update Prompt tries to find the
version file by looking at the directory the script is in. This fix
makes sure to throw an exception on not finding the script instead of
using a `null` path, therefore making the issue more obvious in case
there is an issue finding the version file at all.
> fix(UpdatePrompt): prevent null path to version file

- Assets/VRTK/SDK/Simulator/SDK_SimHeadset.cs
The Simulator Headset SDK does the same for both the headset getter
methods. This change removes one of the implementations and calls the
other one instead to remove the duplicated code.
> refactor(Simulator): remove duplicated code

- Assets/VRTK/Scripts/Controls/2D/PanelMenu/PanelMenuController.cs
- Assets/VRTK/Scripts/Controls/2D/RadialMenu/VRTK_IndependentRadialMenuController.cs
- Assets/VRTK/Scripts/Presence/VRTK_HeadsetFade.cs
The Device Finder offers two transforms for the headset: One for the
headset itself and another one for the headset camera. This fix makes
sure to only use the headset camera when actually needed.
> fix(DeviceFinder): make sure to use correct headset transform

- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_BasicTeleport_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_BodyPhysics_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_Button_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_Control_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_ControllerActions_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_ControllerEvents_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_DashTeleport_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_DestinationMarker_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_HeadsetCollision_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_HeadsetControllerAware_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_HeadsetFade_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractGrab_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractTouch_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractUse_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractableObject_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_ObjectControl_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_PlayerClimb_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_SnapDropZone_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_UIPointer_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_UnityEvents.cs.meta
A new abstract superclass `VRTK_UnityEvents` has been added to simplify
and standardize the various existing UnityEvents scripts. Additionally
all the xml docs have been removed from the UnityEvents scripts because
they add nothing to the documentation (the documentation already refers
to have a look at the respective scripts' documentation to learn more
about the events).
> refactor(UnityEvents): simplify by using new abstract superclass

- Assets/VRTK/SDK/Daydream/SDK_DaydreamController.cs
- Assets/VRTK/SDK/OculusVR/SDK_OculusVRBoundaries.cs
- Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs
- Assets/VRTK/SDK/OculusVR/SDK_OculusVRHeadset.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRBoundaries.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRHeadset.cs
- Assets/VRTK/SDK/Ximmerse/SDK_XimmerseVRController.cs
- Assets/VRTK/SDK/Ximmerse/SDK_XimmerseVRHeadset.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SharedMethods.cs
The SDK classes need to search for some game objects or components. This
fix makes sure that the search for active as well as inactive game
objects and components always works.
> fix(SDK): find inactive game objects and components

- Assets/VRTK/Scripts/Internal/VRTK_Logger.cs
If the Logger was used in the Editor to log something it was added to
scene. This fix makes sure the Logger isn't visible in and is not saved
to the scene when in the Editor.
Additionally the `DontDestroyOnLoad` call has been moved to not be
called when destroying the object anyway.
> fix(Logger): saved to scene in Editor

- Assets/VRTK/SDK/Base/SDK_BaseBoundaries.cs
- Assets/VRTK/SDK/Daydream/SDK_DaydreamBoundaries.cs
- Assets/VRTK/SDK/Fallback/SDK_FallbackBoundaries.cs
- Assets/VRTK/SDK/OculusVR/SDK_OculusVRBoundaries.cs
- Assets/VRTK/SDK/Simulator/SDK_SimBoundaries.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRBoundaries.cs
- Assets/VRTK/SDK/VRTK_SDK_Bridge.cs
- Assets/VRTK/SDK/Ximmerse/SDK_XimmerseVRBoundaries.cs
- DOCUMENTATION.md
The status of whether a play area boundary is drawn can now be
retrieved and set via the SDK Bridge, which bubbles through to the
relevant SDK to check if the boundaries can be drawn.
At present, only SteamVR allows for checking if the boundary can be
drawn via the `SteamVR_PlayArea.drawInGame` variable.
The SteamVR Boundaries SDK has also been tidied up to cache the
GetComponent call to the SteamVR_PlayArea component.
> feat(SDK): add methods to get/set boundary draw status

- Assets/VRTK/SDK/Simulator/SDK_SimHeadset.cs
#1068 added headset fading to the Simulator SDK but actually missed two
other methods that need to be implemented for it to work correctly. This
fix implements those methods.
> fix(Simulator): missing headset fade implementations

- Assets/VRTK/Scripts/Interactions/VRTK_InteractUse.cs
Whenever the InteractUse script was disabled it stopped the usage of the
currently held object by the controller but also stopped the object's
using action. This fix makes sure to only force the controller to stop
the usage, not the object itself.
If users of VRTK depend on the old behavior they should stop the
object's usage themselves when the stopping is recognized using one of
the events or virtual methods.
> fix(Interactions): leave usage when disabling InteractUse

- GETTING_STARTED.md
The `GETTING_STARTED` document was updated to advise to set the tracking
origin type of the `OVRManager` to the floor level for Oculus because
VRTK no longer forces that setting.
> docs(GETTING_STARTED): advise to set Oculus tracking origin type

- .gitattributes
The `.gitattributes` file was set up to treat various Unity assets as
binary files but they are in fact text files. To allow diff'ing the
files git needs to treat these files as text files. Since treating files
as text files is the default this change removes the `.gitattributes`
file completely, as it doesn't do anything else.
> chore(gitattributes): allow asset diffs

- Assets/VRTK/SDK/Daydream/SDK_DaydreamController.cs
- Assets/VRTK/SDK/Simulator/SDK_SimController.cs
The Simulator and Daydream Controller SDKs looked up the controller
index by using the names of the game objects. To be more flexible and
allow other names, too, this fix uses the helper method available in the
base SDK class instead.
Additionally both Controller SDKs no longer return an index for the
headset because Controller SDKs should only care about controllers.
This fixes #1109.
> fix(SDK): name based controller lookup

- Assets/VRTK/Scripts/Utilities/VRTK_AdaptiveQuality.cs
> LateUpdate: LateUpdate is called once per frame, after Update has
> finished. Any calculations that are performed in Update will have
> completed when LateUpdate begins.
This is not the case anymore in Unity 5.5.3f1 when using the Oculus
SDK. The fix is to make sure `UpdateRenderScaleLevels` was called
before accessing `allRenderScales` in `UpdateRenderScale`.
> fix(AdaptiveQuality): index out of bounds when using Oculus Utilities

- Assets/VRTK/Scripts/Internal/VRTK_Logger.cs
Whenever the Unity serialization runs the serialization callbacks in SDK
Info are run. Since those methods were updated to use the VRTK Logger
Unity now throws errors because it's not allowed to create new game
objects while Unity is serializing. The fix is to always create an
instance of the VRTK Logger in the Editor.
> fix(Logger): usage when serialization runs

- Assets/VRTK/Scripts/Internal/VRTK_VRInputModule.cs
The VR Input Model was not cleaning up the pointer event data on
invalid element states, meaning if a canvas was disabled during a
UI action then the pointer event data would be incorrect and would
cause issues.
> fix(UIPointer): ensure pointer events are cleaned with invalid state - fixes #1110

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
- DOCUMENTATION.md
The Snap Drop Zone can now have multiple valid snappable objects in
the hover zone and any object that is released in the snap drop zone
will be snapped.
This fixes an issue where previously only the first valid object
that entered the snap drop zone hover space would be able to be
snapped and any other object even if it was valid would not be snapped
and would just fall on drop.
> fix(SnapDropZone): allow multiple valid objects to hover at same time - fixes #1122

- Assets/VRTK/Examples/ExampleResources/Scripts/VRTK_ControllerPointerEvents_ListenerExample.cs
- Assets/VRTK/Scripts/Pointers/VRTK_DestinationMarker.cs
- Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_DestinationMarker_UnityEvents.cs
- DOCUMENTATION.md
The destination marker now also has a hover event state that can
be used to determine if the destination marker is still hovering over
the existing target collider. This enables the Enter event to only
be emitted when the destination marker first enters the collider.
This provides a cleaner solution as Enter/Exit can now be called
only once whilst hover can be called multiple times if required.
The VRTK_Pointer has been updated to call hover if the collider
hasn't changed, and to call enter if the collider does change.
As the Enter event is no longer emitted every frame, this may cause
issues with solutions that were listening for the Enter event for
changes in the destination marker position.
This can still be achieved by calling
`SetForceHoverOnRepeatedEnter(false)` on the destination …
> feat(DestinationMarker): add hover event

- Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_DashTeleport.cs
Previously, the OnTeleporting and OnTeleported event were being emitted
at the same time in the Dash Teleporter, because the events are both
emitted when the `DoTeleport` method is called. However, as the dash
uses a co-routine to set the position, the destination location can
take a certain amount of time be reached so the OnTeleported event
needed to be emitted after that co-routine had finished.
To fix this, a collection of new overridable methods have been added
that break up the functionality of the `DoTeleport` method and allow
the Dash Teleport script to omit the OnTeleported event and then
manually emit it when required in the co-routine.
> fix(Locomotion): emit dash teleport events at the correct time

- Assets/VRTK/Scripts/Locomotion/VRTK_PlayerClimb.cs
- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
Climbing would mess with the enableBodyColliders parameter in
the body physics object. If a player set that to off, it would
override that value and never set it back. This change fixes
that problem. In addition, falling would sometimes get triggered
as being complete (velocity based) too early based on race cases
between when the FixedUpdate and fall was called. The system now
waits enough time (3 fixed updates worth) before declaring
falling to be complete.
In addition, the body physics was never reset regrabbing (with
the second controller) which put the physics system in a weird
state of having collision enabled and thinking it was in a
falling state, when it wasn't.
> fix(Climbing): reset body collision and false fall end triggers

- Assets/VRTK/Scripts/Controls/3D/VRTK_Button.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Control.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ControllerEvents.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_HeightAdjustTeleport.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_TouchpadMovement.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BezierPointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs
- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_ControllerActions_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_ControllerEvents_UnityEvents.cs
As a number of core VRTK scripts and methods have been deprecated, it
meant that existing VRTK scripts that still relied on those elements
were using deprecated items.
Usually, when something is deprecated it is replaced with a new item
that can be used in place of the old, however, with some of the
elements that have been deprecated in VRTK, this was not possible.
For example, the `Layers To Ignore` parameter has been replaced with
a more complex Custom Raycast script so a direct replacement is not
possible as it is a paradigm change in how things work. The original
`Layers To Ignore` cannot simply be removed from the internal scripts
as this would break existing behaviour (and therefore not be a valid
deprecation).
This meant that deprecation warning messages were being output to
the …
> chore(Structure): suppress internal obsolete warnings

- Assets/VRTK/Scripts/Utilities/VRTK_DeviceFinder.cs
The headset type recognition has a fixed list of known headsets.
This list is missing a special Vive Pre model that is reported as
"Vive DVT".
This fix adds that headset and modifies the recognition to also tell
the user to report any new headset type so it can be added to VRTK.
Additionally a slower check is done when a summarization is
requested to support types VRTK doesn't know about yet.
This fixes #1113.
> fix(DeviceFinder): headset type recognition

- Assets/VRTK/Scripts/Interactions/VRTK_InteractControllerAppearance.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractHaptics.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_PlayerClimb.cs
- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
- Assets/VRTK/Scripts/Presence/VRTK_HeadsetCollisionFade.cs
- DOCUMENTATION.md
Rather than have VRTK scripts simply assume another VRTK script is on
the same GameObject (or on an ancestor or descendant GameObject) it is
now possible to inject the dependent script via a public inspector
property.
This makes it easier specify which component the script should be using
rather than it always just getting the first component it finds on the
checked GameObject.
> chore(Structure): ensure vrtk components can be injected into scripts

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs
- DOCUMENTATION.md
The auto hiding of the controller tooltips is now optional via a new
inspector parameter rather than just relying on their being a
Headset Controller Aware script.
> feat(ControllerTooltips): provide option to auto hide tooltips

- Assets/VRTK/SDK/Base/SDK_BaseController.cs
- Assets/VRTK/SDK/Daydream/SDK_DaydreamController.cs
- Assets/VRTK/SDK/Fallback/SDK_FallbackController.cs
- Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs
- Assets/VRTK/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/SDK/VRTK_SDK_Bridge.cs
- Assets/VRTK/SDK/Ximmerse/SDK_XimmerseVRController.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ControllerEvents.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SharedMethods.cs
- DOCUMENTATION.md
The Controller Events script was not recognizing the thumbstick axis
changes on the Oculus Touch controllers unless the touch sensitive
pad at the top of the thumbstick was being touched.
This is because the Controller Events script would force set the
touchpad axis to not being moved if no touch of the button was
found.
This works fine on the Vive wand and is wanted as the vive wand
touchpad axis can wander and report changes in axis when it's
not being touched. But for the Oculus Touch, this additional check
is counter productive.
To fix the issue, the check to see if the touchpad is static or not
has been abstracted into the Controller SDK so each SDK can handle
how they want to determine if the touchpad axis is static or not.
The private method used for comparing the touchpad axis …
> fix(Interaction): recognize touchpad axis movement on oculus touch

- Assets/VRTK/Scripts/Presence/VRTK_PositionRewind.cs
- DOCUMENTATION.md
Previously, the Player Rewind script only used the headset collider
to determine if a collision had happened. This has now been updated
to also utilise the body physics collision to determine if a rewind
should occur.
> feat(Presence): use body colliders when determining player rewind

- Assets/VRTK/SDK/Base/SDK_BaseController.cs
Sometimes the SDK Manager's loaded setup is null so getting the
controller model hand in the base controller class was throwing
null reference exceptions. The fix is to make sure there is a loaded
setup before using it.
> fix(SDK): controller null reference exception

- Assets/VRTK/Examples/ExampleResources/Scripts/SceneChanger.cs
Since the introduction of SDK Setups using the Scene Changer
strangely forced the next loaded scene to use the wrong SDK Setup.
Sometimes a loaded scene would result in exceptions being thrown
from various Simulator classes.
The fix is to unload the currently used SDK Setup to turn off any
used SDK and force Unity to shut down any used SDK plugins.
> fix(SceneChanger): wrong SDK usage and errors

- Assets/VRTK/Examples/023_Controller_ChildOfControllerOnGrab.unity
- Assets/VRTK/Examples/027_CameraRig_TeleportByModelVillage.unity
- Assets/VRTK/Examples/031_CameraRig_HeadsetGazePointer.unity
- Assets/VRTK/Examples/032_Controller_CustomControllerModel.unity
- Assets/VRTK/Examples/034_Controls_InteractingWithUnityUI.unity
- Assets/VRTK/Scripts/Utilities/VRTK_SDKObjectAlias.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SDKObjectAlias.cs.meta
- DOCUMENTATION.md
The SDK Object Alias script will child the script's GameObject to the
selected SDK Object.
This is useful if a GameObject needs to follow the SDK headset or
play area as these can change during runtime if the SDK is switched.
All of the example scenes that used the Transform Follow have been
updated now to use this new alias script to know which object to
follow as the SDK Object is likely to change when switching SDK.
> feat(Utilities): add sdk object alias script for following SDK objects

- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs
The SDK Manager used a type from the UnityEditor namespace without
making sure it's only used in the Editor. The fix is to wrap that in
an #ifdef.
> fix(SDKManager): standalone build errors

- Assets/VRTK/Scripts/Utilities/VRTK_SharedMethods.cs
The Shared Methods script was throwing errors when compiling for a
build. The fix is to wrap that in an #ifdef correctly.
> fix(SharedMethods): standalone build errors

- Assets/VRTK/Editor/VRTK_InteractHapticsEditor.cs
- Assets/VRTK/Editor/VRTK_InteractHapticsEditor.cs.meta
- Assets/VRTK/SDK/Base/SDK_BaseController.cs
- Assets/VRTK/SDK/Daydream/SDK_DaydreamController.cs
- Assets/VRTK/SDK/Fallback/SDK_FallbackController.cs
- Assets/VRTK/SDK/Oculus/SDK_OculusController.cs
- Assets/VRTK/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/SDK/VRTK_SDK_Bridge.cs
- Assets/VRTK/SDK/Ximmerse/SDK_XimmerseController.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ControllerHaptics.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractHaptics.cs
- DOCUMENTATION.md
The audio haptics vibrate the controller based on an AudioClip
which uses the audio clip data for the pattern of the vibration.
This is useful for providing more customised vibrations.
The InteractHaptics script has been updated now to accept an
audio clip as a parameter for touch/grab/use and comes with a
custom editor to hide the default settings if a clip is provided.
An additional fix has also been added for the Oculus SDK which
was preventing the default haptic pulse from working due to
the way the OVRHapticsClip was being set up before the Oculus
SDK was available.
> feat(Controller): add audio haptics

- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKSetup.cs
Whenever the auto populate action run the changes done were not
saved. The fix is to let Unity know about the changes so it will
mark the scene as dirty.
This fixes #1187.
> fix(SDKSetup): changes because of auto populate not serializing

- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs
The SDK Manager supports Unity's standalone build command line
argument `-vrmode DEVICETYPE`. This fix makes sure `-vrmode none` is
supported in addition to the other available VR devices. If no
`-vrmode` argument is used the SDK Manager's SDK Setups list is
still used by trying one after the other in order.
> fix(SDKManager): allow `-vrmode none` to load Simulator SDK Setup

- Assets/VRTK/Scripts/Internal/VRTK_ScreenFade.cs
There was a bug where the alpha would not get set fully to 1f so
a fix was introduced to force it to 1f if the alpha was over 0.98f.
However, this created another bug where when the alpha should go from
1f to lower it would keep getting reset to 1f.
This fix checks to see if the alpha is being changed up towards the
1f value before attempting to force the alpha to 1f above 0.98f.
> fix(ScreenFade): ensure alpha does not get locked at 1f - fixes #1186

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ObjectTooltip.cs
- DOCUMENTATION.md
A new option on the Tooltip has been added that makes the tooltip
text always face the headset by rotating it accordingly.
> feat(Tooltips): add option to make text always face the headset

- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/VRTK_BasePointer.cs
- Assets/VRTK/Scripts/Pointers/VRTK_PlayAreaCursor.cs
- DOCUMENTATION.md
A new option has been added to the Play Area Cursor script that will
hide the play area cursor if the cursor location is invalid (e.g. it
does not match the policy list or a play area collision has occurred).
This is useful for only showing the play area cursor when the user
is able to move to the new destination.
> feat(Pointer): add ability to hide play area cursor on invalid location

- Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs
- DOCUMENTATION.md
There was an issue that if a secondary grab mechanic was set then it
was still possible to grab an object even if the `isGrabbable` option
was set to false.
This was due to the `PerformSecondaryAction` method would not take
into consideration if a primary grab had already occurred. The fix
is to check if a primary grab has occurred in that method.
> fix(Interaction): prevent secondary grab when isGrabbable is false

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
- DOCUMENTATION.md
Two new methods have been added to get the current hovered objects
and the current snapped object from within a snap drop zone.
Previously, the only way of knowing what was in a snap drop zone was
to register for the event when an item was hovered or snapped into
the zone.
Now these two new methods provide a way of directly accessing the
info on the snap drop zone without needing to use the event.
> feat(SnapDropZone): add getter method for drop zone object

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs
- DOCUMENTATION.md
The initialisation retry attempts of the Controller Tooltips can now
be customised via the inspector parameters rather than being hidden
variables.
This is useful if they need further tweaking, or no auto initialisation
is required and then they can be disabled.
Sometimes controllers take longer to initialise so it's now possible
to increase the retry attempts to ensure initialisation of the
tooltips still works.
> fix(Tooltips): make retry init variables public - fixes #1202

- Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs
Using a head tracked pointer, for gazing, the enter / exit events were not triggering due to a dependence on a valid controller reference.
> fix(Pointer): trigger enter/exit events when controller not required

- Assets/VRTK/SDK/Simulator/SDK_ControllerSim.cs
- Assets/VRTK/SDK/Simulator/SDK_SimHeadset.cs
Fix the calculation for angular velocity, now decently correct.
Tweak calculation of velocity to use fewer samples.
> fix(simulator): fix angular and velocity calculations

- Assets/VRTK/Editor/VRTK_SDKManagerEditor.cs
The SDK Manager editor is changed to explain the load and unload
buttons for the SDK Setups via the button tooltips.
> chore(SDKManager): add SDK Setup load and unload button tooltips

- Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs
- DOCUMENTATION.md
The `ForceTeleport` method now also has an optional
`forceDestinationPosition` option to ensure the actual provided
location is used when forcing the new teleport location.
> feat(Locomotion): allow force destination in force teleport method

- Assets/VRTK/Examples/ExampleResources/Scripts/Archery/ArrowNotch.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/FireExtinguisher_Sprayer.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/LightSaber.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/RealGun.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/SnapDropZoneGroup_Switcher.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ConsoleViewer.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ObjectTooltip.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
- Assets/VRTK/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/SDK/Simulator/SDK_SimHeadset.cs
- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
- Assets/VRTK/Scripts/UI/VRTK_UICanvas.cs
Transform.FindChild() is no longer part of the documentation,
but still exists as part of the UnityEngine assembly.
It is depricated and is functionally identical to Transform.Find().
> refactor(Structure): replace FindChild with Find

- Assets/VRTK/Scripts/Locomotion/VRTK_HeightAdjustTeleport.cs
- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
- Assets/VRTK/Scripts/Presence/VRTK_HeadsetControllerAware.cs
- Assets/VRTK/Scripts/Utilities/VRTK_CustomRaycast.cs
- DOCUMENTATION.md
The various casts done by scripts such as Body Physics, teleporters
and the pointers were all colliding with trigger colliders by default.
The CustomRaycast script has now been updated so it can be called
and informed to ignore trigger colliders without providing an
instantiated CustomRaycast object.
Body Physics and the teleporters now ignore trigger colliders by
default, whereas the pointers still interact with trigger colliders
by default because the UI Canvas generates a trigger collider.
If the pointer is required to pass through a trigger collider then
the object should be put on the Ignore Raycasts layer.
> fix(Utilities): allow for trigger colliders to be ignored by casts - fixes #1230

- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs
The VRTK scripts that register with the SDK Manager were always
being set to enabled even if the script was set to disabled in the
editor.
This fix stores the state of the registered script and then sets it
back to that original state when the SDK Manager runs through the
behaviours registered with it. This means the enabled state of the
scripts are now remembered and set appropriately.
> fix(SDKManager): honour script enable states - fixes #1216

- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
- Assets/VRTK/Scripts/Presence/VRTK_HeadsetCollision.cs
- Assets/VRTK/Scripts/Presence/VRTK_PositionRewind.cs
- DOCUMENTATION.md
The Headset Collision script now has a new parameter to allow it to
ignore colliding with Trigger colliders.
This option is also now in the Position Rewind to allow the rewind
to be ignored when colliding with a trigger collider (but the headset
collision could still fade the headset on trigger collision if that was
required).
> feat(Presence): option to ignore trigger colliders for head collisions

- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SharedMethods.cs
- DOCUMENTATION.md
The pointer object interactor that becomes an extension of the
controller but tracks the scale of the actual pointer cursor.
This would cause an issue when the camera rig was scaled, the
object interactor would change size along with the camera rig
and no longer match the scale of the pointer cursor.
This fix uses the global scale of the pointer cursor to set the
global scale of the object interactor so the scales continue
to match even when the camera rig is scaled.
> fix(Pointers): ensure object interactor is set by global scale - fixes #1162

- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
- DOCUMENTATION.md
It's now possible to provide a custom body collider container and
a custom foot collider container for the Body Physics script.
The containers need to include a capsule collider (no other collider
is allowed). If a capsule collider isn't present on the custom
GameObject then one will be auto generated.
> feat(Presence): allow custom body/feed colliders for body physics

- Assets/VRTK/Scripts/Locomotion/ObjectControlActions/VRTK_BaseObjectControlAction.cs
- Assets/VRTK/Scripts/Locomotion/ObjectControlActions/VRTK_SlideObjectControlAction.cs
- Assets/VRTK/Scripts/Locomotion/ObjectControlActions/VRTK_SnapRotateObjectControlAction.cs
- Assets/VRTK/Scripts/Locomotion/ObjectControlActions/VRTK_WarpObjectControlAction.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_MoveInPlace.cs
- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
- Assets/VRTK/Scripts/Utilities/VRTK_CustomRaycast.cs
- DOCUMENTATION.md
The Body Physics script now has a new method `SweepCollision` that
can be used to determine if the body physics body collider will
collide with an object if it continues to move in a given direction
for a given distance.
This new method is now used in some of the Locomotion methods that
move the play area via `transform.position` and can now check
if they are provided with a Body Physics script if when they move
forward, will the new position cause collision tunnelling and if
it does then the movement can be denied meaning tunnelling is not
possible.
> feat(Presence): provide collision sweep detection for body physics - fixes #1259

- Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractUse.cs
The Interact Touch/Grab/Use script had a number of areas where it
was possible to create a null reference exception because a script
would be called but could be null.
The fix is to do null checks before any methods or variables are
called on these dependent scripts.
> fix(Interactions): prevent null reference exceptions - fixes #1274

- Assets/VRTK/Examples/ExampleResources/Scripts/Controller_Menu.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/FireExtinguisher_Base.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/Gun.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/Lamp.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/LightSaber.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/Menu_Color_Changer.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/Menu_Object_Spawner.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/Openable_Door.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/RealGun.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/RealGun_SafetySwitch.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/Sword.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/UseRotate.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/Whirlygig.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractUse.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs
- Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs
- DOCUMENTATION.md
The Interactable Object script would previously accept a GameObject
when the Touching/Grabbing/Using methods were called. However, this
was ambiguous as to what the object should represent. The object
that is performing the action should be the one with the relevant
VRTK_InteractX script on like VRTK_InteractTouch, VRTK_InteractGrab
and VRTK_InteractUse.
Because of this, it makes more sense to actually pass the reference
to the script as the GameObject can be obtained from the script
with less overhead than the script being obtained from the GameObject
via the `GetComponent` method call.
The existing methods that accept a GameObject still exist but have
been deprecated in favour of the new methods that take the specific
InteractX script.
> fix(Interactions): pass relevant VRTK_InteractX to interactable object - fixes #1261

- Assets/VRTK/Prefabs/DestinationPoint.prefab
The DestinationPoint prefab had a typo in the Locked Cursor child
GameObject.
> fix(Locomotion): typo in destination point locked cursor game object

- Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/VRTK_BasePointer.cs
- Assets/VRTK/Scripts/Pointers/VRTK_DestinationMarker.cs
- Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs
- Assets/VRTK/Scripts/Utilities/VRTK_PolicyList.cs
- DOCUMENTATION.md
The DestinationMarker script had a hidden policy list that the
teleporter would use to determine when to set a pointer to the valid
or invalid colour. However, it wasn't possible to just change the
pointer state based on simply what the pointer was looking at.
This change exposes the hidden policy list variable on the destination
marker and makes it a public parameter that can be updated in the
Unity inspector.
If the pointer has a policy list assigned then it won't get assigned
one by the teleporter, this is useful for overriding the teleport
policy list setting.
> feat(Pointers): expose policy list as public on destination marker

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
- DOCUMENTATION.md
A new setting on the snap drop zone allows to clone the snapped
object when it is unsnapped allowing spawning new objects of
the current snapped object.
> feat(SnapDropZone): allow cloning snapped object on unsnap - fixes #1260

- Assets/VRTK/SDK/SteamVR/SDK_SteamVRBoundaries.cs
The `SteamVR_UpdatePoses` script was added on Unity 5.6 and newer, but
it's no longer needed to do that in Unity 2017.1.
> fix(SteamVR): only add SteamVR_UpdatePoses for Unity 5.6

- Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs
The UIPointer `Toggle` method now exits early if the toggle state
that is passed to the method is already in that state.
e.g. If `Toggle(true)` is called but the pointer is already active
then the Toggle method will exit early.
> fix(UIPointer): ensure toggle does not execute if on existing state

- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_BaseJointGrabAttach.cs
Currently if joint on an object other than the gripping joint breaks, the grip is released. This shouldn't happen.
The grip should only be released if the gripping joint breaks. This change band-aids this issue. It should actually check that the grip joint generated the OnJointBreak, but I see no way of doing this.
> fix(Gripping): Grip release on non-grip joint break. - fixes #1269

- Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs
- up to now, a VRTK_InteractableObject is disabled when it's neither
used nor touched nor grabbed
- however, there may be interactable objects which require more
complex conditions, e.g. a throwable interactable object which
needs to stay enabled until it is no longer moving
- this commit introduces an overridable `IsIdle()` function which
can be overriden by derived interactable objects
> feat(Interaction): allow custom idle checks on Interactable Objects

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_FramesPerSecondViewer.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SDKObjectAlias.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SDKTransformModify.cs
A number of scripts that utilise the `LoadedSetupChanged` event on
the SDKManager were set up so that if they were on a GameObject that
was a child of the current SDK camera rig then when the SDK was
changed, the camera rig would become disabled and the script listening
to the setup change event would then also have the `OnDisable` method
called and unregister the listener. This would mean that the script
would no longer be listening for the switch in SDK and any
functionality required on SDK switch would no longer be available.
For instance, the SDK Object Alias script would not re-child the
relevant object because the SDK change would not be observed as the
listener had been unregistered.
This is fixed by checking in the `OnDisable` method of the script
to see if the actual GameObject …
> fix(Utilities): prevent sdk change event unregistering on disable

- Assets/VRTK/Scripts/Locomotion/ObjectControlActions/VRTK_SnapRotateObjectControlAction.cs
- Assets/VRTK/Scripts/Locomotion/ObjectControlActions/VRTK_WarpObjectControlAction.cs
The SnapRotate and WarpObject control actions both used
`Time.timeSinceLevelLoad` to manage the action delay, however this
would cause an issue when switching scene as the time would no longer
be correct when calculating the delay.
The fix is simply to use `Time.time` to determine when the delay has
subsided.
> fix(Locomotion): replace `timeSinceLevelLoad` to prevent stuck timer - fixes #1300

- Assets/VRTK/Scripts/Utilities/VRTK_DeviceFinder.cs
The DeviceFinder script has a method for determining which headset is
being used. However, there seemed to be an issue where newer HTC Vives
would report their name as `Vive MV.` with a dot at the end rather than
the standard `Vive MV` which was reported by the original HTC Vive
consumer edition.
This fix just checks both values and assumes the headset is `ViveMV`
to prevent users with newer Vive headsets receiving a warning.
> fix(Utilities): new vive keyword for headset discovery in device finder

- Assets/VRTK/Scripts/Utilities/VRTK_DeviceFinder.cs
feat(Utilities): simplify headset checking in device finder
The `GetHeadsetType` method in the DeviceFinder script has now been
simplified to parse the current headset string and process it by
removing any spaces and full stops `.` so a pure string can be
compared.
This processing of the VR device string is then cached so further
processing is not required.
A new method has been added that resets the headset cache if for
some reason the headset type changes at runtime then the cache can
be reset so it is re-parsed and re-processed.
> feat(Utilities): simplify headset checking in device finder

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DestinationPoint.cs
There was an issue with the DestinationPoint script where the
`currentDestinationPoint` which is a static variable was being reset
to null whenever the destination point was set or the pointer exited
the destination point area.
This was not apparent when the pointer activation button and selection
button was the same button because of the speed in which the events
would be triggered.
However, if the activation and selection buttons were different then
the `currentDestinationPoint` would be set to null and this would
reactivate the actual current destination point even though it should
be disabled.
The fix is to ensure the `currentDestinationPoint` is never set to
null and is used for a simple check when resetting the Destination
Point.
> fix(Locomotion): prevent current destination point being set to null - fixes #1307

- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
The BodyPhysics script was doing a `GetComponent` call every
`FixedUpdate` when checking to see if the snap to floor was valid
by checking to see if the object being held was underneath the
headset.
The fix attempts to cache the check the first time around to reduce
any further unnecessary calls to `GetComponent` if the held object
has not changed.
> fix(Presence): reduce GetComponent calls in body physics update

- Assets/VRTK/Examples/ExampleResources/Scripts/SceneChanger.cs
- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs
- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKSetupSwitcher.cs
Whenever the scene changed it was recommended to unload the
currently loaded SDK Setup via the SDK Manager. This lead to issues
with coming up with the exact time to call the unload method,
especially when using `SteamVR_LoadLevel`. That SteamVR script even
lead to crashes.
This fix stops unloading the currently used VR Device everywhere.
The result is that **there is no need to call the unload method
manually anymore**.
The SceneChanger script was simplified a bit after being updated for
this fix.
---
The SDK Manager now tries to use the same SDK Setup that was used
previously (even when it was used in another scene).
> fix/feat: SDK Setup load/unload on scene changes

- Assets/VRTK/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_DashTeleport.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_HeightAdjustTeleport.cs
- DOCUMENTATION.md
The `ForceTeleport` method has now been renamed to `Teleport` and a
new `ForceTeleport` method has been added that simply takes a
position and a rotation and sets the player location to those given
parameters.
> feat(Locomotion): rename force teleport to teleport and add new method

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs
There was an issue if the `hideWhenNotInView` option was active but
no `headsetControllerAware` script was set then the tooltips could
never become active.
This fix just checks to see if `headsetControllerAware` is set and if
it's not then it always activates the tooltips.
> fix(ControllerTooptips): enable tips if no HeadsetAware script is found

- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKSetupSwitcher.cs
The SDK Setup Switcher sometimes didn't recognize the current camera
of the loaded SDK Setup. The fix is to actually ask the SDK Setup
for the camera (via the Device Finder) instead of relying on
`Camera.main` being set.
> fix(SDKSetupSwitcher): recognize SDKSetup camera

- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs
The SDK Manager offers to remember any Behaviour to automatically
toggle it off and on based on whether an SDK Setup is loaded to
remove the need to listen to the SDK Setup Loaded event manually.
When users forget to call the remove method the SDK Manager will
throw a null reference exception which doesn't offer the user enough
info.
This fix handles that case and logs an error in addition to removing
the bad Behaviours.
---
Thanks for @trumpetx for the idea and example implementation.
> fix(SDKManager): handle null Behaviour

- Assets/VRTK/Prefabs/DesktopCamera.prefab
- Assets/VRTK/Prefabs/DesktopCamera.prefab.meta
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DesktopCamera.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DesktopCamera.cs.meta
There's a need to show something different on the desktop window
than what's shown in the VR headset. The potential use cases range
from offering nicer spectator views to showing completely different
views for asymmetrical games.
In combination with VRTK's existing ObjectFollow scripts this allows
for trailer recordings in which the VR headset's movement is
smoothed.
Having a separated desktop-only camera allows for:
- additional overlays or effects
- render other layers in addition/only
- changing the FOV
- ...
This change adds the new `VRTK_DesktopCamera` script and a
corresponding prefab that shows how to use the optional support for
rendering the headset's view in addition to the desktop-only view.
> feat(DesktopCamera): render desktop-only camera while in VR

- Assets/VRTK/Editor/VRTK_EditorUtilities.cs
- Assets/VRTK/Editor/VRTK_NavMeshDataEditor.cs
- Assets/VRTK/Editor/VRTK_NavMeshDataEditor.cs.meta
- Assets/VRTK/Examples/033_CameraRig_TeleportingInNavMesh.unity
- Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/VRTK_DestinationMarker.cs
- Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs
- Assets/VRTK/Scripts/Utilities/VRTK_NavMeshData.cs
- Assets/VRTK/Scripts/Utilities/VRTK_NavMeshData.cs.meta
- DOCUMENTATION.md
The Teleporter scripts now can take a new NavMeshData object which
provides a finer level of customisation over nav mesh limits when
teleporting.
This new NavMeshData object supersedes the previous
`navMeshDistanceLimit` setting which has now been deprecated.
The NavMeshData object contains the ability to set the nav mesh
distance limit but also to allow picking valid Nav Mesh Layers
when determining a valid location.
> feat(Locomotion): allow finer customisation of nav mesh limits

- Assets/VRTK/Scripts/Pointers/VRTK_DestinationMarker.cs
A previous merge removed the System library but than a subsequent
merge required it for the `Obsolete` tag.
These cross merges meant there was an error left in the script.
> chore(Pointer): add system library to allow obsolete tag

- Assets/VRTK/SDK/Oculus/SDK_OculusDefines.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRBoundaries.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRDefines.cs
The new release of SteamVR fixed issues VRTK worked around
previously. These workarounds are now wrapped in an #ifdef to
support the new version while maintaining support for the previous
ones.
Additionally the version lookup on both the SteamVR and Oculus SDK
are simplified.
> fix(SDK): support SteamVR plugin 1.2.2

- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs
- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKSetup.cs
When using the persist on load setting on the SDK Manager it is
moved to the `DontDestroyOnLoad` scene at runtime by Unity. That
scene is inaccessible which means there's no way to find objects in
that scene. Because of the issues related to looking up objects in
the inaccessible scene the persist on load setting on the SDK
Manager is now deprecated.
It's recommended to use additive scene loading instead. To reduce
the likelihood of these issues breaking the project for users
already using the setting this fix also makes sure to only populate
the SDK Setup object references when this setting is *not* checked.
> fix(SDKManager): deprecate persist on load setting - fixes #1316

- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
There was an issue with the Body Physics body collider being sized
incorrectly in the simulator because the calculation was relying
on local positions and the simulator has a more complex set up
with the new neck object.
This fix uses global positions and is more generic to provide a
better future proof solution.
Thanks to @virror for the fix.
> fix(Presence): calculate collider height based on global positions - fixes #1325

- Assets/VRTK/SDK/SteamVR/SDK_SteamVRDefines.cs
The SteamVR scripting define symbols were defined based on
`SteamVR_Update.currentVersion`, but that type is only available in
the Editor assembly, which is not included in builds. The fix is to
revert back to the old method of identifying the used SteamVR plugin
version and to add new identification logic for the SteamVR plugin
version 1.2.2.
> fix(SDK): SteamVR SDK Setup unusable in build

- Assets/VRTK/Editor/VRTK_EditorUtilities.cs
- Assets/VRTK/Editor/VRTK_UpdatePrompt.cs
Long changelogs resulted in Unity logging an error. The fix is to
add pagination to the changelog so less text is rendered at one
point.
Additionally the changelog is updated to follow the markdown look a
bit more.
> fix(UpdatePrompt): long changelog error

- Assets/VRTK/Editor/VRTK_UpdatePrompt.cs
The Update Prompt unnecessarily added another page even if the
remaining changelog text fits in the last page. The fix is to only
try to find and break at the last newline in case a new page is
actually needed.
> fix(UpdatePrompt): unnecessary pagination

- Assets/VRTK/Examples/ExampleResources/Scripts/VRTK_ControllerAppearance_Example.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/VRTK_ControllerEvents_ListenerExample.cs
- Assets/VRTK/Prefabs/Resources/ControllerColliders/Simulator.prefab
- Assets/VRTK/Prefabs/Resources/ControllerColliders/SteamVROculusTouch_Right.prefab
- Assets/VRTK/Prefabs/Resources/ControllerColliders/ValveKnuckles_Left.prefab
- Assets/VRTK/Prefabs/Resources/ControllerColliders/ValveKnuckles_Left.prefab.meta
- Assets/VRTK/Prefabs/Resources/ControllerColliders/ValveKnuckles_Right.prefab
- Assets/VRTK/Prefabs/Resources/ControllerColliders/ValveKnuckles_Right.prefab.meta
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs
- Assets/VRTK/SDK/Base/SDK_BaseController.cs
- Assets/VRTK/SDK/Daydream/SDK_DaydreamController.cs
- Assets/VRTK/SDK/Fallback/SDK_FallbackController.cs
- Assets/VRTK/SDK/Oculus/SDK_OculusController.cs
- Assets/VRTK/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/SDK/VRTK_SDK_Bridge.cs
- Assets/VRTK/SDK/Ximmerse/SDK_XimmerseController.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ControllerEvents.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ControllerHighlighter.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs
- DOCUMENTATION.md
The new Valve knuckle controllers contain cap sense buttons for
all fingers, so a new `SenseAxis` concept has been added to VRTK
that allows to check the intensity that a cap sense sensor is
being affected between `0f` and `1f`.
The Oculus Touch also supports limited cap sense buttons too so
the Oculus NearTouch concept is also supported through this new
`SenseAxis` concept.
The Valve knuckle controllers are also now supported as a means
of testing and proving the new `SenseAxis` concept works.
> feat(SDK): add sense axis for capacitive touch buttons

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DestinationPoint.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_DashTeleport.cs
- DOCUMENTATION.md
There was an issue with Dash Teleporting to a Destination Point
where the Destination Point would attempt to reseat the final
position to the Destination Point destination location but this
was happening too fast before the Dash Teleport had chance to
finish lerping to it's final destination.
The solution is to create a new way of overriding the final destination
of the teleport before the teleport event has triggered and then this
override is called from the destination point when the destination
marker events occur.
This now allows the destination point to only need one teleport event
as it tells the teleporter the actual destination rather than just
using the destination the pointer gave it.
The dash teleport also lerps the rotation of the teleport now as well
rather than just snapping …
> fix(Locomotion): correct teleport to destination point with dash

- Assets/VRTK/Examples/ExampleResources/Scripts/VRTK_ControllerAppearance_Example.cs
There was an unused variable introduced in the previous capsense
axis commit. The fix is to remove said variable.
> fix(Examples): remove unused variable to resolve warning

- Assets/VRTK/Scripts/Locomotion/VRTK_HeightAdjustTeleport.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BezierPointerRenderer.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs
- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
- Assets/VRTK/Scripts/Presence/VRTK_HeadsetControllerAware.cs
There was an issue where the CustomRaycast default raycast layer mask
was set to a blank LayerMask which meant all raycasts that were not
custom were not ignoring the default `Ignore Raycasts` layer.
This caused a number of issues such as pointers colliding with the
pointer cursor collider as it was set to the ignore raycast layer
but the raycast from the pointer wasn't being set to ignore
raycasts.
The fix is to ensure the default LayerMask is set to the
`Physics.IgnoreRaycastLayer`.
> fix(CustomRaycast): set default raycast layer mask to correct setting

- Assets/VRTK/Examples/ExampleResources/Scripts/FireExtinguisher_Base.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/LightSaber.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/UseRotate.cs
- Assets/VRTK/Examples/ExampleResources/Scripts/Whirlygig.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractUse.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs
- DOCUMENTATION.md
The Interact Use script was emitting two unuse events because the
Interact Use script calls StopUsing on the Interactable Object and
the Interactable Object script calls ForceResetUsing on the
Interact Use script, which would then in turn emit the unuse event
before the original StopUsing routine had finished. This would
result in two unuse events being emitted.
The fix for this is to add another check into the Interactable Object
StopUsing method that can be used to bypass the ForceResetUsing call
as it's not needed to reset the Interact Use object if the StopUsing
on the Interact Use has been called as it will already reset the state
anyway.
> fix(Interaction): prevent double unuse event

- Assets/VRTK/Scripts/Locomotion/ObjectControlActions/VRTK_BaseObjectControlAction.cs
- Assets/VRTK/Scripts/Locomotion/ObjectControlActions/VRTK_SlideObjectControlAction.cs
- Assets/VRTK/Scripts/Locomotion/ObjectControlActions/VRTK_WarpObjectControlAction.cs
The ObjectControlAction scripts were not always getting the correct
BodyPhysics collider if no BodyPhysics was available as they were
just looking for the child CapsuleCollider and this could exist
in any of the CameraRig children such as on the Controller Objects.
This fix ensures it uses the BodyPhysics script and get the body
collider to use in the ObjectControlAction scripts.
> fix(Locomotion): get correct body physics collider in object control - fixes #1357

- Assets/VRTK/Editor/VRTK_SDKSetupEditor.cs
- Assets/VRTK/Examples/ExampleResources/Prefabs/SDKSetups.prefab
- Assets/VRTK/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs
- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKSetupSwitcher.cs
Supporting multiple SDKs means VRTK had to disable all the SDK 
Setups that are used automatically to ensure they're usable for
runtime switching. This change allows to completely bypass the
runtime loading and that requirement in case only one SDK Setup is
used. This means users of VRTK don't have to bother with handling
when an SDK Setup is loaded and usable, nor do they have to
re-enable their SDK Setups game objects again to work on them in the
editor while they're visible.
> feat(SDKManager): simplify single SDK Setup configurations

- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
The object interactor renderer was not having the scale set on it
but instead it was the whole transform of the script being rescaled
which was incorrect.
> fix(Pointer): set object interactor scale correctly on renderer - fixes #1362

- Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs
If the rotation is set after the new teleport position
is set then the final position of the user is in the wrong
position especially if the headset compensation is on.
The fix is to ensure rotation is done before any new location
position is determined.
> fix(Locomotion): set rotation before teleport - fixes #1291

- Assets/VRTK/SDK/Oculus/SDK_OculusBoundaries.cs
- Assets/VRTK/SDK/Oculus/SDK_OculusController.cs
- Assets/VRTK/SDK/Oculus/SDK_OculusDefines.cs
- Assets/VRTK/SDK/Oculus/SDK_OculusHeadset.cs
- Assets/VRTK/SDK/Oculus/SDK_OculusSystem.cs
The Oculus SDK has been updated to also support the Android build
platform. This means that building with the Oculus SDK will allow
to be deployed on Android for GearVR.
> feat(SDK): allow Android support for Oculus SDK

- Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs
The ForceTeleport method within the Teleport script was not
applying the headset compensation upon teleport. This fix ensures
the headset compensation code is applied accordingly.
> fix(Locomotion): apply headset compensation to force teleport

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs
To prevent any unwanted null reference exceptions, the arrays in
the controller tooltips have been initialised to a default size
so if they're called before the init code is run then they at
least will be valid empty arrays.
> refactor(ControllerTooltips): initialise arrays in declaration

- Assets/VRTK/SDK/Oculus/SDK_OculusController.cs
The Oculus controller SDK was returning the same controller type for
both button presses, meaning the left controller (or index 0) was
initiating button presses on both controllers.
This has been fixed now by also checking for the generic `Touch`
controller type and using the given index to determine which
touch controller is being used.
> fix(SDK): ensure oculus touch uses correct controller for button press

- Assets/VRTK/Scripts/Pointers/VRTK_PlayAreaCursor.cs
The Play Area Cursor was considering a collision with a trigger
collider an actual collision therefore teleporting into trigger
colliders was not possible.
This fix ensures that colliders that are set to trigger are no
longer considered a valid collision target.
> fix(Pointer): ignore trigger colliders with play area cursor

- Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs
The SDK Manager never fell back to the Simulator SDK Setup after the
recent changes to allow for single SDK Setup configurations. The fix
is to update a check that previously relied on the fact that a
variable was null or an empty string, but is now always set.
> fix(SDKManager): fall back to Simulator SDK Setup

- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
The Body Phsyics script was incorrectly detecting collisions within
the `SweepCollision` method if the play area was rotated.
This fix ensures to take the rotation into consideration when emitting
the collision sweep ray.
Thanks to @Michaelwolf95 for the fix.
> fix(Presence): account for play area rotation in collision sweep - fixes #1395

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
The SnapDropZone script would continually call `GetComponent` in the
`Update` method as well as in the `OnTriggerStay` method to attempt
to get the Interactable Object component of the snappable GameObject.
This was an inefficient call and has been replaced with a cached
version of the interactable object to ensure the inefficient
`GetComponent` call is removed from the `Update` and `OnTriggerStay`
methods.
> refactor(SnapDropZone): reduce GetComponent calls in update

- Assets/VRTK/Scripts/Controls/3D/VRTK_Drawer.cs
The Drawer 3D Control would not deal with the snap force correctly
if the drawer was rotated and it would apply the snap force in the
wrong direction causing the drawer to push open on it's own.
Thanks to @RobCob for the fix.
> fix(Controls): ensure drawer snap force handles rotation correctly - fixes #1397

- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs
There was an issue with the Straight Pointer Renderer with GearVR
and the Simulator where it would lag behind the controller due to
how the position of the pointer tracer was being updated to always
match the smoothing object position, which was in turn being matched
to the actual controller position with TransformFollow.
The solution is simply childing the pointer container to the
smoothing Game Object so it doesn't need the secondary update which
causes the lag.
> fix(Pointer): child straight pointer renderer to smoothing object - fixes #1394

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_PointerDirectionIndicator.cs
- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- DOCUMENTATION.md
A new option has been added to the Pointer Direction Indicator
so it can always be visible when the pointer cursor is visible.
This allows for the `Always On` setting for the cursor on the
pointer renderer to always determine if the direction indicator
is also on.
Even if the `Always Off` setting is on for the cursor then the
pointer direction indicator will still become visible when
the pointer is activated.
> feat(Pointer): allow direction indicator to be visible with cursor

- Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs
- DOCUMENTATION.md
The Interactable Object has a new method that can be called to see
if the object is currently being hovered over a snap drop zone.
> feat(Interaction): determine if object is hovered over snap drop zone

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_AvatarHandController.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs
- Assets/VRTK/SDK/Base/SDK_BaseController.cs
- Assets/VRTK/SDK/Daydream/SDK_DaydreamController.cs
- Assets/VRTK/SDK/Fallback/SDK_FallbackController.cs
- Assets/VRTK/SDK/Oculus/SDK_OculusController.cs
- Assets/VRTK/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/SDK/VRTK_SDK_Bridge.cs
- Assets/VRTK/SDK/Ximmerse/SDK_XimmerseController.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ControllerEvents.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ControllerHighlighter.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs
- Assets/VRTK/Scripts/Internal/VRTK_TrackedController.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_ControllerEvents_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/VRTK_DeviceFinder.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SDKTransformModify.cs
- DOCUMENTATION.md
The Controller Model is now emitted via a new event on the
TrackedController script (which is also re-thrown by the
ControllerEvents script). This event is emitted when the model
of the connected controller is loaded in.
Previously, a number of scripts would duplicate the same coroutine
for determining when the controller model was available. This new
event removes the need for this duplication as these scripts can just
listen for this event.
The `GetCurrentControllerType` method now accepts a ControllerReference
to determine specific connected controller type. If `null` is passed
then it will attempt to get the right controller first then the left
if the right is not available.
> feat(Interaction): emit event when controller model is available

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_FramesPerSecondViewer.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SDKObjectAlias.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SDKTransformModify.cs
There was an issue with the `LoadedSetupChanged` method that it
would attempt to access objects or destroy objects when the SDK
was finally unloaded because the object in question had already
been destroyed (e.g. when ending the scene).
This fix just ensures the sdk setup changes only call their intended
methods if the game object the script is on is still active in the
hierarchy.
> fix(Utilities): prevent crash when switching sdk setup

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
There was an issue withe the Highlight Always Active option where it
could be turned on at scene run, but then if it was turned off during
play it would not turn off the highlighter even though the state of
the option would dictate otherwise.
The fix is to ensure the `isHighlighted` flag is always correctly
set and an additional check is done to make sure to turn the
highlighter off if it shouldn't be on due to this option being false.
> fix(SnapDropZone): ensure highlight always active option is honoured - fixes #1421

- Assets/VRTK/Scripts/Utilities/VRTK_Simulator.cs
- Assets/VRTK/Scripts/Utilities/VRTK_Simulator.cs.meta
- DOCUMENTATION.md
The VRTK Simulator has been superseded by the VRTK SDK Simulator which
simulates the entire SDK setup rather than just enabling the camera rig
to move around with key presses.
This means there is little reason to keep this old simulator.
> feat(Simulator): deprecate VRTK Simulator

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ConsoleViewer.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_RadialMenu.cs
Update some scripts that were not adhering to the coding conventions
such as using the `var` keyword or using `private` variables and
methods.
> refactor(Structure): apply coding conventions

- Assets/VRTK/SDK/Daydream/SDK_DaydreamSystem.cs
- Assets/VRTK/SDK/HyperealVR/SDK_HyperealVRSystem.cs
- Assets/VRTK/SDK/Oculus/SDK_OculusSystem.cs
- Assets/VRTK/SDK/Simulator/SDK_SimSystem.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRSystem.cs
- Assets/VRTK/SDK/Ximmerse/SDK_XimmerseSystem.cs
The pretty names for each SDK platform and build target has been
updated to include the library and build target to make it easier
to see which SDK option is for which output device.
> chore(SDK): provide more meaningful SDK pretty names

- Assets/VRTK/Examples/ExampleResources/Scripts/Archery/BowAim.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DestinationPoint.cs
- Assets/VRTK/SDK/Base/SDK_BaseController.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Slider.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractUse.cs
- Assets/VRTK/Scripts/Internal/VRTK_ControllerReference.cs
- Assets/VRTK/Scripts/Internal/VRTK_VRInputModule.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_MoveInPlace.cs
- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
Unity3d creates garbage when dealing with `Equals` as it's considered
a Boxing method and therefore is less efficient than simply comparing
with `==`
This information can be found at:
https://unity3d.com/learn/tutorials/topics/performance-optimization/optimizing-garbage-collection-unity-games
This refactor replaces all of the occurrences of `Equals` with `==`
to provide the efficiency improvements.
The MoveInPlace script has also been slightly refactored to use a
`switch` statement rather than a collection of `if/else` statements
that all in turn used the `Equals` method as well.
> refactor(Structure): replace occurrences of Equals with ==

- Assets/VRTK/Scripts/Utilities/VRTK_VelocityEstimator.cs
The Velocity Estimator was using world space to determine the samples
for velocity and angular velocity, which would cause problems if the
Velocity Estimator was attached to a GameObject that's parent was
rotated.
It could be seen in the Unity SDK by simply rotating the CameraRig
around the Y axis and then the throwing mechanism would throw
things in the wrong direction.
The solution is to simply use local space for position and rotation
as then the actual object the Velocity Estimator is attached to
will be used for the relative position and rotation.
> fix(Utilities): use local space for velocity estimation samples - fixes #1440

- CONTRIBUTING.md
- README.md
The new branch structure for the project requires pull requests
to go into a specific branch. The README.md file didn't reflect these
new requirements, but do now with this commit.
> chore(README.md): update contribution instructions for new branches

- Assets/VRTK/Examples/008_Controller_UsingAGrabbedObject.unity
- Assets/VRTK/Examples/014_Controller_SnappingObjectsOnGrab.unity
- Assets/VRTK/Examples/016_Controller_HapticRumble.unity
- Assets/VRTK/Examples/021_Controller_GrabbingObjectsWithJoints.unity
- Assets/VRTK/Examples/023_Controller_ChildOfControllerOnGrab.unity
- Assets/VRTK/Examples/026_Controller_ForceHoldObject.unity
- Assets/VRTK/Examples/032_Controller_CustomControllerModel.unity
- Assets/VRTK/Examples/ExampleResources/Prefabs/BasicArrow.prefab
- Assets/VRTK/Scripts/Interactions/VRTK_InteractControllerAppearance.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractControllerAppearance.cs.meta
- Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractObjectAppearance.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractObjectAppearance.cs.meta
- Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractUse.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractableObject.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ObjectAppearance.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractControllerAppearance_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractObjectAppearance_UnityEvents.cs
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractObjectAppearance_UnityEvents.cs.meta
- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractableObject_UnityEvents.cs
- DOCUMENTATION.md
The Interact Object Appearance script is used to determine the
appearance of a given object when an interactable object is interacted
with (touch/grab/use). It's possible to determine the state of the
object's renderer or even game object on any of the interaction states.
This script supersedes the functionality of the Interact Controller
Appearance script as this Interact Object Appearance script can be
used to hide the controller on interaction. This means the
Interact Controller Appearance script has been deprecated and all
of the example scenes that used it have been updated to use the new
Interact Object Appearance script.
> feat(Interaction): add interact object appearance script

- Assets/VRTK/SDK/Unity/SDK_UnityController.cs
The left mouse button now determines a right controller trigger press
and the right mouse button determines a right controller grip press.
This can be useful for developing on Google Cardboard as the Cardboard
input button is considered to be a left mouse button click.
> feat(SDK): support mouse button in Unity SDK

- Assets/VRTK/Scripts/Interactions/VRTK_InteractObjectAppearance.cs
The Interact Object Appearance script was throwing an error if the
co routine to determine the appearance was being run but the script
GameObject had been disabled (e.g. when the play mode was stopped).
This has been fixed by checking that the GameObject is active in
the hierarchy to determine if it's a valid interaction.
> fix(Interaction): prevent coroutine running if game object is disabled

- Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs
The Secondary Grab Action was checking to see if the controller was a
valid grab controller on the interactable object.
This did not make sense as if the right controller was a valid grab
controller then only the right controller could pick up the object
but then the left controller could never initiate a secondary grab
action as the right controller was the only one denoted as being
valid to initiate a grab action.
> fix(Interaction): remove valid controller check from secondary action - fixes #1453

- Assets/VRTK/Examples/014_Controller_SnappingObjectsOnGrab.unity
- Assets/VRTK/Examples/016_Controller_HapticRumble.unity
- Assets/VRTK/Examples/021_Controller_GrabbingObjectsWithJoints.unity
- Assets/VRTK/Examples/023_Controller_ChildOfControllerOnGrab.unity
- Assets/VRTK/Examples/026_Controller_ForceHoldObject.unity
- Assets/VRTK/Examples/032_Controller_CustomControllerModel.unity
- Assets/VRTK/Examples/043_Controller_SecondaryControllerActions.unity
- Assets/VRTK/Examples/ExampleResources/Prefabs/BasicArrow.prefab
- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_BaseGrabAttach.cs
- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_BaseJointGrabAttach.cs
- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_ChildOfControllerGrabAttach.cs
- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_TrackObjectGrabAttach.cs
The Grab Attach Mechanics were using a Eular angle to determine the
grabbed rotation which meant the actual rotation values were odd even
though the grabbed rotation was correct.
The Track Object grab mechanic didn't use a Eular and used an
inverted Quaternion which was correct but required the snap handles
to be flipped to work as the other grab mechanics worked with the
snap handles.
As the other grab mechanics now all use the quaternion and not the
eular to determine their rotation, it means that all snap handles
work the same and don't require any flipping.
This also means that the existing values for any snap handles will
be incorrect and will need inverting to work correctly again.
All of the example scenes have been updated to reflect the breaking
change and …
> fix(Interaction): determine grab rotation based on quaternion not eular - fixes #1171

- Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractableObject_UnityEvents.cs
The Interactable Object Unity Events script was declaring two events
called `OnEnable` and `OnDisable` which were causing warnings as those
names are also reserved for the `MonoBehaviour` methods.
> fix(Interaction): change event name to prevent overriding base method

- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_IndependentRadialMenuController.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_PanelMenuController.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_RadialMenu.cs
- Assets/VRTK/Prefabs/Resources/Scripts/VRTK_SnapDropZone.cs
- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_MaterialColorSwapHighlighter.cs
- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_MaterialPropertyBlockColorSwapHighlighter.cs
- Assets/VRTK/Scripts/Interactions/SecondaryControllerGrabActions/VRTK_ControlDirectionGrabAction.cs
- Assets/VRTK/Scripts/Interactions/VRTK_ObjectAppearance.cs
- Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs
- Assets/VRTK/Scripts/UI/VRTK_UICanvas.cs
A number of files were not adhering to the coding conventions and
using the `var` keyword or using `foreach` instead of `for`.
Also some coroutines were not being started and stopped correctly
without necessary checking before stopping.
> refactor(Structure): apply coding conventions to codebase - fixes #1459

- Assets/VRTK/Prefabs/Resources/SubPrefabs/RadialMenuButton/UICircle.cs
- Assets/VRTK/SDK/Base/SDK_BaseHeadset.cs
- Assets/VRTK/SDK/Oculus/SDK_OculusBoundaries.cs
- Assets/VRTK/SDK/Simulator/SDK_InputSimulator.cs
- Assets/VRTK/SDK/SteamVR/SDK_SteamVRHeadset.cs
- Assets/VRTK/Scripts/Controls/3D/Utilities/VRTK_ContentHandler.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Control.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Slider.cs
- Assets/VRTK/Scripts/Controls/3D/VRTK_Wheel.cs
- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_BaseJointGrabAttach.cs
- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_CustomJointGrabAttach.cs
- Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_RotatorTrackGrabAttach.cs
- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_BaseHighlighter.cs
- Assets/VRTK/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
- Assets/VRTK/Scripts/Interactions/SecondaryControllerGrabActions/VRTK_AxisScaleGrabAction.cs
- Assets/VRTK/Scripts/Internal/VRTK_PlayerObject.cs
- Assets/VRTK/Scripts/Internal/VRTK_RoomExtender_PlayAreaGizmo.cs
- Assets/VRTK/Scripts/Internal/VRTK_UIGraphicRaycaster.cs
- Assets/VRTK/Scripts/Internal/VRTK_VRInputModule.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_PlayerClimb.cs
- Assets/VRTK/Scripts/Locomotion/VRTK_RoomExtender.cs
- Assets/VRTK/Scripts/Pointers/VRTK_PlayAreaCursor.cs
- Assets/VRTK/Scripts/Presence/VRTK_HeadsetControllerAware.cs
- Assets/VRTK/Scripts/UI/VRTK_UIDropZone.cs
- Assets/VRTK/Scripts/UI/VRTK_UIPointer.cs
- Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_ObjectFollow.cs
- Assets/VRTK/Scripts/Utilities/VRTK_AdaptiveQuality.cs
- Assets/VRTK/Scripts/Utilities/VRTK_PolicyList.cs
- Assets/VRTK/Scripts/Utilities/VRTK_SharedMethods.cs
The coding conventions about not using `var` and preferring `for`
over `foreach` has been applied to more code.
> refactor(Structure): apply coding conventions to scripts

- Assets/VRTK/Prefabs/Internal/Scripts/VRTK_RadialMenu.cs
The angles of the generated buttons was being calculated incorrectly
due to a division by an integer rather than a float which caused
certain button amounts to unevenly distribute around the radial
menu (e.g. 7 buttons).
Any reference to a float should use a float in the calculation or
equation by defining the `f` suffix to ensure it doesn't fall back
to using integers.
Thanks to @rivierasolutions for the fix.
> fix(RadialMenu): ensure button placement is calculated correctly

- Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs
The Interact Touch script could potentially return a null exception
error when calling the `ControllerColliders` method because if the
condition was false it would still try and perform a `GetComponent`
on a null object.
It was also not necessary to do the GetComponents or
GetComponentsInChildren check as the latter will also get components
in the current object as well as the children.
> fix(Interaction): prevent null exception when getting touch colliders - fixes #1478

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Examples/ExampleResources/Scripts/SnapDropZoneGroup_Switcher.cs
- Assets/VRTK/Prefabs/Internal/Scripts/VRTK_SnapDropZone.cs
The SnapDropZone has been refactored to now utilise the
interactable object over a simple GameObject. This also
enables the ability to listen for the ungrab event on the
interactable object and then determine the snap on that event
rather than constantly polling in the OnTriggerStay method for
the snap event.
This also means that the default snapped object has been deprecated
and an interactable object is provided as the default.
Only interactable objects can be snapped so this makes more sense.
> feat(SnapDropZone): use interaction events for snapping - fixes #1472

- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKSetupSwitcher.cs
A new checkbox on the SDK Setup Switcher that when checked will
synchronise the play area transform to the previous play area transform
when the SDK is switched.
This is useful when wanting to move the play area around with the
Simulator and then switch to an SDK of an actual HMD and be in the
position of where the Simulator was moved to.
> feat(SDK): ability to synchronise the play area transform on sdk switch

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Editor/VRTK_SDKSetupEditor.cs
- Assets/VRTK/Source/SDK/Unity/SDK_UnityCameraRig.cs
- Assets/VRTK/Source/SDK/Unity/SDK_UnityControllerTracker.cs
- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_AdaptiveQuality.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_DeviceFinder.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_SharedMethods.cs
Unity 2017.2 has changed all of the VR packages and VR class names
and renamed them to XR. To ensure future proofing, all of the
references to VR classes have been updated XR and then script
define symbols for any Unity version older than 2017.2 create
class aliases from the old VR convention to the new XR convention.
The VRSettings.renderScale method has been completely renamed so
it's not possible to alias it. In this case a new helper method
has been created in SharedMethods that allows the retrieval of
the renderScale and another method which sets it.
> chore(Structure): support new XR naming convention in 2017.2

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Prefabs/AvatarHands/BasicHands/Models/VRTK_BasicHand_AnimationController.controller
- Assets/VRTK/Prefabs/Internal/Scripts/VRTK_AvatarHandController.cs
- Assets/VRTK/Source/Editor/VRTK_InteractHapticsEditor.cs
- Assets/VRTK/Source/Editor/VRTK_ObjectSetup.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractGrab.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractHaptics.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractNearTouch.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractNearTouch.cs.meta
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractObjectAppearance.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractObjectHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractObjectHighlighter.cs.meta
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractTouch.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractUse.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractableObject.cs
- Assets/VRTK/Source/Scripts/Utilities/UnityEvents/VRTK_InteractHaptics_UnityEvents.cs
- Assets/VRTK/Source/Scripts/Utilities/UnityEvents/VRTK_InteractNearTouch_UnityEvents.cs
- Assets/VRTK/Source/Scripts/Utilities/UnityEvents/VRTK_InteractNearTouch_UnityEvents.cs.meta
- Assets/VRTK/Source/Scripts/Utilities/UnityEvents/VRTK_InteractObjectHighlighter_UnityEvents.cs
- Assets/VRTK/Source/Scripts/Utilities/UnityEvents/VRTK_InteractObjectHighlighter_UnityEvents.cs.meta
- Assets/VRTK/Source/Scripts/Utilities/UnityEvents/VRTK_InteractableObject_UnityEvents.cs
The Interact Near Touch script generates a collider around the
controller that should be larger than the controller collider and
then when the controller is near something it will emit a near
touch event.
This can be useful for knowing what the controllers are near.
> feat(Interaction): add near touch interactions

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Interactions/VRTK_ControllerHighlighter.cs
The Controller Highlighter script was not using the correct model alias
or the correct actual controller model if one was specified. It would
also fail if the SDK Manager was switched to another SDK.
This has been fixed by ensuring the references to the relevant objects
are set accordingly and not overridden incorrectly.
> fix(Interaction): ensure controller highlighter uses correct aliases

- Assets/VRTK/Prefabs/Internal/Scripts/VRTK_ControllerTooltips.cs
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractGrab.cs
There were a couple of warnings being thrown because code was not being
used anywhere.
> refactor(Structure): remove code that is no longer required

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_BaseHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_MaterialColorSwapHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_MaterialPropertyBlockColorSwapHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_ControllerHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractableObject.cs
The Interactable Object script now has an additional parameter that
allows injecting a Base Highlighter for the Interactable Object to
use.
This means that the Highlighter does not need to be on the same
GameObject as the Interactable Object and can also be swapped out
at runtime for a different highlighter.
To enable this to work, the Highlighters now can accept new
GameObject parameter in the Initialise method. This GameObject
parameter is the second parameter pushing the `options` parameter
to the 3rd param which will cause a breaking change for anyone
using the existing code.
> feat(Interaction): provide custom highlighter to interactable object

- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractGrab.cs
The Interact Grab script requires the `IsValidGrabAttempt` method
to be called to set up state for future method calls.
This was removed during a cleanup that said the line was not being
used, but the variable it was being assigned to wasn't being used,
however, the method call was still required.
> fix(Interaction): ensure valid grab attempt is called

- Assets/VRTK/Prefabs/Internal/Scripts/VRTK_SnapDropZone.cs
The Snap Drop Zone will automatically unsnap an object if it leaves the
trigger collider of the snap drop zone. However, this isn't always the
correct result. If the snap drop zone is using a joint snap and the
joint is set to infinity, then it would never be expected to break the
joint. Also, if the interactable object can only be dropped in snap
drop zones then forcing it out of the snap drop zone when it leaves
the trigger collider is also incorrect.
> fix(SnapDropZone): prevent unwanted unsnap on leaving trigger collider

- Assets/VRTK/Prefabs/Internal/Scripts/VRTK_SnapDropZone.cs
A previous commit made it so it was not possible to unsnap objects
from Snap Drop Zones when they left the trigger collider if they were
considered objects that should not be able to be unsnapped.
However, this caused an issue that it was not possible to grab objects
out of snap drop zones either without releasing them and having them
snap straight back into the snap drop zone.
This issue ensures any grabbed object can be removed from a snap drop
zone.
> fix(SnapDropZone): allow grab remove from unsnappable joints

- Assets/VRTK/Prefabs/Internal/Scripts/VRTK_SnapDropZone.cs
The highlight object on the Snap Drop Zone was casting a shadow and
was also set to receive shadows. This fix forces all mesh renderers
of the snap drop zone to not cast or receive shadows.
> fix(SnapDropZone): remove shadows from highlight object

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_ControllerHighlighter.cs
The Controller Highlighter sript now has an additional parameter that
allows injecting a Base Highlighter for the Controller Highlighter to
use.
There has also been a slight fix to the Outline Highlighter where it
wouldn't set up child materials with the correct colour.
> feat(Interaction): provide custom highlighter to controller highlighter

- Assets/VRTK/Source/Scripts/Pointers/VRTK_Pointer.cs
The Pointer script will now attempt to find a Pointer Renderer
on the same GameObject or any children if the Pointer Renderer
parameter is not set. If it cannot find one then it will auto
generate a Straight Pointer Renderer.
This means if a Pointer is not configured correctly, then at least
some functionality will be available preventing the assumption
that things are broken.
> feat(Pointers): auto create pointer renderer if not set

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Interactions/VRTK_InteractGrab.cs
- Assets/VRTK/Source/Scripts/Pointers/VRTK_PlayAreaCursor.cs
The Play Area Cursor script can now accept a Pointer Direction
Indicator which if provided will be used to amend the rotation of the
Play Area Cursor to match the Pointer Direction Indicator.
If no Pointer Direction Indicator is provided then the rotation will
simply match the Playarea rotation.
> feat(Pointers): match play area cursor rotation to direction indicator - fixes #1499

- Assets/VRTK/Source/Scripts/Internal/VRTK_CurveGenerator.cs
- Assets/VRTK/Source/Scripts/Pointers/PointerRenderers/VRTK_BezierPointerRenderer.cs
- Assets/VRTK/Source/Scripts/Pointers/VRTK_Pointer.cs
There was an issue where if the Pointer was active in the scene but
either the Pointer script or the Pointer Renderer script were disabled
then the Pointer Renderer would stay visible on the screen.
This fix ensures that when the Pointer script is disabled it
automatically calls `Toggle(false)` to turn off the pointer and also
checks the state of the attached Pointer Renderer and if it is disabled
the `Toggle(false)` is also called to ensure the pointer is disabled.
> fix(Pointers): turn off renderer when either script is disabled

- Assets/VRTK/Prefabs/Internal/Scripts/VRTK_IndependentRadialMenuController.cs
- Assets/VRTK/Prefabs/Internal/Scripts/VRTK_RadialMenu.cs
- Assets/VRTK/Prefabs/Internal/Scripts/VRTK_RadialMenuController.cs
Allow the player to touch the centre of the touchpad without
immediately triggering the OnHoverEnter event of a button.
> feat(RadialMenu): add dead zone to radial menu - fixes #1486

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Utilities/VRTK_DeviceFinder.cs
The Oculus Rift headset can have a rare reported type of es07 which
is now being caught and returned correctly.
Thanks to @avik-das for identifying the issue.
> fix(DeviceFinder): add oculus headset type for rare es07

- Assets/VRTK/Prefabs/Internal/Scripts/VRTK_SnapDropZone.cs
This stops removing RigidBodys from failing cause Joints depends on them.
> fix(SnapDropZone): remove all joints before removing rest - fixes #1517

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Utilities/UnityEvents/VRTK_SlingshotJump_UnityEvents.cs
- Assets/VRTK/Source/Scripts/Utilities/UnityEvents/VRTK_SlingshotJump_UnityEvents.cs.meta
The Slingshot Jumpt script now has a Unity Event Helper script to
allow for unity events to be used in place of C# delegates.
> feat(Locomotion): add unity event helper for slingshot jump

- Assets/VRTK/SDK/Simulator/SDK_InputSimulator.cs
This fixes the simulator mouse cursor lock to behave as expected with
the "Always" selection of the "Mouse movement input" mode and actually
lock the cursor in the game view.
> fix(Simulator): ensure mouse lock behaviour works correctly

- Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs
- Assets/VRTK/Scripts/Interactions/VRTK_InteractUse.cs
When the override grab or use buttons are set and reset it also needs
to call the ManageListeners method otherwise the override button
will get reset to the wrong button if multiple touches on the object
occur.
> fix(Interaction): ensure override buttons are reset correctly - fixes #1535

- Assets/VRTK/Source/Scripts/Locomotion/VRTK_TouchpadControl.cs
There was an issue where if the touchpad was being held down when the
scene started and then released, the other touchpad control enable
state was being set to disabled because the touchpad axis change
hadn't occurred therefore the previous object control state was
always being set to false.
> fix(Locomotion): correctly set other touchpad control enable state - fixes #1521

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Internal/Materials/Resources/TunnelOverlay.mat
- Assets/VRTK/Internal/Materials/Resources/TunnelOverlay.mat.meta
- Assets/VRTK/Source/Scripts/Internal/Shaders/VRTK_TunnelEffect.shader
- Assets/VRTK/Source/Scripts/Internal/Shaders/VRTK_TunnelEffect.shader.meta
- Assets/VRTK/Source/Scripts/Internal/VRTK_TunnelEffect.cs
- Assets/VRTK/Source/Scripts/Internal/VRTK_TunnelEffect.cs.meta
- Assets/VRTK/Source/Scripts/Locomotion/VRTK_TunnelOverlay.cs
- Assets/VRTK/Source/Scripts/Locomotion/VRTK_TunnelOverlay.cs.meta
The Tunnel Overlay script creates a texture overlay that can increase
in it's radius towards the centre of the screen to reduce the perceived
field of view.
This can be triggered based on the movement and rotation of the play
area to reduce nausea with artificial locomotion. The tunnel effect
can also be applied when stationary to simulate effects such as damage
being taken.
Thanks to @reznovVR for the original port of the excellent
UnityVRTunnelling repo by @sixways:
https://github.com/SixWays/UnityVrTunnelling
> feat(Locomotion): add tunnel overlay camera effect for comfort options - fixes #222

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Internal/VRTK_SDKControllerReady.cs
- Assets/VRTK/Source/Scripts/Internal/VRTK_SDKControllerReady.cs.meta
- Assets/VRTK/Source/Scripts/Utilities/VRTK_DeviceFinder.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_SDKObjectState.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_SDKTransformModify.cs
The Controller Ready event wasn't being emitted correctly due to the
SDK switching happening when the scene first starts. This meant that
the SDK Transform Modify and SDK Object State script were not working
on SDK switch correctly.
The solution is to ensure the Controller Ready event is always
unregistered and re-registered when then SDK setup changes.
This now happens in a new base script called SDK Controller Ready and
the relevant scripts that need to deal with the controller being ready
can now just extend that script and have access to the controller ready
event even when the SDK setup switches.
The Device Finder has also had a few more methods that make it easy
to find the Controller Reference of the left or right hand.
> fix(Utilities): ensure controller ready event happens on sdk switch

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractableObject.cs
The Interactable Object now relies on the Interact Object Highlighter
to handle highlighting and previously if a highlight colour wasn't
provided then the base Material Colour Swap highlighter wasn't
automatically added to the Interactable Object GameObject.
Since the Interact Object Highlighter was added, the base Highlighter
was always being added to the Interactable Object even if no
highlighting was occurring.
The fix is to only initialise the highlighter if a highlight colour
is available (i.e. not set to Color.clear).
> fix(Interaction): prevent object highlighter always being created - fixes #1545

- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractableObject.cs
The Grab Attach or Action should only be found on the same GameObject
as the Interactable Object otherwise nested Interactable Object
Attach/Actions can be used incorrectly.
> fix(Interaction): do not look for grab attach/action in children

- Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
The `makeRendererVisible` list was being cleared during a loop within
the loop so it wasn't being cleared correctly.
The better approach is to simply clear the entire list after the loop
is done.
> fix(Pointers): ensure visible renderers list is cleared correctly

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Source/Scripts/Utilities/ObjectFollow/VRTK_TransformFollow.cs
The Straight Pointer Renderer position was being updated using the
Transform Follow script and this was defaulting to using the
OnPreRender moment to update position. This had a knock on effect
that the pointer Object Interactor position was being updated in a
Fixed Update but this meant that the Object Interactor position was
not correctly updated to the correct pointer position as the pointer
position was always slightly slower due to being on the OnPreRender
setting.
The solution is to ensure the Pointer position is updated via
FixedUpdate as well to ensure the position of the pointer is correct
for when the Object Interactor is updated in the Fixed Update routine.
> fix(Pointer): update pointer position in fixed update

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Prefabs/AvatarHands/VRTK_AvatarHandController.cs
The Avatar Hand Controller script can now have a custom Model
Transform injected into the inspector component in case the
model is not a child called `Model`.
> feat(Avatar): allow custom model to be provided - resolves #1567

- Assets/VRTK/Source/Scripts/Utilities/VRTK_SharedMethods.cs
In Unity 5.5.4 you get this error:
`Assets/VRTK/Source/Scripts/Utilities/VRTK_SharedMethods.cs(359,20):
error CS0103: The name 'VRStats' does not exist in the current context`
The error disappears changing `VRStats` to `XRStats`.
> fix(Utilities): fixed error for Unity versions prior to 5.6

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/SDK/Base/SDK_BaseHeadset.cs
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/Source/SDK/Unity/SDK_UnityController.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_DeviceFinder.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_SDKObjectState.cs
The Headsets enum has been moved from the DeviceFinder to the
SDK BaseHeadset script to keep in line with the controllers enum
being in the SDK BaseController script.
Additional Headset types have been added for GearVR supported devices
and for Daydream and Cardboard. As Google devices don't report
differences between the devices the summary and detail both return
the same response of `Daydream` or `GoogleCardboard`.
> feat(SDK): add new headset types and move to base headset sdk

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Locomotion/VRTK_HeightAdjustTeleport.cs
The Height Adjust Teleport script now has a new option that will also
apply the play area parent position as an offset when teleporting.
This fixes issues with headsets that aren't room scale aware and
therefore cannot determine where the floor is so will always send the
HMD view to the point of teleport. This would cause the user to
be teleported into the floor.
This new feature allows for the play area camera rig to be placed
in a parent GameObject and that parent GameObject to have a Y position
set on it to be used as the default standing height of the HMD view.
> feat(Locomotion): apply play area parent position to teleporter - fixes #1559

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Editor/Attributes.meta
- Assets/VRTK/Source/Editor/Attributes/MinMaxRangeDrawer.cs
- Assets/VRTK/Source/Editor/Attributes/MinMaxRangeDrawer.cs.meta
- Assets/VRTK/Source/Editor/DataTypes/Limits2DDrawer.cs
- Assets/VRTK/Source/Editor/DataTypes/Limits2DDrawer.cs.meta
- Assets/VRTK/Source/Editor/DataTypes/Vector3StateDrawer.cs
- Assets/VRTK/Source/Editor/VRTK_AdaptiveQualityEditor.cs
- Assets/VRTK/Source/Editor/VRTK_EditorUtilities.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Artificial/VRTK_ArtificialRotator.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Artificial/VRTK_ArtificialSlider.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_PhysicsRotator.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_PhysicsSlider.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/GrabAttachMechanics/VRTK_MoveTransformGrabAttach.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/GrabAttachMechanics/VRTK_RotateTransformGrabAttach.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/SecondaryControllerGrabActions/VRTK_AxisScaleGrabAction.cs
- Assets/VRTK/Source/Scripts/Internal/Attributes.meta
- Assets/VRTK/Source/Scripts/Internal/Attributes/MinMaxRangeAttribute.cs
- Assets/VRTK/Source/Scripts/Internal/Attributes/MinMaxRangeAttribute.cs.meta
- Assets/VRTK/Source/Scripts/Internal/DataTypes/Limits2D.cs
- Assets/VRTK/Source/Scripts/Internal/DataTypes/Limits2D.cs.meta
- Assets/VRTK/Source/Scripts/Internal/DataTypes/SerializedPropertyExtensions.cs
- Assets/VRTK/Source/Scripts/Internal/DataTypes/SerializedPropertyExtensions.cs.meta
- Assets/VRTK/Source/Scripts/Internal/DataTypes/Vector3State.cs
- Assets/VRTK/Source/Scripts/Internal/DataTypes/Vector3State.cs.meta
- Assets/VRTK/Source/Scripts/Utilities/VRTK_AdaptiveQuality.cs
In a number of scripts, standard data types were being used but created
confusion in meaning, such as using a `Vector2` for a min/max range as
this would then display in the editor as `x` and `y` values, with `x`
being minimum and the `y` being maximum.
This has now been replaced with a new `Limits2D` data type that
displays the same 2 float input boxes as a `Vector2` but instead uses
the labels of `min` and `max` which makes a lot more sense.
The `Limits2D` data type can also have a new custom attribute applied
to it called `[MinMaxRange]` which works in a similar way to `[Range]`
but it provides 2 slider points that can be dragged to set a minimum
and maximum value for the control. It should also work with a Vector2
if required.
The Axis Scale Grab Action has also …
> feat(Structure): provide custom data types to convey better meaning - fixes #1579

- Assets/VRTK/Source/Editor/Attributes/MinMaxRangeDrawer.cs
- Assets/VRTK/Source/Editor/Attributes/SerializedPropertyExtensions.cs
- Assets/VRTK/Source/Editor/DataTypes/Limits2DDrawer.cs
- Assets/VRTK/Source/Editor/DataTypes/Vector3StateDrawer.cs
- Assets/VRTK/Source/Scripts/Internal/Attributes/MinMaxRangeAttribute.cs
- Assets/VRTK/Source/Scripts/Internal/DataTypes/Limits2D.cs
- Assets/VRTK/Source/Scripts/Internal/DataTypes/Vector3State.cs
To prevent name collisions with 3rd party scripts, the editor datatypes
and attributes used by VRTK are now within the VRTK namespace.
The Serialized Property Extensions script is also now included in the
VRTK namespace in case 3rd party scripts are also using this same
script causing it to be in the project twice.
> fix(Internal): add editor datatypes and attributes to VRTK namespace - fixes #1590

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/SDK/Base/SDK_BaseController.cs
- Assets/VRTK/Source/SDK/Daydream/SDK_DaydreamController.cs
- Assets/VRTK/Source/SDK/Fallback/SDK_FallbackController.cs
- Assets/VRTK/Source/SDK/HyperealVR/SDK_HyperealVRController.cs
- Assets/VRTK/Source/SDK/Oculus/SDK_OculusController.cs
- Assets/VRTK/Source/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/Source/SDK/Unity/SDK_UnityController.cs
- Assets/VRTK/Source/SDK/VRTK_SDK_Bridge.cs
- Assets/VRTK/Source/SDK/Ximmerse/SDK_XimmerseController.cs
- Assets/VRTK/Source/Scripts/Internal/VRTK_VRInputModule.cs
- Assets/VRTK/Source/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Source/Scripts/Pointers/VRTK_Pointer.cs
- Assets/VRTK/Source/Scripts/UI/VRTK_UIPointer.cs
Previously the Pointer and UIPointer would use the transform of the
controller for the pointer origin and forward, but for SteamVR due
to different controllers being at different orientations it would
use a custom origin via the `GenerateControllerPointerOrigin` method.
This is not required as the `tip/attach` GameObject in a SteamVR
controller is already at the correct orientation for determining the
appropriate pointer origin.
This fix now ensures this tip is used for determining the pointer
origin and the `GenerateControllerPointerOrigin` class has been
deprecated as no other SDKs used it except for SteamVR and SteamVR
already has a built in mechanism for dealing with this complication.
The Pointer and UIPointer also have a new `Attached To` parameter
which can be used to determine …
> fix(Pointers): use appropriate tip for determining pointer origin

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Examples/025_Controls_Overview.unity
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Artificial/VRTK_ArtificialRotator.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_BasePhysicsControllable.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_PhysicsRotator.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_PhysicsSlider.cs
- Assets/VRTK/Source/Scripts/Utilities/ObjectFollow/VRTK_RigidbodyFollow.cs
The Physics Controllables previously had an `Auto Interaction` option
which would automatically create a Controller Rigidbody Activator on
the control if one was not already present.
This caused a number of issues where the Rigidbody Activator collider
was not of the correct size and would lead to confusion with the
controls. The simplest solution is to just remove the mechanism all
together and expect the Rigidbody Activator prefab to be added
manually when it's required.
Example scene 25 has been updated to reflect this change.
> chore(Interaction): remove physics controllable auto interaction option

- Assets/VRTK/Source/Scripts/Internal/VRTK_SDKControllerReady.cs
The SDK Controller Ready script was only attempting to register the
controller ready check if a valid controller reference was found.
However, with SteamVR and possibly other SDKs the controller is not
actually ready at start up and takes a few moments before it's ready
meaning the controller reference is not valid.
The registration of the controller ready checks should always be
done anyway and not only if a valid controller is ready as the
SDK event is emitted when the actual SDK reports the controller as
being ready.
> fix(Internal): ensure controller ready registration is always done

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Interactions/Interactables/GrabAttachMechanics/VRTK_TrackObjectGrabAttach.cs
The Track Object Grab Mechanic had an internal parameter for the
Max Distance Delta used within the MoveTowards method. However, this
was always set to `10f` but on occasion it was prudent to change this
value to something else. The simplest solution is to just expose this
parameter to allow the user to set it to what they need it to be.
> feat(Interaction): expose max distance delta parameter on track grab - fixes #1563

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Internal/Materials/Resources/TunnelOverlay.mat
- Assets/VRTK/Source/Scripts/Internal/Shaders/VRTK_TunnelEffect.shader
- Assets/VRTK/Source/Scripts/Locomotion/VRTK_TunnelOverlay.cs
The view in which the Tunnel Overlay fades out to can now have a
Cubemap texture provided to display as a static skybox to provide a
better point of reference.
The Effect Color can also be used to tint the skybox texture if
required.
Thanks to @jwnjwn for the work on this!
Example Cubemap texture -> ![image](https://user-images.githubusercontent.com/1029673/32651257-78a009c2-c5f8-11e7-8af3-51da0a7230c6.png)
> feat(Locomotion): option to add skybox texture to tunnel overlay cage

- Assets/VRTK/Examples/005_Controller_BasicObjectGrabbing.unity
The basic object grabbing scene had the simulator auto populate
checkbox unchecked so it wasn't automatically finding the camera rig
elements.
> fix(Examples): auto populate simulator objects in basic grabbing scene

- Assets/VRTK/Source/Scripts/Pointers/VRTK_Pointer.cs
The Controller Reference was only set when the activation button was
pressed which meant that the enter event would not emit until the
activation button was pressed. This caused an issue when the
`Activate On Enable` option was set as the Controller Reference
had not been set at that point.
> fix(Pointers): ensure controller reference set when controller found - fixes #1610

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Editor/VRTK_SDKManagerEditor.cs
- Assets/VRTK/Source/Editor/VRTK_SDKSetupEditor.cs
- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs
There was an issue with Unity 2017.2 where it would display a warning
when trying to manage the VR settings due to the Facebook and Switch
platform not being supported.
The new Target Platform Group Exclusions will allow for these two
platforms to be automatically excluded but also the array can be
updated with additional platforms if required.
> feat(SDK): add option to exclude target build platforms

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Internal/VRTK_UIGraphicRaycaster.cs
- Assets/VRTK/Source/Scripts/UI/VRTK_UIPointer.cs
The UI Pointer can now have it's raycast length limited by a script
parameter.
It stores the parameter against the pointer id in a static dictionary
that is then read by the Graphics Raycaster to determine the max
raycast length.
> feat(Pointers): add max length option to ui pointer

- Assets/VRTK/Source/Editor/VRTK_SDKSetupEditor.cs
The `playmodeStateChanged` event has been replaced in 2017.2 with
`playModeStateChanged` and there needs to be a platform dependent
define to ensure compatibility with both the 2017.2 version of Unity
and the older versions which use the older event name.
> fix(SDK): ensure deprecated event is only used in old unity version

- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs
Add a check in `VRTK_SDKManager` on Unity version when initializing 
`excludeTargetGroups` to avoid the error `'UnityEditor.BuildTargetGroup'
does not contain a definition for 'Switch'`.
> fix(SDK): let SDKManager work with Unity versions prior to 2017.1

- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs
BuildTargetGroup is defined in `UnityEditor` namespace, exclude the
declaration of `excludeTargetGroups` in `VRTK_SDKManager` if not in
Unity Editor.
> fix(SDK): exclude BuildTargetGroup outside Unity Editor

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Internal/VRTK_UIGraphicRaycaster.cs
- Assets/VRTK/Source/Scripts/UI/VRTK_UIPointer.cs
There was an issue where the pointerID didn't exist when checking the
UI Pointer length which would cause a crash.
This has been fixed by adding a check when retrieving the pointer max
length from the dictionary and making the dictionary protected whilst
providing a static public getter method.
> fix(Pointers): ensure pointer id exists when checking ui pointer length

- Assets/VRTK/Prefabs/SnapDropZone/VRTK_SnapDropZone.cs
The valid object check was being done after a touched object was added
to the valid snap object list, meaning that any object that was not
valid but touching the object would cause the highlighter to display
even if the object was not valid.
> fix(SnapDropZone): ensure valid object check is done at correct point

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/SDK/Base/SDK_BaseHeadset.cs
- Assets/VRTK/Source/SDK/Daydream/SDK_DaydreamHeadset.cs
- Assets/VRTK/Source/SDK/Fallback/SDK_FallbackHeadset.cs
- Assets/VRTK/Source/SDK/HyperealVR/SDK_HyperealVRHeadset.cs
- Assets/VRTK/Source/SDK/Oculus/SDK_OculusHeadset.cs
- Assets/VRTK/Source/SDK/Simulator/SDK_SimHeadset.cs
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRHeadset.cs
- Assets/VRTK/Source/SDK/Unity/SDK_UnityController.cs
- Assets/VRTK/Source/SDK/Unity/SDK_UnityHeadset.cs
- Assets/VRTK/Source/SDK/VRTK_SDK_Bridge.cs
- Assets/VRTK/Source/SDK/Ximmerse/SDK_XimmerseHeadset.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_DeviceFinder.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_SDKObjectState.cs
Previously, the `VRTK_DeviceFinder.GetHeadsetType()` would rely on the
built in Unity methods for determining the headset type, however this
was unsustainable as it didn't report generic enough information and
would mean the list of headset types would grow and grow and ultimately
not provide useful information.
This has now been changed by each SDK now has a `GetHeadsetType` method
that reports a simpler to understand headset type string, so in the
case of the vive, it does not report all of the variants, just reports
"htcvive" and similarly with the rift.
This string is then used to return a new, cleaner enum from the
`VRTK_DeviceFinder.GetHeadsetType()` method and the enum is stored
in the SDK_BaseHeadset class as it's more appropriate.
The usage of `GetHeadsetType` to determine which …
> feat(SDK): utilise underlying sdk to retrieve headset type

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractHaptics.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractObjectAppearance.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractObjectHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractableListener.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractableListener.cs.meta
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_ObjectTouchAutoInteract.cs
The collection of interactable helpers would fail if no Interactable
Object script was available on the GameObject at edit time because
they all attempted to register to the interaction events in the
`OnEnable` method.
This causes issues with other scripts (such as the controllables) if
the Interactable Object is set up at runtime in their `OnEnable`
method as the Interactable Object is not available until the next
frame.
This fix introduces a new base class called Interactable Listener
which provides an interface for how interactable helpers should
attempt to register the interaction events at in `OnEnable` but
if no Interactable Object is found then they will wait till the
end of the the frame and try again when the Interactable Object
should be present.
> fix(Interaction): ensure interactable helpers get reference to object

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Examples/ExampleResources/Scripts/VRTK_ControllerEvents_ListenerExample.cs
- Assets/VRTK/Source/SDK/Base/SDK_BaseController.cs
- Assets/VRTK/Source/SDK/Base/SDK_BaseHeadset.cs
- Assets/VRTK/Source/SDK/SteamVR/Resources/ControllerColliders/SteamVRWindowsMRController_Left.prefab
- Assets/VRTK/Source/SDK/SteamVR/Resources/ControllerColliders/SteamVRWindowsMRController_Left.prefab.meta
- Assets/VRTK/Source/SDK/SteamVR/Resources/ControllerColliders/SteamVRWindowsMRController_Right.prefab
- Assets/VRTK/Source/SDK/SteamVR/Resources/ControllerColliders/SteamVRWindowsMRController_Right.prefab.meta
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRHeadset.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactors/VRTK_ControllerEvents.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_DeviceFinder.cs
The SteamVR SDK also supports Windows Mixed Reality devices but again
has some slight differences such as controller collider shapes and
controller orientations.
The Windows Mixed Reality controller also has an additional thumbstick
as well as a touchpad. The thumbstick is now referred to as
`TouchpadTwo` but only has axis change events as the button press is
reserved as a system event in SteamVR and there is no touch sensing
available.
> feat(SDK): add WindowsMR support for SteamVR

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Prefabs/RadialMenu/VRTK_IndependentRadialMenuController.cs
- Assets/VRTK/Prefabs/RadialMenu/VRTK_RadialMenu.cs
- Assets/VRTK/Prefabs/SnapDropZone/VRTK_SnapDropZone.cs
- Assets/VRTK/Source/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/Source/SDK/Unity/SDK_UnityController.cs
- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_BaseHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_MaterialColorSwapHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_MaterialPropertyBlockColorSwapHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_IgnoreInteractTouchColliders.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractObjectAppearance.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractableObject.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_ObjectTouchAutoInteract.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactors/VRTK_ControllerHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactors/VRTK_ControllerTrackedCollider.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactors/VRTK_InteractNearTouch.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactors/VRTK_InteractTouch.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_ControllerHaptics.cs
- Assets/VRTK/Source/Scripts/Interactions/VRTK_ObjectAppearance.cs
- Assets/VRTK/Source/Scripts/Internal/VRTK_ControllerReference.cs
- Assets/VRTK/Source/Scripts/Internal/VRTK_Logger.cs
- Assets/VRTK/Source/Scripts/Internal/VRTK_UIGraphicRaycaster.cs
- Assets/VRTK/Source/Scripts/Locomotion/VRTK_MoveInPlace.cs
- Assets/VRTK/Source/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Source/Scripts/Presence/VRTK_BodyPhysics.cs
- Assets/VRTK/Source/Scripts/UI/VRTK_UIPointer.cs
- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKInfo.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_SharedMethods.cs
There are a number of places where the use of a List or Dictionary has
unnecessary repetition in checking if a value or key is present before
either adding or removing from the list or dictionary.
There are also times where a value is attempted to be retrieved from
a dictionary but it doesn't exist which would then need to be added
so multiple dictionary lookups are done, which is inefficient. The
proposed changes ensure a single look up is done via `TryGetValue`
which will reduce dictionary usage overhead.
> refactor(Structure): provide helper methods for lists and dictionaries - fixes #1631

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Prefabs/ControllerTooltips/VRTK_ControllerTooltips.cs
- Assets/VRTK/Prefabs/SnapDropZone/VRTK_SnapDropZone.cs
- Assets/VRTK/Source/Editor/Attributes/ObsoleteInspectorDrawer.cs
- Assets/VRTK/Source/Editor/Attributes/ObsoleteInspectorDrawer.cs.meta
- Assets/VRTK/Source/Scripts/Interactions/Interactables/SecondaryControllerGrabActions/VRTK_AxisScaleGrabAction.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractableObject.cs
- Assets/VRTK/Source/Scripts/Internal/Attributes/ObsoleteInspectorAttribute.cs
- Assets/VRTK/Source/Scripts/Internal/Attributes/ObsoleteInspectorAttribute.cs.meta
- Assets/VRTK/Source/Scripts/Locomotion/VRTK_BasicTeleport.cs
- Assets/VRTK/Source/Scripts/Pointers/VRTK_DestinationMarker.cs
- Assets/VRTK/Source/Scripts/Pointers/VRTK_Pointer.cs
- Assets/VRTK/Source/Scripts/UI/VRTK_UIPointer.cs
- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_AdaptiveQuality.cs
The new `[ObsoleteInspector]` attribute is placed above public
inspector parameters in place of the previous `[HideInInspector]`
attribute as hidden deprecated parameters was causing confusion
and this new attribute will display the parameter still but render
the label in a red, italic font so it's obvious there is something
different about the field. The tooltip for the parameter is also
replaced by the obsolete message from the `[System.Obsolete]`
attribute.
> feat(Structure): add ObsoleteInspector attribute

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractObjectHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractableObject.cs
The Interactable Object is no longer responsible for causing the object
to highlight. All of the highlighting code within the Interactable
Object script has now been removed or deprecated. The Interact
Object Highlight script now takes full control of highlighting an
object and it has been improved so it can listen for the events on an
interactable object and affect the highlighting of a different object.
> feat(Interaction): remove highlighting duty from interactable obejct

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Prefabs/PointerDirectionIndicator/VRTK_PointerDirectionIndicator.cs
- Assets/VRTK/Source/SDK/Base/SDK_BaseController.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactors/VRTK_ControllerEvents.cs
- Assets/VRTK/Source/Scripts/Locomotion/VRTK_TouchpadControl.cs
The Vector2Axis from the BaseController script has now been moved to
the Controller Events script as it's only really used by the
controller events and it also requires an `Undefined` state which
wouldn't make sense in the BaseController enum.
> refactor(ControllerEvents): relocate vector2 axis types from sdk

- Assets/VRTK/Source/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
The cached attach point on the Base Pointer Renderer was not being
cleared when the SDK was switched so the transform follow script was
not updating to track the new hand type.
This has been fixed by clearing the cache in the `OnEnable` method
and registering the script with the SDKManager toggle method.
> fix(Pointers): clear cached attach point on sdk change

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Prefabs/PointerDirectionIndicator/VRTK_PointerDirectionIndicator.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_SDKInputOverride.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_SDKInputOverride.cs.meta
- Assets/VRTK/Source/Scripts/Utilities/VRTK_Simulator.cs
A new SDK Input Override script has been added that allows the input
button on the numerous scripts to be changed at runtime based on the
SDK being used or the controller type connected.
(WIP COMMIT)
> feat(Input): ability to switch script input button based on sdk type

- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_MaterialPropertyBlockColorSwapHighlighter.cs
- a bug was introduced with c40d0d8f8e91226430615e10765e55763d12d8e3 that led to materials not being correctly restored to their initial state when unhighlighting
- the reason is that two separate material property blocks need to be stored - one for restoring the intial values and one for modifying material properties during the highlight
> fix(Highlighter): MBP highlighter not restoring material properties

- Assets/VRTK/Prefabs/PointerDirectionIndicator/VRTK_PointerDirectionIndicator.cs
- Assets/VRTK/Source/Scripts/Pointers/VRTK_PlayAreaCursor.cs
- Assets/VRTK/Source/Scripts/Pointers/VRTK_Pointer.cs
The Pointer Direction Indicator will now only work when the script
is active in the current GameObject hierarchy which is useful for
turning the direction indicator on and off by simply disabling a
container parent GameObject.
> fix(Pointers): stop direction indicator working when script disabled

- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_SDKInputOverride.cs
The SDK Input Overrides script was causing null pointer exceptions if
the modifier was null which could happen if the controller wasn't ready
which has also been fixed by making the SDK Manager brute check the
validity of the controller and not just returning the undefined state
straight away.
> fix(Input): ensure modifiers are not null and wait for controller ready

- Assets/VRTK/Source/Scripts/Presence/VRTK_BodyPhysics.cs
The Body Physics script would crash if no foot collider was created
because it would attempt to ignore collisions on a null object.
> fix(Presence): add null checks on colliders before ignoring collisions

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Presence/VRTK_HeadsetCollisionFade.cs
The Headset Collision Fade script can now accept a policy list to
determine which targets cause the headset fade on collision.
> feat(Presence): add policy list to headset collision fade

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Utilities/VRTK_SDKInputOverride.cs
The Input Overrides docs were incorrect, this ensures they make
sense.
> chore(Input): provide correct docs on input overrides

- Assets/VRTK/Source/Scripts/Pointers/VRTK_Pointer.cs
The activation logic has been moved from the button callback method
to it's own separate method as this helps decouple the logic.
> refactor(Pointers): move activation button logic to separate method

- Assets/VRTK/Source/Scripts/Internal/VRTK_UIGraphicRaycaster.cs
When working with additive scenes there is null exception if:
- first scene has a UICanvas, but no camera
- second scene is the one with a camera
As soon as the first scene is loaded, the raycast gives an error
because trying to do an update but there is no camera.
The error stops after the second scene is loaded.
Thanks to @interillusion for the fix.
> fix(UI): check for error with null event camera

- Assets/VRTK/Prefabs/ControllerTooltips/VRTK_ControllerTooltips.cs
- Assets/VRTK/Prefabs/SnapDropZone/VRTK_SnapDropZone.cs
- Assets/VRTK/Source/Editor/VRTK_SDKManagerEditor.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/SecondaryControllerGrabActions/VRTK_AxisScaleGrabAction.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractObjectHighlighter.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractableObject.cs
- Assets/VRTK/Source/Scripts/Locomotion/VRTK_BasicTeleport.cs
- Assets/VRTK/Source/Scripts/Pointers/VRTK_Pointer.cs
- Assets/VRTK/Source/Scripts/UI/VRTK_UIPointer.cs
- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs
The obsolete parameters are now all grouped at the bottom of the script
inspector window and under the header `Obsolete Settings` to make it
easier to identify deprecated variables.
> refactor(Structure): move obsolete parameters to bottom of inspector

- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractObjectAppearance.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_InteractableObject.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/VRTK_ObjectTouchAutoInteract.cs
- Assets/VRTK/Source/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
- Assets/VRTK/Source/Scripts/Presence/VRTK_BodyPhysics.cs
- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs
There was an issue when using a HashSet and a foreach loop that if the
HashSet contents had changed during the iteration then an error would
be thrown.
The solution is to clone the HashSet before iterating over the clone
so any changes to the original HashSet don't affect the iteration.
> fix(Structure): clone HashSet when iterating to prevent change errors

- Assets/VRTK/Source/Editor/VRTK_SDKManagerEditor.cs
- Assets/VRTK/Source/SDK/Daydream/SDK_DaydreamController.cs
- Assets/VRTK/Source/SDK/HyperealVR/SDK_HyperealVRBoundaries.cs
- Assets/VRTK/Source/SDK/HyperealVR/SDK_HyperealVRController.cs
- Assets/VRTK/Source/SDK/HyperealVR/SDK_HyperealVRHeadset.cs
- Assets/VRTK/Source/SDK/Oculus/SDK_OculusBoundaries.cs
- Assets/VRTK/Source/SDK/Oculus/SDK_OculusController.cs
- Assets/VRTK/Source/SDK/Oculus/SDK_OculusHeadset.cs
- Assets/VRTK/Source/SDK/Simulator/SDK_InputSimulator.cs
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRBoundaries.cs
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRHeadset.cs
- Assets/VRTK/Source/SDK/Unity/SDK_UnityBoundaries.cs
- Assets/VRTK/Source/SDK/Unity/SDK_UnityController.cs
- Assets/VRTK/Source/SDK/Unity/SDK_UnityHeadset.cs
- Assets/VRTK/Source/SDK/Ximmerse/SDK_XimmerseBoundaries.cs
- Assets/VRTK/Source/SDK/Ximmerse/SDK_XimmerseController.cs
- Assets/VRTK/Source/SDK/Ximmerse/SDK_XimmerseHeadset.cs
- Assets/VRTK/Source/Scripts/Locomotion/ObjectControlActions/VRTK_BaseObjectControlAction.cs
- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs
- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKSetup.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_SharedMethods.cs
This is an updated proposed fix for https://github.com/thestonefox/VRTK/issues/1580.
It builds on the work done by @peaj in this PR https://github.com/thestonefox/VRTK/pull/1645 with a few minor changes.  
The problem is the same, I'm loading scenes additively and VRTK is only searching the active scene. 
This PR fixes the problem (as originally proposed by @peaj) by iterating through all active scenes and searching for the component rather than only the active scene. 
The main difference in this version vs the one done by @peaj in https://github.com/thestonefox/VRTK/pull/1645 is just that I use a common private method with an option to avoid duplicating the code and leaving room for bugs in that sense.
This PR also remains backwards compatible with the `VRTK_SharedMethods` API, only …
> fix(SharedMethods): change FindEvenInactive to search all loaded scenes

- Assets/VRTK/Source/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
Proposed fix for https://github.com/thestonefox/VRTK/issues/1723
I can't think of a great way to know this object was destroyed from inside `VRTK_BasePointerRenderer` but the null check on the component reference does work.
This also recreates the references when the `ResetPointerObjects` metrhod is called. This is the hook I use on scene unload/load to re-create the objects. 
I know deleting these objects is unlikely in a single scene setup, but it's a quick way to see the error. 
Another possible solution here would be to create the objects in the same scene as the controllers and assume that would never be deleted. The benefit to this would be that it wouldn't require the call to `ResetPointers`, though that change may be warranted regardless? 
It would however require that I change …
> fix(Pointers): handle destroyed origin transform follow

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Interactions/Interactors/VRTK_ControllerEvents.cs
The grip sense axis on the SteamVR knuckles can now be used as a button
press which is useful for using the grip sense for picking up objects.
> feat(Interaction): grip sense axis acts as button press

- Assets/VRTK/Source/Scripts/Locomotion/ObjectControlActions/VRTK_BaseObjectControlAction.cs
- Assets/VRTK/Source/Scripts/Locomotion/ObjectControlActions/VRTK_RotateObjectControlAction.cs
- Assets/VRTK/Source/Scripts/Locomotion/ObjectControlActions/VRTK_SnapRotateObjectControlAction.cs
Player used to have an offset after rotation
through the scripts
VRTK_RotateObjectControlAction and
VRTK_SnapRotateObjectControlAction
(see #1693).
Gameobject [CameraRig] is moved after
rotation to compensate the offset.
> fix(Locomotion): fix player position offset after rotation

- Assets/VRTK/Source/SDK/Oculus/README.md
- Assets/VRTK/Source/SDK/SteamVR/README.md
- README.md
The Oculus SDK for Unity is now available as a Unity asset on the Unity
Asset Store. This package includes the Oculus Avatar package as well so
out of the box provides controller visualisation support.
The documentation has been updated to point to this Unity asset as the
basis for getting Oculus SDK support rather than using the Oculus
Utilities download from the Oculus developer website.
> chore(SDK): provide new location to Oculus SDK download

- Assets/VRTK/Examples/ExampleResources/SharedResources/Scripts/VRTKExample_AdditiveSceneLoader.cs
- Assets/VRTK/Examples/ExampleResources/SharedResources/Scripts/VRTKExample_SceneSwitcher.cs
- ProjectSettings/EditorBuildSettings.asset
Previously, the constructor scene was injected into the
AdditiveSceneLoader component as a `Object` type and then the `name`
of this object was used to identify the constructor scene which worked
fine when running in the Unity Editor but would fail in a build.
This is most likely because the `Object` type is not being injected
in a build and only works due to quirks in the editor.
The solution is now to ensure the final scene in Build Settings is the
constructor scene and then simply to use that index in the
AdditiveSceneLoader component and remove the ability to inject a scene.
> fix(Examples): use final scene index for constructor scene

- Assets/VRTK/Source/Editor/VRTK_PolicyListEditor.cs
- Assets/VRTK/Source/Editor/VRTK_SDKManagerEditor.cs
The `EnumMaskField` method on the `EditorGUILayout` class has been
deprecated in Unity 2017.3 and replaced with `EnumFlagsField`.
This short refactor just ensures the deprecated method is only used
in older versions of Unity where it is still supported.
Thanks to @qubytes for the fix.
> refactor(PolicyList): provide alternative for deprecated EnumMaskField

- Assets/VRTK/Examples/ExampleResources/SharedResources/Scripts/VRTKExample_AdditiveSceneLoader.cs
- Assets/VRTK/Examples/README.md
- Assets/VRTK/Source/Scripts/Internal/VRTK_Logger.cs
- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKSetup.cs
- README.md
There is an issue where the new example scenes don't set the required
VRTK script define symbols because this is done via the SDK Manager
script and that is no longer present in the example scenes as it is
dynamically loaded in via the constructor scene.
This fix simply throws an error if the example scene cannot find the
required scripting define symbols and attempts to provide useful
information for the user to rectify the issue.
> fix(Examples): display error if script define symbols have not been set

- Assets/VRTK/Source/SDK/WindowsMR/Resources/WindowsMR_Camera.cs
- Assets/VRTK/Source/SDK/WindowsMR/Resources/WindowsMR_TrackedObject.cs
- Assets/VRTK/Source/SDK/WindowsMR/SDK_WindowsMRBoundaries.cs
- Assets/VRTK/Source/SDK/WindowsMR/SDK_WindowsMRController.cs
- Assets/VRTK/Source/SDK/WindowsMR/SDK_WindowsMRHeadset.cs
- Assets/VRTK/Source/SDK/WindowsMR/SDK_WindowsMRSystem.cs
Many of the required WindowsMR libraries didn't appear until
Unity 2017.2 and beyond, so this fix ensures that any libraries
that didn't appear until 2017.2 are commented out so they don't
create errors. As Windows MR features shouldn't be used on anything
prior to Unity 2017.3 then this is a fair solution.
> fix(SDK): exclude WindowsMR from unsupported versions of Unity

- Assets/VRTK/Source/Scripts/Utilities/VRTK_SharedMethods.cs
I introduced a change to find even inactive objects in all scenes as opposed to just the currently loaded one (#1725). 
In doing so I was assuming that the scene would be `isLoaded` by the time i wanted to do the search. As discovered by @bddckr, the `Awake`/`Start` methods run before the scene `isLoaded` and this resulted in the shared methods being unable to find certain components during `Awake` and `Start`.
This gets rid of that condition, since scenes retrieved using `sceneCount` and `GetSceneAt` are either loading or loaded.
This also refactors the method to avoid unnecessary iteration when only searching the active scene, and also renames the helper method.
@bddckr @thestonefox
> fix(SharedMethods): find components in loading scenes

- Assets/VRTK/Examples/ExampleResources/SharedResources/Scripts/VRTKExample_AdditiveSceneLoader.cs
- Assets/VRTK/Source/Editor/VRTK_ExampleSetupInfoEditor.cs
- Assets/VRTK/Source/Editor/VRTK_ExampleSetupInfoEditor.cs.meta
- Assets/VRTK/Source/Scripts/Internal/VRTK_Logger.cs
The previous way of attempting to notify the user that they need to
open the example constructor scene before opening any of the example
scenes did not work if no 3rd party SDK was installed that required
it. It would simply just continually throw the error message.
The new solution is not to try and second guess what the set up is
automatically and to just provide a popup window with information
for the user on requiring them to open the constructor example scene.
> fix(Examples): remove script define symbol check and provide popup

- Assets/VRTK/Source/SDK/Daydream/SDK_DaydreamSystem.cs
- Assets/VRTK/Source/SDK/Unity/SDK_UnitySystem.cs
- Assets/VRTK/Source/SDK/Ximmerse/SDK_XimmerseSystem.cs
The latest version of the Google VR SDK (v1.110.0 released 2017-11-08)
uses the string constant "daydream" as the VRSettings.loadedDeviceName.
See GoogleVR/Scripts/GvrSettings.cs
This also applies to the built in Unity SDK for Daydream and for
Cardboard.
Co-authored-by: Ty <2926368+tnterdan@users.noreply.github.com>
> fix(SDK): update Google SDK vrDeviceName

- Assets/VRTK/Documentation/API.md
- Assets/VRTK/Source/Scripts/Presence/VRTK_BodyPhysics.cs
- Assets/VRTK/Source/Scripts/Utilities/VRTK_CustomRaycast.cs
The Body Physics script was doing a BoxCast but always just using the
default `Physics.BoxCast` which meant it never took into consideration
the custom raycast settings being applied.
The CustomRaycast script now contains a CustomBoxCast method that the
Body Physics script is now using which brings it in line with other
raycast types.
> fix(Presence): provide custom boxcast to ensure correct settings used

- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_MaterialColorSwapHighlighter.cs
Fixes #1758 
Base class `Texture` constructor is inaccessible due to protection level.
Update to use `Texture2D.whiteTexture` which has been confirmed not to create new textures at runtime.
> fix(Highlighters): use whiteTexture in place of new Texture

- Assets/VRTK/Source/SDK/Oculus/SDK_OculusController.cs
The Oculus Controller SDK assumed the vendor SDK reports a single
tracked device via its `Controller` enum. This enum is actually a
flag so to handle multiple devices being connected at the same time
this fix ensures to check via the proper binary operations instead
of doing an equality check.
Since VRTK currently only supports returning a single device enum
this change leaves the device importance order untouched.
> fix(SDK): handle multiple Oculus devices - fixes #1762

- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
The shadow casting mode is now copied over from the object's renderer.
Also removed an unnecessary duplicate if statement.
fixes: #1278
> fix(Highlighter): copy shadow casting mode from object renderer - fixes #1278

- Assets/VRTK/Source/SDK/Unity/SDK_UnityController.cs
Add HTC Vive controller joystick names as reported by Unity 2017.4.2f2.
Fixes #1798
> fix(UnityXR): add more joystick names

- Assets/VRTK/Source/SDK/Unity/SDK_UnityController.cs
Add HTC Vive controller joystick names as reported by Unity 2017.4.2f2.
Don't allow the SetTrackedControllerCaches method to re-enter while it's executing since it's possible to call itself and get stuck.
fixes #1764
> fix(UnityXR): fix UnityXR stack overflow

- Assets/VRTK/Source/Scripts/Interactions/Highlighters/VRTK_OutlineObjectCopyHighlighter.cs
Wrong array length was being used.
Also re-added the if statement I removed in a previous commit.
because i'm dumb.
fixes: #1792
> fix(highlighter): index out of range

- Assets/VRTK/Source/Scripts/Internal/VRTK_UIGraphicRaycaster.cs
- Assets/VRTK/Source/Scripts/UI/VRTK_UICanvas.cs
BlockingMask is now transfered across using reflection
GraphicRaycaster -> VRTK_GraphicRaycaster
fixes: #1418
> fix(GraphicRaycaster): transfer BlockingMask across

- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Artificial/VRTK_ArtificialPusher.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Artificial/VRTK_ArtificialRotator.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Artificial/VRTK_ArtificialSlider.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_PhysicsPusher.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_PhysicsRotator.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_PhysicsSlider.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/VRTK_BaseControllable.cs
a SetValue function was added to the base class
all classes implement this
implemented for Sliders & Rotators
not for Pusher because resets anyway
fixes: #1696
> fix(controllables): no longer resets value on re-enable

- Assets/VRTK/Source/SDK/Unity/README.md
The touchpad y-axis in the Unity SDK is backwards from the SteamVR SDK. (Forward is negative instead of positive).
When setting up the inputs for the Unity SDK, it might prevent some confusion to know this ahead of time.
> docs(UnityXR): Add touchpad y-axis information

- Assets/VRTK/Source/SDK/Unity/[UnityBase_CameraRig].prefab
Tag the UnityXR camera rig's camera as MainCamera so that UI
interactions will work.
> fix(UnityXR): Tag the camera rig's camera as MainCamera

- Assets/VRTK/Source/Scripts/Locomotion/VRTK_BasicTeleport.cs
Check for null target before checking to see if it's a player or ui.
Since it will always return false if the target is null anyway, just check it at the top and remove the extra checks.
> fix(BasicTeleport): Fix null reference

- Assets/VRTK/Prefabs/DestinationPoint/VRTK_DestinationPoint.cs
Changed the SetLocation function in VRTK_DestinationPoint.cs.
It now uses eulerAngles instead of localEulerAngles.
> fix(DestinationPoint): Change GetRotation to use eulerAngles - fixes #1775

- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs
- Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKSetup.cs
Unity 2018.1 deprecated the `hierarchyWindowChanged` event and is now
called `hierarchyChanged` so the fix is to do a script define to use
the correct event based on the version.
> fix(SDK): use new hierarcyChanged event introduced in 2018.1

- Assets/VRTK/Source/SDK/Unity/SDK_UnityController.cs
Change the Vive Controller Menu Button (Button Two) to button ids:
2 (left) and 0 (right).
Change button KeyCodes to come from any joystick.
Comment out calls to SetControllerButtonValues since the joystickIndex
shouldn't be different between right and left controllers.
Fixes #1786
> fix(UnityXR): fix HTC Vive button mapping

- Assets/VRTK/Source/SDK/HyperealVR/SDK_HyperealVRController.cs
- Assets/VRTK/Source/SDK/Oculus/SDK_OculusController.cs
- Assets/VRTK/Source/SDK/Simulator/SDK_SimController.cs
- Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRController.cs
- Assets/VRTK/Source/SDK/WindowsMR/SDK_WindowsMRController.cs
- Assets/VRTK/Source/SDK/Ximmerse/SDK_XimmerseController.cs
Fix NPE causing Unity to crash by returning `""` from
`GetControllerElementPath()` instead of `null`.
> fix(Controller): work around crash in Unity 2018.2 #1852

- Assets/VRTK/Prefabs/ControllerTooltips/VRTK_ControllerTooltips.cs
Fix spelling mistake in ControllerTooltips which caused TouchpadTwo to be ignored, due to prior ToLower()-conversion.
> fix(Tooltips): Spelling mistake in touchpadtwo

- Assets/VRTK/Source/SDK/Oculus/SDK_OculusController.cs
Added the missing switch case to handle the value returned by OVRInput.GetConnectedControllers when touch controllers
and a classic controller are active in the same time.
> fix(SDK): handle touch and classic controller plugged in - fixes #1866

- Assets/VRTK/Source/Scripts/Utilities/VRTK_SharedMethods.cs
If a scene is open in the editor, but not loaded like this:  
Then every change in the hierarchy causes an exception like this one:
```
ArgumentException: The scene is not loaded.
UnityEngine.SceneManagement.Scene.GetRootGameObjects (System.Collections.Generic.List`1 rootGameObjects) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/SceneBindings.gen.cs:61)
UnityEngine.SceneManagement.Scene.GetRootGameObjects () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/SceneBindings.gen.cs:45)
VRTK.VRTK_SharedMethods.FindEventInactiveComponentsInScene[VRTK_SDKSetup] (Scene scene, Boolean stopOnMatch) (at Assets/VRTK/Source/Scripts/Utilities/VRTK_SharedMethods.cs:813)
VRTK.VRTK_SharedMethods.FindEvenInactiveComponentsInValidScenes[VRTK_SDKSetup] (Boolean …
```
> fix(SharedMethods): don't search in unloaded scenes

- .gitignore
- Assets/VRTK/Examples/ExampleResources/SharedResources/Scripts/Editor.meta
- Assets/VRTK/Examples/ExampleResources/SharedResources/Scripts/Editor/VRTKExample_FixSetupEditor.cs
- Assets/VRTK/Examples/ExampleResources/SharedResources/Scripts/Editor/VRTKExample_FixSetupEditor.cs.meta
- Assets/VRTK/Examples/ExampleResources/SharedResources/Scripts/VRTKExample_FixSetup.cs
- Assets/VRTK/Examples/ExampleResources/SharedResources/Scripts/VRTKExample_FixSetup.cs.meta
- Assets/VRTK/Examples/[001 - Interactions] ControllerEvents.unity
- Assets/VRTK/Examples/[002 - Pointers] StraightPointer.unity
- Assets/VRTK/Examples/[003 - Pointers] BezierPointer.unity
- Assets/VRTK/Examples/[004 - Locomotion] Teleporting.unity
- Assets/VRTK/Examples/[005 - Interactions] InteractableObjects.unity
- Assets/VRTK/Examples/[006 - Locomotion] MovementTypes.unity
- Assets/VRTK/Examples/[007 - Interactions] InteractionHelpers.unity
The example scenes all have broken Oculus prefab instances unless the
specific version of the Oculus SDK is used. This fix uses a script to
attempt to repair the prefab by recreating the setup automatically.
> fix(Examples): automatically repair broken Oculus prefab instances

- Assets/VRTK/Source/Scripts/Controls/3D/VRTK_Door.cs
- Assets/VRTK/Source/Scripts/Controls/3D/VRTK_Drawer.cs
- Assets/VRTK/Source/Scripts/Controls/3D/VRTK_Lever.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_PhysicsPusher.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_PhysicsSlider.cs
- Assets/VRTK/Source/Scripts/Interactions/Interactors/VRTK_InteractTouch.cs
- Assets/VRTK/Source/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs
Unity 2018.3 seems to have a bug where it does not support continuous
dynamic for the rigidbody collision detection, instead it uses a newly
introduced mode called collision speculative.
This fix wraps all of the places where continuous dynamic is used with
ifdefs to check if the version is Unity 2018.3 or higher and if it is
then it will use the continuous speculative mode instead.
> fix(physics): change collision detection mode for 2018.3

- Samples/Farm/Prefabs/OptionsMenu/OptionsMenu.prefab
- Samples/Farm/Scenes/ExampleScene.unity
The options prefab had empty event listeners in the enable/disable
options. These have been deleted from the default prefab and added
as overrides to the options prefab in the farmyard example scene.
> fix(examples): remove empty event listeners from options prefab

- Prefabs/Helpers/Tooltip/SharedResources/Scripts/TooltipInternalSetup.cs
A using statement that is no longer used has been removed to clean
up the codebase.
> chore(Helpers): remove unused using statement

- Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts/UnityXRConfigurator.cs
When VR is off the existence of the Unity XR camera rig would set
the physics timestep to a really high value, which breaks any
physics usage altogether. The fix is to check whether XR is actually
used.
> fix(CameraRig): don't change the physics settings when XR is off

- README.md
The VRTK repo is now on the ExtendRealityLtd organisation so the
repository link has been updated to reflect this change.
> docs(README): update git url to reflect new ownership

- README.md
The documentation for VRTK is now referred to as the VRTK Academy and
as such the Readme has been updated to reflect this change.
> docs(README.md): update documentation wording to academy

- Prefabs/Interactions/Interactables/SharedResources/Scripts/Grab/Receiver/GrabInteractableReceiver.cs
- Prefabs/Interactions/Interactables/SharedResources/Scripts/Touch/TouchInteractableConfigurator.cs
Redundant using statements have been removed as the namespace they
import is no longer used in the respective type.
> chore(Interactables): remove unused using statements

- README.md
The instructions for how to clone the repo missed out a step that
requires switching to the cloned repo directory before initializing
the submodule. Whilst this may seem obvious, many people who do not
have experience of git will follow the instructions to the letter
and will have no knowledge of why it's not working.
A Documentation section has been added that clearly links to the
VRTK Academy as well for extra clarity.
> docs(README.md): improve cloning the repo instructions

- README.md
The required Unity version seems to be at least 2018.3.5 based on
user testing. Earlier versions have issues checking out the copy of
Malimbe and/or Zinnia used inside VRTK as direct and indirect
dependencies. This change states Unity 2018.3.10f1 as the required
version as it is known to definitely work and comes with an
important bugfix for builds using XR functionality.
> docs(README.md): change required Unity version

- README.md
Unity 2019.1 requires the XR Legacy Input Helpers to be installed as
the XR packages from Unity have been removed from the core product
and put into their own package in the Unity Package Manager.
These instructions describe how to obtain the required package.
> docs(README.md): add instructions for Unity 2019.1 installation

- Prefabs/Interactions/Interactors/SharedResources/Scripts/GrabInteractorConfigurator.cs
If the Interactable was grabbed with a toggle grab type then the
Interactor was no longer colliding with the Interactable (but still
grabbing) then the Interactor Grab publisher would be empty and when
the force ungrab was called it would attempt to do a grab before
ungrabbing to ensure the toggle state was set correctly.
However, it would not be able to perform the grab as the touched state
did not exist to populate the grab publisher.
This fix ensures that if the grab publisher payload is empty then it
forces the current interactable into the payload so the initial
grab before ungrabbing can take place.
> fix(Interactions): allow interactor ungrab on untouched interactable - fixes #1988

- README.md
The project backlog has been moved to GitHub projects as Waffle.io
is being shutdown.
The License badge has also been added to bring it inline with the
other repos.
> docs(README.md): update backlog link to GitHub projects

- Prefabs/Interactions/Controllables/SharedResources/Scripts/DirectionalDriveFacade.cs
- Prefabs/Interactions/Controllables/SharedResources/Scripts/DriveFacade.cs
- Prefabs/Interactions/Controllables/SharedResources/Scripts/RotationalDriveFacade.cs
The Drive Facades now only call the internal `Drive.SetUp()` method
when any property changes occur. Previously, the specific method
on the drive was called and then the `SetUp()` method was called which
made no sense as the `SetUp()` method would call the specific method
again anyway.
The Directional and Rotational Drive Facade `OnAfterChange` methods
didn't even call `SetUp()` so were not correctly setting up the drive
again after property changes. These now just call `SetUp()` the same
as the abstract DriveFacade class.
> fix(Interactions): call only drive setup to manage property changes

- Prefabs/Locomotion/DestinationLocations/SharedResources/Scripts/DestinationLocationConfigurator.cs
The DestinationLocation was calling the HoverActivated event in the
EmitHoverDeactivated method which is wrong. The correct event is
now being called.
> fix(Locomotion): call correct event on location hover deactivation - fixes #2006

- .github/FUNDING.yml
The FUNDING.yml configures the GitHub page to show a link to the Patreon.
> chore(FUNDING.yml): add funding information for patreon

- Prefabs/Interactions/Controllables/SharedResources/Scripts/DirectionalDriveFacade.cs
- Prefabs/Interactions/Controllables/SharedResources/Scripts/RotationalDriveFacade.cs
The Directional and Rotational Drive Facades have been updated so
the gizmos for the axis data are only drawn when the drive GameObject
is selected in the hierarchy as this increases editor performance and
it is not necessary to draw gizmos all the time.
> fix(Interactions): only draw gizmos when drive is selected

- Prefabs/Pointers/SharedResources/Scripts/PointerConfigurator.cs
There was a race condition where the activation action could be
registered before the selection action meaning doing things like
select on release would not work as the activation action was
being called before the selection action so the pointer would be
disabled before it could select anything.
This fix moves around some of the registration logic to ensure
the correct order for actions.
> fix(Pointers): ensure correct order for pointer actions - fixes #2027

- .github/CODE_OF_CONDUCT.md
- .github/ISSUE_TEMPLATE.md
There was a spelling mistake in the Code Of Conduct and the Issue
Template now has an example of providing a very specific Unity version
number as this is generally important in debugging.
> docs(structure): fix spelling mistake and add clearer version number

- Prefabs/Interactions/Controllables/DirectionalJointDrive.prefab
- Prefabs/Interactions/Controllables/RotationallJointDrive.prefab
- Prefabs/Interactions/Controllables/SharedResources/Scripts/ComponentTags.meta
- Prefabs/Interactions/Controllables/SharedResources/Scripts/ComponentTags/ControllableJointDriveContainerTag.cs
- Prefabs/Interactions/Controllables/SharedResources/Scripts/ComponentTags/ControllableJointDriveContainerTag.cs.meta
- Prefabs/Interactions/Interactors/Interactor.prefab
- Prefabs/Interactions/Interactors/SharedResources/NestedPrefabs/Interaction.Touching.prefab
- Samples/Farm/Scenes/ExampleScene.unity
The Interactor ActiveCollisionsContainer now has a new Validity Rule
that only allows interactions to occur with anything that is a type
of Interactable. This means an Interactor can collide with any other
valid collider in the scene but it can only actively interact with
items that pass the new Validity Rule.
> fix(Interactions): treat interactable as only valid active collision - fixes #2032

- Samples/Farm/Scenes/ExampleScene.unity
A new Axis Control for pointer activation/selection has been added to
the example scene to mimic the way WMR handles pointer activation and
selection by only activating the pointer if the thumbstick axis is
pressed forward and then is only deactivated when the thumbstick
Vector2 axis falls underneath a certain threshold (e.g. returns to
the centre).
This example is all done with wiring up Action events and requires no
custom coding. The new feature can be toggled on/off on the Options
Menu Station under the Button/Axis Control lever in the Pointer Options
section.
> feat(examples): windows mixed reality style pointer activate/select

- Prefabs/Interactions/Interactables/SharedResources/NestedPrefabs/GrabActions/Interactable.GrabAction.FollowAction.prefab
- Prefabs/Interactions/Interactables/SharedResources/Scripts/Grab/Action/GrabInteractableFollowAction.cs
The GrabInteractableFollowAction can set the kinematic state of the
consumer rigidbody when the follow action is inactive. This is the
default kinematic state for the rigidbody. Initially this default state
was always whatever the actual consumer rigidbody kinematic state was
initially set to, however there may be times where this inherited
default state may not be required so an additional option has been
added to the GrabInteractableFollowAction to ignore the setting of
the inactive state to that of the consumer rigidbody kinematic state.
This fix is largely based on the work by @JWNJWN but also contains
a fix from @bruno1308 which ensures the `ConfigureFollowTracking`
method is called when the GrabSetup is changed.
Co-authored-by: JWNJWN <jwneicho@gmail.com>
> fix(Interactions): optionally inherit RB kinematic on follow action - Fixes #2047

- Prefabs/Locomotion/Teleporters/SharedResources/NestedPrefabs/SnapToFloor.prefab
The SnapToFloor prefab was set up so the SurfaceLocator would cast a
ray and consider a trigger collider a valid floor. This makes little
sense as a trigger collider is usually used to determine a volume that
can be entered and passed through. The fix is to add a custom
PhysicsCast to the SnapToFloor prefab that has the setting to ignore
trigger colliders for the RayCast. This can then still be disabled
if required.
> fix(Locomotion): prevent teleport snap to floor onto trigger colliders

- Assets/Samples/Farm/Scenes/ExampleScene.unity
- Packages/manifest.json
The pointer grab validity rule was still set to Water meaning pointer
grabbing wasn't working. It has now been set to the correct layer.
OpenVR has also been added to the manifest.json just so it's already
included for anyone wanting to use an OpenVR headset.
> fix(examples): use correct layer for pointer grab validity rule

- Packages/manifest.json
Bumps the dependency of VRTK.Prefabs to the latest version of 1.0.5.
> chore(deps): bump io.extendreality.vrtk.prefabs from 1.0.2 to 1.0.5

- Packages/manifest.json
Bumps the dependency of VRTK.Prefabs to the latest version of 1.0.7.
> chore(deps): bump io.extendreality.vrtk.prefabs from 1.0.5 to 1.0.7

- README.md
Highlight this as just an example project and mention the fact that
VRTK.Prefabs has now been deprecated in place of the Tilia repos.
> docs(README.md): identify as example project and deprecate VRTK.Prefabs

- Assets/Samples/Farm/Scenes/ExampleScene.unity
- Packages/manifest.json
- Packages/packages-lock.json
The pointer grabbers have been updated so they ignore trigger colldiers
so they can grab from snap zones and they also use the snap zone
manager on the before grabbed event to force unsnap from the snap zone
so the grab works correctly.
The snap zones have also been updated to the latest version which
includes a fix for the highlighting logic.
> fix(examples): allow pointer grabbers to retrieve from snap zones

- Assets/Samples/Farm/Prefabs/FireConfettiAction.prefab
There was an issue with the gun particles not appearing to play when
built for Quest. This has been fixed by using the `Play(bool)` method
in the particle system which seems to enforce the particle system to
play the particle process.
> fix(Prefabs): ensure gun particles fire on all platforms
